In [1]:
import pandas as pd
import numpy as np
import oracledb
import os
import platform
import sys
import tomli
import datetime as dt
from check_py import check_security_cf as scf

pd.set_option('float_format', '{:f}'.format)

In [2]:
# Assign pathlink
path_link_db_algo = r"C:\Users\tungtt1\Desktop\bsc_config\config_algo.toml"

# Import files connfiq
with open(path_link_db_algo, mode="rb") as fp:
    config_acc = tomli.load(fp)
    
# Set up config for Oracle SQl Developer
host = config_acc["algo_acc"]["host"]
port = config_acc["algo_acc"]["port"]
service_name = config_acc["algo_acc"]["service_name"]
user = config_acc["algo_acc"]["user"]
password = config_acc["algo_acc"]["password"]

oracledb.init_oracle_client()

# Connect to database Oracle
conn = oracledb.connect(
    user=user,
    password=password,
    dsn=host+"/"+service_name
)

c = conn.cursor()

Check SECURITY_CF_DIRECT

In [3]:
dfd = pd.read_sql_query(
    """ SELECT 
    * 
    FROM SECURITY_CF_DIRECT
    WHERE LENGTH(SECURITY_CODE) = 3
    ORDER BY REPORT_DATE ASC, SECURITY_CODE ASC
    """, con=conn
)

C:\Users\tungtt1\AppData\Local\Temp\45\ipykernel_108940\1185746926.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dfd = pd.read_sql_query(

In [4]:
dfd

,SCN,REPORT_DATE,REPORTED_DATE,FREQ_CODE,SECURITY_CODE,AUDITED,MONTH_IN_PERIOD,SCFD_1_1,SCFD_1_2,SCFD_1,...,SCFD_42_2A,SCFD_42_3A,SCFD_43A,SCFD_44A,SCFD_45A,SCFD_45_1A,SCFD_46A,SCFD_47A,CREATED_DATE,UPDATED_DATE
0,125296,2018-03-31,None,Q,ART,N,3,0.000000,0.000000,-79583632667.000000,...,0.000000,0.000000,0.000000,41678440656.000000,0.000000,0.000000,0.000000,0.000000,2021-06-27 04:45:53,2023-07-12 00:58:30.117840
1,125296,2018-03-31,None,Q,BMS,N,3,0.000000,0.000000,-2443716970884.000000,...,0.000000,0.000000,0.000000,0.000000,1595120445.000000,0.000000,0.000000,0.000000,2021-06-27 04:45:53,2023-07-12 00:58:30.117840
2,125296,2018-03-31,None,Q,BVS,N,3,0.000000,0.000000,-4569299206732.000000,...,0.000000,0.000000,348509314280.000000,0.000000,2228499922.000000,0.000000,0.000000,0.000000,2021-06-27 04:45:53,2023-07-12 00:58:30.117840
3,125296,2018-03-31,None,Q,DSC,N,3,0.000000,0.000000,-177644030937.000000,...,0.000000,0.000000,0.000000,4424831806.000000,0.000000,0.000000,0.000000,0.000000,2021-06-27 04:45:53,2023-07-12 00:58:30.117840
4,125296,2018-03-31,None,Q,HBS,N,3,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2021-06-27 04:45:53,2023-07-12 00:58:30.117840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,43618015,2023-06-30,None,Q,BVS,N,3,0.000000,0.000000,-27323941724365.000000,...,0.000000,0.000000,405948473661.000000,0.000000,11939368336.000000,0.000000,0.000000,837655862828.000000,2023-07-19 12:42:26,2023-07-19 18:00:11.156580
155,43637871,2023-06-30,None,Q,HBS,N,3,0.000000,0.000000,-277855290411.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2023-07-24 15:54:10,2023-07-24 17:00:07.542029
156,43602726,2023-06-30,None,Q,MBS,N,3,0.000000,0.000000,-41324693535940.000000,...,0.000000,0.000000,243281427973.000000,0.000000,1465529906.000000,0.000000,0.000000,0.000000,2023-07-14 14:14:19,2023-07-18 17:00:19.361777
157,43636573,2023-06-30,None,Q,SBS,N,3,0.000000,0.000000,-1100000000.000000,...,0.000000,0.000000,0.000000,135149549004.000000,0.000000,0.000000,0.000000,0.000000,2023-07-24 11:44:06,2023-07-24 17:00:07.542029
158,43686710,2023-06-30,None,Q,WSS,N,3,0.000000,0.000000,-135644591781.000000,...,0.000000,0.000000,0.000000,0.000000,2108523.000000,0.000000,0.000000,0.000000,2023-08-03 14:49:29,2023-08-07 00:58:16.247235

In [5]:
scf.check_scfd_1_2(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_1_2

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_1_2,SCFD_1,SCFD_2,SCFD_3,SCFD_4,SCFD_5,SCFD_6,SCFD_7,SCFD_8,SCFD_9,SCFD_10,SCFD_11,SCFD_12
0,ART,2018-03-31,Q,N,0.000000,-79583632667.000000,26991711108.000000,-2201826560.000000,54098900.000000,11430136772.000000,0.000000,-20053569259.000000,-1236333568.000000,0.000000,0.000000,265872359424.000000,-105050464256.000000
1,BMS,2018-03-31,Q,N,0.000000,-2443716970884.000000,1802700307924.000000,-200600944.000000,0.000000,293433589.000000,-1430669184.000000,0.000000,1895741824.000000,0.000000,0.000000,1276655697920.000000,-955117142016.000000
2,BVS,2018-03-31,Q,N,0.000000,-4569299206732.000000,4652273638887.000000,0.000000,675621700.000000,49563397470.000000,-118748224.000000,-11130649040.000000,-41353641984.000000,0.000000,0.000000,5154695282688.000000,-1711320465408.000000
3,DSC,2018-03-31,Q,N,0.000000,-177644030937.000000,171022151167.000000,-89257352.000000,10500.000000,552033743.000000,0.000000,-294387257.000000,-1143272192.000000,0.000000,0.000000,16755447808.000000,-1966545152.000000
4,HBS,2018-03-31,Q,N,0.000000,0.000000,0.000000,0.000000,44700.000000,328596845.000000,0.000000,-711615546.000000,-979925824.000000,0.000000,0.000000,1541988096.000000,-18056871936.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,BVS,2023-06-30,Q,N,0.000000,-27323941724365.000000,26363125187392.000000,0.000000,7733135180.000000,78349319983.000000,-21604493335.000000,-12078061459.000000,-27367674145.000000,-27794252629.000000,0.000000,1627968745521.000000,-1412423699689.000000
155,HBS,2023-06-30,Q,N,0.000000,-277855290411.000000,273629709589.000000,0.000000,47100.000000,7617126524.000000,0.000000,-60891125.000000,-1294767895.000000,-558632810.000000,0.000000,1869560995.000000,-1734226975.000000
156,MBS,2023-06-30,Q,N,0.000000,-41324693535940.000000,50549976799574.000000,0.000000,727950.000000,176920376667.000000,-9260505980.000000,-26749551941.000000,-41795386270.000000,10558708525102.000000,0.000000,10632115846222.000000,-28632797478445.000000
157,SBS,2023-06-30,Q,N,0.000000,-1100000000.000000,11902860610.000000,0.000000,0.000000,1918642727.000000,0.000000,-8284369366.000000,-5995059442.000000,-5679633498.000000,0.000000,2106779798522.000000,-2082761409752.000000
158,WSS,2023-06-30,Q,N,0.000000,-135644591781.000000,170790615181.000000,0.000000,0.000000,4141713698.000000,0.000000,0.000000,-1142284777.000000,-83289878.000000,0.000000,44109259700.000000,-78479442276.000000

In [6]:
scf.check_scfd_7(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_7

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_7,SCFD_7_1,SCFD_7_2,SCFD_7_3,SCFD_7_4,SCFD_7_5
0,ART,2018-03-31,Q,N,-20053569259.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,BVS,2018-03-31,Q,N,-11130649040.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,DSC,2018-03-31,Q,N,-294387257.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,HBS,2018-03-31,Q,N,-711615546.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,SBS,2018-03-31,Q,N,-4384028278.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
151,SBS,2023-03-31,Q,N,-7428218442.000000,0.000000,0.000000,0.000000,0.000000,0.000000
154,BVS,2023-06-30,Q,N,-12078061459.000000,0.000000,0.000000,0.000000,0.000000,0.000000
155,HBS,2023-06-30,Q,N,-60891125.000000,0.000000,0.000000,0.000000,0.000000,0.000000
156,MBS,2023-06-30,Q,N,-26749551941.000000,0.000000,0.000000,0.000000,0.000000,0.000000
157,SBS,2023-06-30,Q,N,-8284369366.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [7]:
scf.check_scfd_20(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_20

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_20,SCFD_1_1,SCFD_1_2
0,ART,2018-03-31,Q,N,75607629824.000000,0.000000,0.000000
1,BMS,2018-03-31,Q,N,-331971035136.000000,0.000000,0.000000
2,BVS,2018-03-31,Q,N,3495730085888.000000,0.000000,0.000000
3,DSC,2018-03-31,Q,N,5309878272.000000,0.000000,0.000000
4,HBS,2018-03-31,Q,N,-18113032192.000000,0.000000,0.000000
...,...,...,...,...,...,...,...
154,BVS,2023-06-30,Q,N,-748033517546.000000,0.000000,0.000000
155,HBS,2023-06-30,Q,N,1612634992.000000,0.000000,0.000000
156,MBS,2023-06-30,Q,N,1882425816939.000000,0.000000,0.000000
157,SBS,2023-06-30,Q,N,16780829801.000000,0.000000,0.000000
158,WSS,2023-06-30,Q,N,3691979867.000000,0.000000,0.000000

In [8]:
scf.check_scfd_22(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_22

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_22,SCFD_22_1,SCFD_22_2,SCFD_22_3,SCFD_22_4
12,WSS,2018-06-30,Q,Y,0.000000,0.000000,0.000000,-5750000128.000000,0.000000
13,ART,2018-09-30,Q,N,10000000.000000,0.000000,0.000000,0.000000,45499998208.000000
14,BMS,2018-09-30,Q,N,1395162496.000000,0.000000,0.000000,0.000000,0.000000
17,MBS,2018-09-30,Q,N,545455.000000,0.000000,0.000000,0.000000,0.000000
20,ART,2018-12-31,Y,Y,0.000000,0.000000,0.000000,-540000000000.000000,40000000000.000000
29,WSS,2018-12-31,Y,Y,0.000000,0.000000,0.000000,-5750000000.000000,0.000000
37,ART,2019-06-30,Q,Y,0.000000,0.000000,0.000000,0.000000,100000000000.000000
40,MBS,2019-06-30,Q,Y,7416364.000000,0.000000,0.000000,0.000000,0.000000
45,HBS,2019-09-30,Q,N,45454545.000000,0.000000,0.000000,0.000000,0.000000
49,ART,2019-12-31,Y,Y,0.000000,0.000000,0.000000,0.000000,200000000000.000000
50,ART,2019-12-31,Q,N,0.000000,0.000000,0.000000,0.000000,100000000000.000000
53,HBS,2019-12-31,Y,Y,45454545.000000,0.000000,0.000000,0.000000,0.000000
55,MBS,2019-12-31,Q,N,1818182.000000,0.000000,0.000000,0.000000,0.000000
65,ART,2020-06-30,Q,Y,0.000000,0.000000,0.000000,0.000000,30000000000.000000
66,BMS,2020-06-30,Q,N,0.000000,0.000000,0.000000,-150000000000.000000,100000000000.000000
77,ART,2020-12-31,Y,Y,0.000000,0.000000,0.000000,0.000000,30000000000.000000
84,MBS,2020-12-31,Q,N,1636364.000000,0.000000,0.000000,0.000000,0.000000
86,VDS,2020-12-31,Y,N,NaN,NaN,NaN,NaN,NaN
87,VUA,2020-12-31,Y,N,NaN,NaN,NaN,NaN,NaN
89,ART,2021-03-31,Q,N,0.000000,0.000000,0.000000,-501240000000.000000,0.000000
94,VUA,2021-03-31,Q,N,NaN,NaN,NaN,NaN,NaN
96,ART,2021-06-30,Q,Y,0.000000,0.000000,0.000000,0.000000,329300000000.000000
103,ART,2021-09-30,Q,N,0.000000,0.000000,0.000000,-189100000000.000000,521200000000.000000
108,ART,2021-12-31,Y,Y,0.000000,0.000000,0.000000,-725340000000.000000,521200000000.000000
109,ART,2021-12-31,Q,N,0.000000,0.000000,0.000000,-35000000000.000000,0.000000
114,HBS,2021-12-31,Y,Y,0.000000,0.000000,0.000000,0.000000,50000000000.000000
115,HBS,2021-12-31,Q,N,0.000000,0.000000,50000000000.000000,0.000000,0.000000
136,BMS,2022-12-31,Q,N,-66889327.000000,0.000000,0.000000,0.000000,0.000000
140,HBS,2022-12-31,Y,Y,0.000000,-2480000000.000000,0.000000,0.000000,0.000000

In [9]:
scf.check_scfd_30(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_30

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_30,SCFD_21,SCFD_22,SCFD_25
12,WSS,2018-06-30,Q,Y,-5782139904.000000,-32140000.000000,0.000000,0.000000
13,ART,2018-09-30,Q,N,28197353472.000000,-34959982592.000000,10000000.000000,17647335424.000000
14,BMS,2018-09-30,Q,N,1409998464.000000,0.000000,1395162496.000000,14836054.000000
17,MBS,2018-09-30,Q,N,-123567544.000000,-124113000.000000,545455.000000,0.000000
20,ART,2018-12-31,Y,Y,-509291660000.000000,-9581660000.000000,0.000000,290000000.000000
29,WSS,2018-12-31,Y,Y,-5750000000.000000,0.000000,0.000000,0.000000
37,ART,2019-06-30,Q,Y,95561284820.000000,-4438715180.000000,0.000000,0.000000
49,ART,2019-12-31,Y,Y,189183584820.000000,-10816415180.000000,0.000000,0.000000
50,ART,2019-12-31,Q,N,99985000000.000000,-15000000.000000,0.000000,0.000000
65,ART,2020-06-30,Q,Y,29978000000.000000,-22000000.000000,0.000000,0.000000
66,BMS,2020-06-30,Q,N,-50015231962.000000,-45500000.000000,0.000000,30268038.000000
77,ART,2020-12-31,Y,Y,24983637000.000000,-5016363000.000000,0.000000,0.000000
86,VDS,2020-12-31,Y,N,-18807872308.000000,0.000000,NaN,NaN
87,VUA,2020-12-31,Y,N,-27827996398.000000,0.000000,NaN,NaN
89,ART,2021-03-31,Q,N,-171940000000.000000,0.000000,0.000000,329300000000.000000
94,VUA,2021-03-31,Q,N,-16170925398.000000,0.000000,NaN,NaN
96,ART,2021-06-30,Q,Y,0.000000,0.000000,0.000000,-329300000000.000000
103,ART,2021-09-30,Q,N,2800000000.000000,0.000000,0.000000,-329300000000.000000
108,ART,2021-12-31,Y,Y,-204640000000.000000,-500000000.000000,0.000000,0.000000
109,ART,2021-12-31,Q,N,-35500000000.000000,-500000000.000000,0.000000,0.000000
114,HBS,2021-12-31,Y,Y,51545000000.000000,-355000000.000000,0.000000,1900000000.000000
115,HBS,2021-12-31,Q,N,50295000000.000000,-355000000.000000,0.000000,650000000.000000
140,HBS,2022-12-31,Y,Y,-7610761600.000000,-5130761600.000000,0.000000,0.000000

In [10]:
scf.check_scfd_33(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_33

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_33,SCFD_33_1,SCFD_33_2
1,BMS,2018-03-31,Q,N,529664573440.000000,0.000000,529664573833.000000
2,BVS,2018-03-31,Q,N,21516820480.000000,0.000000,21516820883.000000
8,BMS,2018-06-30,Q,Y,173599997952.000000,0.000000,173600000000.000000
9,BVS,2018-06-30,Q,Y,450003140608.000000,0.000000,450003150685.000000
12,WSS,2018-06-30,Q,Y,179999997952.000000,0.000000,180000000000.000000
14,BMS,2018-09-30,Q,N,109999996928.000000,0.000000,110000000000.000000
15,BVS,2018-09-30,Q,N,326755483648.000000,0.000000,326755500000.000000
17,MBS,2018-09-30,Q,N,5791015763968.000000,0.000000,5791015855556.000000
86,VDS,2020-12-31,Y,N,179323563263.000000,NaN,NaN
87,VUA,2020-12-31,Y,N,-63764738640.000000,NaN,NaN
94,VUA,2021-03-31,Q,N,27757320115.000000,NaN,NaN

In [11]:
scf.check_scfd_34(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_34

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_34,SCFD_34_1,SCFD_34_2,SCFD_34_3
1,BMS,2018-03-31,Q,N,-253714677760.000000,0.000000,0.000000,-253714673833.000000
2,BVS,2018-03-31,Q,N,-90090094592.000000,0.000000,0.000000,-90090096372.000000
6,WSS,2018-03-31,Q,N,-161116995584.000000,0.000000,0.000000,-161117000000.000000
8,BMS,2018-06-30,Q,Y,-204650102784.000000,0.000000,0.000000,-204650100000.000000
9,BVS,2018-06-30,Q,Y,-177277698048.000000,0.000000,0.000000,-177277698150.000000
12,WSS,2018-06-30,Q,Y,-140593004544.000000,0.000000,0.000000,-140593000000.000000
14,BMS,2018-09-30,Q,N,-255050104832.000000,0.000000,0.000000,-255050100000.000000
15,BVS,2018-09-30,Q,N,-387618734080.000000,0.000000,0.000000,-387618726823.000000
17,MBS,2018-09-30,Q,N,-8675134013440.000000,0.000000,0.000000,-8675134171222.000000
86,VDS,2020-12-31,Y,N,0.000000,NaN,NaN,NaN
87,VUA,2020-12-31,Y,N,0.000000,NaN,NaN,NaN
94,VUA,2021-03-31,Q,N,-38378760774.000000,NaN,NaN,NaN

In [12]:
scf.check_scfd_40(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_40

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_40,SCFD_31,SCFD_32,SCFD_33,SCFD_34,SCFD_35,SCFD_36
1,BMS,2018-03-31,Q,N,275859275776.000000,0.000000,0.000000,529664573440.000000,-253714677760.000000,0.000000,-90637600.000000
6,WSS,2018-03-31,Q,N,-33116999680.000000,0.000000,0.000000,128000000000.000000,-161116995584.000000,0.000000,0.000000
8,BMS,2018-06-30,Q,Y,168929230848.000000,199999995904.000000,0.000000,173599997952.000000,-204650102784.000000,0.000000,-20667400.000000
9,BVS,2018-06-30,Q,Y,272725458944.000000,0.000000,0.000000,450003140608.000000,-177277698048.000000,0.000000,0.000000
12,WSS,2018-06-30,Q,Y,39407001600.000000,0.000000,0.000000,179999997952.000000,-140593004544.000000,0.000000,0.000000
14,BMS,2018-09-30,Q,N,-145113038848.000000,0.000000,0.000000,109999996928.000000,-255050104832.000000,0.000000,-62936552.000000
15,BVS,2018-09-30,Q,N,-111083143168.000000,0.000000,0.000000,326755483648.000000,-387618734080.000000,0.000000,-50219913216.000000
17,MBS,2018-09-30,Q,N,-2884120084480.000000,0.000000,-1706600.000000,5791015763968.000000,-8675134013440.000000,0.000000,0.000000
86,VDS,2020-12-31,Y,N,-245477582.000000,-71408566580.000000,0.000000,179323563263.000000,0.000000,-6141978000.000000,3707319372.000000
87,VUA,2020-12-31,Y,N,1218537153.000000,10463698944.000000,0.000000,-63764738640.000000,0.000000,0.000000,180432808.000000
90,BMS,2021-03-31,Q,N,-180642269255.000000,0.000000,0.000000,0.000000,-180000000000.000000,0.000000,0.000000
94,VUA,2021-03-31,Q,N,1935588194.000000,0.000000,0.000000,27757320115.000000,-38378760774.000000,0.000000,-35572681.000000

In [13]:
scf.check_scfd_50(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_50

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_50,SCFD_20,SCFD_30,SCFD_40
1,BMS,2018-03-31,Q,N,-56057434112.000000,-331971035136.000000,54335420.000000,275859275776.000000
2,BVS,2018-03-31,Q,N,3426466398208.000000,3495730085888.000000,-690419968.000000,-68573274112.000000
3,DSC,2018-03-31,Q,N,5007276032.000000,5309878272.000000,-325601888.000000,23000000.000000
4,HBS,2018-03-31,Q,N,-17576411136.000000,-18113032192.000000,536620000.000000,0.000000
6,WSS,2018-03-31,Q,N,-87559831552.000000,-54442835968.000000,0.000000,-33116999680.000000
7,ART,2018-06-30,Q,Y,132694818816.000000,133666816000.000000,-972000000.000000,0.000000
8,BMS,2018-06-30,Q,Y,180988936192.000000,12114033664.000000,-54335420.000000,168929230848.000000
9,BVS,2018-06-30,Q,Y,-1889831092224.000000,-2162491129856.000000,-65450000.000000,272725458944.000000
11,SBS,2018-06-30,Q,Y,15970202624.000000,15882780672.000000,87421880.000000,0.000000
12,WSS,2018-06-30,Q,Y,61509537792.000000,27884677120.000000,-5782139904.000000,39407001600.000000
13,ART,2018-09-30,Q,N,583862648832.000000,555665260544.000000,28197353472.000000,0.000000
14,BMS,2018-09-30,Q,N,-5187147264.000000,138515890176.000000,1409998464.000000,-145113038848.000000
15,BVS,2018-09-30,Q,N,-532758003712.000000,-421605244928.000000,-69600000.000000,-111083143168.000000
16,HBS,2018-09-30,Q,N,-32618903552.000000,-26963503104.000000,-5655400960.000000,0.000000
17,MBS,2018-09-30,Q,N,-163711418368.000000,2720532267008.000000,-123567544.000000,-2884120084480.000000
86,VDS,2020-12-31,Y,N,3153556325.000000,0.000000,-18807872308.000000,-245477582.000000
87,VUA,2020-12-31,Y,N,180187722.000000,0.000000,-27827996398.000000,1218537153.000000
94,VUA,2021-03-31,Q,N,17914336.000000,0.000000,-16170925398.000000,1935588194.000000

In [14]:
scf.check_scfd_70(df=dfd)

CHECK ITEM & SUB-ITEMS SCFD_70

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFD_70,SCFD_50,SCFD_60,SCFD_63
0,ART,2018-03-31,Q,N,81015406592.000000,75607629824.000000,5407777280.000000,0.000000
1,BMS,2018-03-31,Q,N,5292007936.000000,-56057434112.000000,61349441536.000000,0.000000
2,BVS,2018-03-31,Q,N,3654849921024.000000,3426466398208.000000,228383440896.000000,0.000000
3,DSC,2018-03-31,Q,N,48968978432.000000,5007276032.000000,43961700352.000000,0.000000
5,SBS,2018-03-31,Q,N,9030642688.000000,-33932744704.000000,42963390464.000000,0.000000
6,WSS,2018-03-31,Q,N,73357402112.000000,-87559831552.000000,160917241856.000000,1608720640.000000
8,BMS,2018-06-30,Q,Y,186280935424.000000,180988936192.000000,5292007936.000000,0.000000
10,HBS,2018-06-30,Q,Y,170895917056.000000,-5915895808.000000,176811802624.000000,0.000000
12,WSS,2018-06-30,Q,Y,134866935808.000000,61509537792.000000,73357402112.000000,0.000000
13,ART,2018-09-30,Q,N,797572857856.000000,583862648832.000000,213710225408.000000,0.000000
14,BMS,2018-09-30,Q,N,1093792128.000000,-5187147264.000000,6280939520.000000,0.000000
15,BVS,2018-09-30,Q,N,1014138470400.000000,-532758003712.000000,1546896539648.000000,0.000000
16,HBS,2018-09-30,Q,N,138277011456.000000,-32618903552.000000,170895917056.000000,0.000000
17,MBS,2018-09-30,Q,N,116077600768.000000,-163711418368.000000,279789010944.000000,0.000000
29,WSS,2018-12-31,Y,Y,68578530101.000000,-90730297885.000000,159308827986.000000,623388.000000
57,WSS,2019-12-31,Y,Y,75938154138.000000,7359624037.000000,68578530101.000000,553431.000000
86,VDS,2020-12-31,Y,N,5165741876.000000,3153556325.000000,79826352837.000000,0.000000
87,VUA,2020-12-31,Y,N,-14001962731.000000,180187722.000000,-7717031150.000000,0.000000
94,VUA,2021-03-31,Q,N,1472325950.000000,17914336.000000,-8900436691.000000,0.000000
96,ART,2021-06-30,Q,Y,2013359951.000000,-1490666346.000000,3504026297.000000,3504026297.000000
102,WSS,2021-06-30,Q,Y,9816545976.000000,1741008746.000000,8075537230.000000,-273667.000000
120,WSS,2021-12-31,Y,Y,19822138868.000000,-3945788292.000000,23767927160.000000,28514.000000

Check SECURITY_CF_INDIRECT

In [15]:
dfi = pd.read_sql_query(
    """ SELECT 
    * 
    FROM SECURITY_CF_INDIRECT
    WHERE LENGTH(SECURITY_CODE) = 3
    ORDER BY REPORT_DATE ASC, SECURITY_CODE ASC
    """, con=conn
)

C:\Users\tungtt1\AppData\Local\Temp\45\ipykernel_108940\4085741866.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dfi = pd.read_sql_query(

In [16]:
len(dfi)

1587

In [17]:
scf.check_scfi_2(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_2

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_2,SCFI_3,SCFI_4,SCFI_5,SCFI_7,SCFI_6,SCFI_9
63,CASC,2021-09-30,Q,N,16046154836.000000,256570071.000000,0.000000,0.000000,0.000000,0.000000,0.000000
141,CASC,2021-12-31,Q,N,-12025789849.000000,259916846.000000,3503878070.000000,0.000000,0.000000,0.000000,0.000000
195,EVS,2021-09-30,Q,N,19856392699.000000,520183765.000000,386883600.000000,NaN,-483711316.000000,19433036650.000000,NaN
202,NVSC,2021-03-31,Q,N,173256232.000000,196107388.000000,NaN,-65068.000000,-22786088.000000,NaN,NaN
270,NHSV,2020-03-31,Q,N,-54152548651.000000,1985002857.000000,0.000000,-22090815.000000,-74930829235.000000,18409895926.000000,0.000000
275,ASIAS,2020-03-31,Q,N,37168334.000000,43648014.000000,0.000000,0.000000,0.000000,0.000000,0.000000
285,ASIAS,2020-06-30,Q,Y,50127694.000000,43648014.000000,0.000000,0.000000,0.000000,0.000000,0.000000
289,MBS,2020-06-30,Q,Y,21778938746.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
291,MASC,2020-06-30,Q,Y,133690828441.000000,1022760215.000000,0.000000,4572842153.000000,-37224860553.000000,121618072699.000000,0.000000
295,MASC,2020-03-31,Q,N,-41346481513.000000,949150320.000000,0.000000,-7227842153.000000,8634224247.000000,0.000000,0.000000
372,NHSV,2020-06-30,Q,Y,25604310252.000000,1985002857.000000,405472616.000000,24424922.000000,5051046020.000000,9394092415.000000,9149744038.000000
414,CASC,2021-03-31,Q,N,225070071.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
865,CASC,2021-06-30,Q,Y,2412050581.000000,477181809.000000,2159938843.000000,0.000000,0.000000,0.000000,0.000000
872,DDSC,2020-09-30,Q,N,4884943239139.000000,0.000000,891100.000000,46684860025.000000,-6173508865.000000,0.000000,-11939031393.000000
875,DDSC,2021-09-30,Q,N,22498569170068.000000,-10542583114.000000,350320.000000,6012496135.000000,-22772564930.000000,-696203623.000000,-3557224256.000000
876,DDSC,2021-06-30,Q,N,13787302072504.000000,-10542583114.000000,239070.000000,8224085664.000000,-15108057229.000000,-696203623.000000,-2844264845.000000
877,DDSC,2021-03-31,Q,N,5543003743202.000000,-10542583114.000000,117250.000000,8172378441.000000,-7623336313.000000,-244463013.000000,-1951489113.000000
981,ASIAS,2019-12-31,Q,N,551210895.000000,43648014.000000,512123834.000000,0.000000,0.000000,0.000000,0.000000
998,VDS,2019-09-30,Q,N,5037516452.000000,1428413984.000000,6000016445.000000,0.000000,-2390905007.000000,0.000000,0.000000
1074,VDS,2019-06-30,Q,Y,-38700720.000000,1807301397.000000,0.000000,105000000.000000,-6487673396.000000,4536662309.000000,0.000000
1090,KISVN,2019-09-30,Q,N,84397650285.000000,2213637959.000000,0.000000,0.000000,94723286585.000000,-12337017590.000000,0.000000
1118,KISVN,2019-12-31,Q,N,45428640493.000000,2422767134.000000,12726599890.000000,-4400141369.000000,-7605208715.000000,42082366884.000000,0.000000
1149,MASC,2019-03-31,Q,N,-20874970190.000000,275238749.000000,0.000000,600000000.000000,-20194602262.000000,0.000000,876795733.000000
1182,MASC,2019-06-30,Q,Y,-24279609084.000000,1467683786.000000,0.000000,-232400000.000000,6267996073.000000,66661504380.000000,-100876795733.000000
1240,ASIAS,2019-06-30,Q,N,562631429.000000,45540912.000000,512123834.000000,0.000000,0.000000,2018560.000000,0.000000
1251,ASIAS,2019-09-30,Q,N,50507586.000000,45540908.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1291,NHSV,2018-09-30,Q,N,877488521.000000,388404232.000000,24562100.000000,-9764071.000000,-15087488205.000000,0.000000,15144932976.000000
1295,ASIAS,2018-12-31,Q,N,323428384.000000,27690924.000000,300000000.000000,0.000000,0.000000,0.000000,0.000000
1343,MASC,2018-03-31,Q,N,-62375209259.000000,497907141.000000,0.000000,0.000000,0.000000,0.000000,-57804762144.000000
1447,MASC,2018-06-30,Q,N,80516597386.000000,562824656.000000,0.000000,0.000000,17080656330.000000,0.000000,57804762144.000000
1479,NHSV,2018-06-30,Q,N,1134894505.000000,1117209788.000000,15433600.000000,-6956515.000000,419092606.000000,0.000000,6956515.000000
1512,VND,2018-12-31,Y,Y,479816514046.000000,21958681733.000000,169741593659.000000,-826465877.000000,0.000000,286523253543.000000,0.000000
1536,ASIAS,2018-09-30,Q,N,99310596.000000,33315924.000000,32000000.000000,0.000000,0.000000,0.000000,0.000000
1552,ASIAS,2018-06-30,Q,Y,377168941.000000,33315924.000000,348890521.000000,0.000000,0.000000,0.000000,0.000000
1575,ASIAS,2018-03-31,Q,N,38353428.000000,33315924.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [18]:
scf.check_scfi_10(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_10

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_10,SCFI_11,SCFI_12,SCFI_13,SCFI_14,SCFI_15,SCFI_16,SCFI_17
8,VND,2022-12-31,Q,N,393643757521.000000,391562957449.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
80,VND,2022-12-31,Y,Y,1451565245595.000000,1449484445523.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
161,AGR,2020-09-30,Q,N,-7569689409.000000,-5222958241.000000,0.000000,-1080340662.000000,0.000000,0.000000,0.000000,0.000000
195,EVS,2021-09-30,Q,N,175987092490.000000,175987092490.000000,NaN,NaN,NaN,NaN,0.000000,NaN
202,NVSC,2021-03-31,Q,N,20458341977.000000,20458341977.000000,NaN,NaN,NaN,NaN,0.000000,NaN
220,AGR,2020-12-31,Q,N,-1506996270.000000,-1652163390.000000,0.000000,-1121223386.000000,0.000000,0.000000,0.000000,0.000000
872,DDSC,2020-09-30,Q,N,-550829400.000000,224332250.000000,-6898686099.000000,NaN,NaN,NaN,0.000000,NaN
875,DDSC,2021-09-30,Q,N,0.000000,160725330.000000,-20070826594.000000,NaN,NaN,NaN,0.000000,NaN
876,DDSC,2021-06-30,Q,N,0.000000,237551893.000000,-10834767695.000000,NaN,NaN,NaN,0.000000,NaN
877,DDSC,2021-03-31,Q,N,0.000000,6041260.000000,-2767245846.000000,NaN,NaN,NaN,0.000000,NaN
1291,NHSV,2018-09-30,Q,N,-229462070.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1479,NHSV,2018-06-30,Q,N,229462070.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [19]:
scf.check_scfi_11(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_11

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_11,SCFI_11_1,SCFI_11_2,SCFI_11_3,SCFI_11_4
2,PGSC,2022-03-31,Q,N,1959480532.000000,0.000000,0.000000,0.000000,0.000000
3,NHSV,2021-12-31,Y,Y,214652635.000000,0.000000,0.000000,0.000000,0.000000
4,AAS,2022-06-30,Q,Y,-870380000.000000,0.000000,0.000000,0.000000,0.000000
6,APS,2022-09-30,Q,N,164539595510.000000,0.000000,0.000000,0.000000,0.000000
8,VND,2022-12-31,Q,N,391562957449.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
1581,APS,2018-06-30,Q,N,8521100860.000000,0.000000,0.000000,0.000000,0.000000
1583,VDS,2023-06-30,Q,N,-92256060331.000000,0.000000,0.000000,0.000000,0.000000
1584,HCM,2023-06-30,Q,N,-401283627.000000,0.000000,0.000000,0.000000,0.000000
1585,AAS,2023-06-30,Q,N,-785423063.000000,0.000000,0.000000,0.000000,0.000000
1586,TCI,2023-06-30,Q,N,1738741033.000000,0.000000,0.000000,0.000000,0.000000

In [20]:
scf.check_scfi_14(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_14

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_14,SCFI_14_1,SCFI_14_2
195,EVS,2021-09-30,Q,N,NaN,0.000000,0.000000
202,NVSC,2021-03-31,Q,N,NaN,0.000000,0.000000
258,SSI,2020-09-30,Q,N,279804.000000,0.000000,0.000000
337,SSI,2020-12-31,Y,Y,13351221324.000000,0.000000,0.000000
338,SSI,2020-12-31,Q,N,13350941520.000000,0.000000,0.000000
422,SSI,2021-03-31,Q,N,929243500.000000,0.000000,0.000000
643,SSI,2021-12-31,Y,Y,929243500.000000,0.000000,0.000000
872,DDSC,2020-09-30,Q,N,NaN,0.000000,0.000000
875,DDSC,2021-09-30,Q,N,NaN,0.000000,0.000000
876,DDSC,2021-06-30,Q,N,NaN,0.000000,0.000000
877,DDSC,2021-03-31,Q,N,NaN,0.000000,0.000000
976,SSI,2019-12-31,Y,Y,93932433.000000,0.000000,0.000000
1140,SSI,2019-03-31,Q,N,93850886.000000,0.000000,0.000000
1179,SSI,2019-12-31,Q,N,81547.000000,0.000000,0.000000
1270,BSI,2023-06-30,Q,N,53060057844.000000,0.000000,0.000000
1291,NHSV,2018-09-30,Q,N,0.000000,0.000000,-229462070.000000
1294,SSI,2018-09-30,Q,N,974543588.000000,0.000000,0.000000
1399,SSI,2018-12-31,Y,Y,974544960.000000,0.000000,0.000000
1479,NHSV,2018-06-30,Q,N,0.000000,0.000000,229462070.000000
1518,SSI,2018-12-31,Q,N,1372.000000,0.000000,0.000000

In [21]:
scf.check_scfi_18(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_18

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_18,SCFI_19,SCFI_20,SCFI_21,SCFI_31,SCFI_32,SCFI_33,SCFI_34,SCFI_40
0,VTSC,2022-03-31,Q,N,0.000000,0.000000,0.000000,0.000000,-83704463292.000000,0.000000,2864565168.000000,0.000000,-716142671.000000
1,SSV,2022-03-31,Q,N,0.000000,0.000000,0.000000,0.000000,-77042584650.000000,-472500000000.000000,-736866509420.000000,0.000000,-1189834169.000000
2,PGSC,2022-03-31,Q,N,0.000000,0.000000,0.000000,0.000000,-135422810406.000000,200000000000.000000,-76893971967.000000,0.000000,-1695149871.000000
3,NHSV,2021-12-31,Y,Y,-312217837.000000,-312217837.000000,0.000000,0.000000,618911982.000000,348900000000.000000,-670169306471.000000,0.000000,-333458599.000000
4,AAS,2022-06-30,Q,Y,0.000000,0.000000,0.000000,0.000000,-164147336429.000000,0.000000,20408214376.000000,0.000000,-6089074799.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1581,APS,2018-06-30,Q,N,9787522495.000000,9787522495.000000,0.000000,0.000000,-37458800431.000000,0.000000,16480457685.000000,0.000000,-777332470.000000
1583,VDS,2023-06-30,Q,N,-22352813503.000000,-22352813503.000000,0.000000,0.000000,8503038757.000000,0.000000,-230548706407.000000,0.000000,12906452314.000000
1584,HCM,2023-06-30,Q,N,-30591622838.000000,-30591622838.000000,0.000000,0.000000,-252839507389.000000,0.000000,-1968415876386.000000,0.000000,0.000000
1585,AAS,2023-06-30,Q,N,-15108597611.000000,0.000000,-15108597611.000000,0.000000,-148394993496.000000,64802950712.000000,-8079431738.000000,123999810000.000000,101205548493.000000
1586,TCI,2023-06-30,Q,N,-5696995656.000000,-5696995656.000000,0.000000,0.000000,1707264656.000000,-63638942467.000000,-323049914744.000000,76025223733.000000,592928080.000000

In [22]:
scf.check_scfi_19(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_19

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_19,SCFI_19_1,SCFI_19_2,SCFI_19_3
3,NHSV,2021-12-31,Y,Y,-312217837.000000,0.000000,0.000000,0.000000
6,APS,2022-09-30,Q,N,-172893692276.000000,0.000000,0.000000,0.000000
8,VND,2022-12-31,Q,N,-334248716971.000000,0.000000,0.000000,0.000000
11,NSIC,2022-12-31,Y,Y,-108984414959.000000,0.000000,0.000000,0.000000
12,NSIC,2022-12-31,Q,N,156117648097.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
1580,HCM,2018-12-31,Q,N,5198526141.000000,0.000000,0.000000,0.000000
1581,APS,2018-06-30,Q,N,9787522495.000000,0.000000,0.000000,0.000000
1583,VDS,2023-06-30,Q,N,-22352813503.000000,0.000000,0.000000,0.000000
1584,HCM,2023-06-30,Q,N,-30591622838.000000,0.000000,0.000000,0.000000
1586,TCI,2023-06-30,Q,N,-5696995656.000000,0.000000,0.000000,0.000000

In [23]:
scf.check_scfi_20(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_20

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_20,SCFI_20_1,SCFI_20_2,SCFI_20_3,SCFI_20_4,SCFI_20_5
103,SHS,2020-12-31,Q,N,-234086061051.000000,0.000000,0.000000,0.000000,0.000000,0.000000
122,ART,2020-03-31,Q,N,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
127,NSIC,2021-03-31,Q,N,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
137,WSS,2021-03-31,Q,N,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
138,WSS,2020-12-31,Y,N,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
139,WSS,2020-03-31,Q,N,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
195,EVS,2021-09-30,Q,N,NaN,0.000000,0.000000,NaN,0.000000,0.000000
198,SHS,2021-09-30,Q,N,133682079060.000000,0.000000,0.000000,0.000000,0.000000,0.000000
202,NVSC,2021-03-31,Q,N,NaN,0.000000,0.000000,NaN,0.000000,0.000000
227,SSI,2020-03-31,Q,N,-159274198599.000000,0.000000,0.000000,0.000000,0.000000,0.000000
258,SSI,2020-09-30,Q,N,-68439325383.000000,0.000000,0.000000,0.000000,0.000000,0.000000
264,TVB,2020-03-31,Q,N,1276931509.000000,0.000000,0.000000,0.000000,0.000000,0.000000
337,SSI,2020-12-31,Y,Y,-227713523982.000000,0.000000,0.000000,0.000000,0.000000,0.000000
378,TVB,2020-06-30,Q,Y,-1276931509.000000,0.000000,0.000000,0.000000,0.000000,0.000000
454,SHS,2020-12-31,Y,Y,-234086061051.000000,0.000000,0.000000,0.000000,0.000000,0.000000
462,SHS,2021-06-30,Q,Y,-133682079060.000000,0.000000,0.000000,0.000000,0.000000,0.000000
590,VUA,2022-12-31,Q,N,-28448760545.000000,0.000000,0.000000,0.000000,0.000000,0.000000
640,IVS,2022-06-30,Q,Y,-152117442313.000000,0.000000,0.000000,0.000000,0.000000,0.000000
717,IVS,2022-09-30,Q,N,152117442313.000000,0.000000,0.000000,0.000000,0.000000,0.000000
799,NSIC,2022-06-30,Q,Y,-38052891150.000000,0.000000,0.000000,0.000000,0.000000,0.000000
800,NSIC,2022-09-30,Q,N,38052891150.000000,0.000000,0.000000,0.000000,0.000000,0.000000
872,DDSC,2020-09-30,Q,N,-20491008445.000000,0.000000,0.000000,NaN,0.000000,0.000000
875,DDSC,2021-09-30,Q,N,-671840574017.000000,0.000000,0.000000,NaN,0.000000,0.000000
876,DDSC,2021-06-30,Q,N,4284249040.000000,0.000000,0.000000,NaN,0.000000,0.000000
877,DDSC,2021-03-31,Q,N,-10447964908.000000,0.000000,0.000000,NaN,0.000000,0.000000
878,DDSC,2020-12-31,Q,N,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
976,SSI,2019-12-31,Y,Y,-64935654053.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1027,SSI,2019-06-30,Q,Y,-16778830583.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1036,TVB,2019-12-31,Y,Y,1221123290.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1059,TVB,2019-09-30,Q,N,-272739727.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1084,TVB,2019-03-31,Q,N,521643836.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1113,SSI,2019-09-30,Q,N,-13179319507.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1179,SSI,2019-12-31,Q,N,-34977503963.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1190,TVB,2019-06-30,Q,Y,349041098.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1221,TVB,2019-12-31,Q,N,623178083.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1270,BSI,2023-06-30,Q,N,-126968876456.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1290,TVB,2018-12-31,Y,Y,322328767.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1294,SSI,2018-09-30,Q,N,-16838106236.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1326,TVB,2018-06-30,Q,Y,-606900003.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1332,TVB,2018-09-30,Q,N,-1206861112.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1345,SSI,2018-06-30,Q,Y,-11190160354.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1364,SSI,2018-03-31,Q,N,-26635462186.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1398,PHS,2018-03-31,Q,N,0.000000,0.000000,0.000000,0.000000,-3590909.000000,0.000000
1399,SSI,2018-12-31,Y,Y,-179612863981.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1417,IVS,2023-06-30,Q,N,-183154.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1457,PHS,2018-06-30,Q,N,0.000000,0.000000,0.000000,0.000000,3590909.000000,0.000000
1476,TVB,2018-03-31,Q,N,1023777779.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1506,TVB,2018-12-31,Q,N,1112312103.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1518,SSI,2018-12-31,Q,N,-124949135205.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1585,AAS,2023-06-30,Q,N,-15108597611.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [24]:
scf.check_scfi_30(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_30

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_30,SCFI_35,SCFI_36,SCFI_37,SCFI_38,SCFI_39,...,SCFI_46,SCFI_47,SCFI_48,SCFI_49,SCFI_50,SCFI_42,SCFI_51,SCFI_52,SCFI_44,SCFI_43
0,VTSC,2022-03-31,Q,N,-69759094763.000000,0.000000,158824868.000000,0.000000,0.000000,-6333611.000000,...,0.000000,143589171.000000,-231783767.000000,0.000000,13573187670.000000,-386408696.000000,0.000000,120635525.000000,0.000000,0.000000
1,SSV,2022-03-31,Q,N,-1274566352293.000000,0.000000,28853791582.000000,46630080.000000,0.000000,-64002728.000000,...,0.000000,-152626442.000000,1305893538.000000,0.000000,189659672.000000,-1064415930.000000,0.000000,-2833249444.000000,0.000000,0.000000
2,PGSC,2022-03-31,Q,N,205006508805.000000,45456284033.000000,-360608361231.000000,-11927512512.000000,0.000000,-175734808.000000,...,0.000000,12832014997.000000,3940464324.000000,0.000000,633001046083.000000,392737960.000000,-1063041000.000000,6517619817.000000,0.000000,0.000000
3,NHSV,2021-12-31,Y,Y,-359051463252.000000,0.000000,15317146687.000000,268494.000000,0.000000,-1758823008.000000,...,0.000000,8517926260.000000,1614806002.000000,0.000000,2448729738.000000,-240009174.000000,0.000000,-46981898.000000,0.000000,0.000000
4,AAS,2022-06-30,Q,Y,-478832054615.000000,0.000000,79282156863.000000,272850592.000000,0.000000,1169504624.000000,...,0.000000,-6847743793.000000,128600255.000000,0.000000,-52781784814.000000,-32885496385.000000,0.000000,-2705985131.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1581,APS,2018-06-30,Q,N,-10413276577.000000,4700000000.000000,19107834.000000,68900000.000000,0.000000,-950233446.000000,...,164286339.000000,4251307549.000000,-100138362.000000,0.000000,-71666079.000000,63435313.000000,0.000000,75493790.000000,0.000000,0.000000
1583,VDS,2023-06-30,Q,N,-133545962674.000000,0.000000,0.000000,6201129519.000000,0.000000,8350745541.000000,...,0.000000,-9810064259.000000,-740780218.000000,0.000000,1171973719.000000,300271659.000000,0.000000,23493427357.000000,0.000000,0.000000
1584,HCM,2023-06-30,Q,N,-2371163133998.000000,0.000000,0.000000,194841248242.000000,0.000000,-637310292.000000,...,41350919.000000,5316995571.000000,0.000000,0.000000,-227381602321.000000,-3244968209.000000,3799468000.000000,26106259871.000000,0.000000,0.000000
1585,AAS,2023-06-30,Q,N,436284433472.000000,0.000000,-10341024111.000000,257123469.000000,0.000000,-2278471717.000000,...,-16121500.000000,430630250.000000,-253786977.000000,0.000000,15982816260.000000,97684001660.000000,0.000000,104308508874.000000,0.000000,0.000000
1586,TCI,2023-06-30,Q,N,-494590612221.000000,0.000000,-1392990589.000000,-31112460.000000,0.000000,-76301370.000000,...,0.000000,396511263.000000,-260916522.000000,0.000000,276782111.000000,918169640.000000,161013549.000000,325249699.000000,0.000000,0.000000

In [25]:
scf.check_scfi_40(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_40

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_40,SCFI_40_1,SCFI_40_2,SCFI_40_3,SCFI_40_4,SCFI_40_5,SCFI_40_6
0,VTSC,2022-03-31,Q,N,-716142671.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,SSV,2022-03-31,Q,N,-1189834169.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,PGSC,2022-03-31,Q,N,-1695149871.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,NHSV,2021-12-31,Y,Y,-333458599.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,AAS,2022-06-30,Q,Y,-6089074799.000000,2009300000.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
1579,ORS,2018-03-31,Q,N,-196061922.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1581,APS,2018-06-30,Q,N,-777332470.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1583,VDS,2023-06-30,Q,N,12906452314.000000,-4845266000.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1585,AAS,2023-06-30,Q,N,101205548493.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1586,TCI,2023-06-30,Q,N,592928080.000000,-160987397600.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [26]:
scf.check_scfi_42(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_42

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_42,SCFI_42_1,SCFI_42_2
0,VTSC,2022-03-31,Q,N,-386408696.000000,0.000000,0.000000
1,SSV,2022-03-31,Q,N,-1064415930.000000,0.000000,0.000000
2,PGSC,2022-03-31,Q,N,392737960.000000,0.000000,0.000000
3,NHSV,2021-12-31,Y,Y,-240009174.000000,0.000000,0.000000
4,AAS,2022-06-30,Q,Y,-32885496385.000000,0.000000,0.000000
...,...,...,...,...,...,...,...
1582,VTSS,2018-06-30,Q,N,99500001.000000,0.000000,0.000000
1583,VDS,2023-06-30,Q,N,300271659.000000,0.000000,0.000000
1584,HCM,2023-06-30,Q,N,-3244968209.000000,0.000000,0.000000
1585,AAS,2023-06-30,Q,N,97684001660.000000,0.000000,0.000000
1586,TCI,2023-06-30,Q,N,918169640.000000,0.000000,0.000000

In [27]:
scf.check_scfi_50(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_50

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_50,SCFI_50_1,SCFI_50_2
0,VTSC,2022-03-31,Q,N,13573187670.000000,-1574765128.000000,0.000000
1,SSV,2022-03-31,Q,N,189659672.000000,-2529667886.000000,0.000000
2,PGSC,2022-03-31,Q,N,633001046083.000000,-22847928976.000000,0.000000
3,NHSV,2021-12-31,Y,Y,2448729738.000000,-10251687581.000000,0.000000
4,AAS,2022-06-30,Q,Y,-52781784814.000000,-92990786306.000000,0.000000
...,...,...,...,...,...,...,...
1582,VTSS,2018-06-30,Q,N,784460.000000,0.000000,0.000000
1583,VDS,2023-06-30,Q,N,1171973719.000000,0.000000,0.000000
1584,HCM,2023-06-30,Q,N,-227381602321.000000,-30732814738.000000,0.000000
1585,AAS,2023-06-30,Q,N,15982816260.000000,3599097005.000000,0.000000
1586,TCI,2023-06-30,Q,N,276782111.000000,0.000000,0.000000

In [28]:
scf.check_scfi_51(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_51

    SECURITY_CODE REPORT_DATE FREQ_CODE AUDITED  SCFI_51  SCFI_51_1  SCFI_51_2
122           ART  2020-03-31         Q       N      NaN   0.000000        NaN
127          NSIC  2021-03-31         Q       N      NaN   0.000000        NaN
137           WSS  2021-03-31         Q       N      NaN   0.000000        NaN
138           WSS  2020-12-31         Y       N      NaN   0.000000        NaN
139           WSS  2020-03-31         Q       N      NaN   0.000000        NaN
195           EVS  2021-09-30         Q       N      NaN   0.000000        NaN
202          NVSC  2021-03-31         Q       N      NaN   0.000000        NaN
872          DDSC  2020-09-30         Q       N      NaN   0.000000        NaN
875          DDSC  2021-09-30         Q       N      NaN   0.000000        NaN
876          DDSC  2021-06-30         Q       N      NaN   0.000000        NaN
877          DDSC  2021-03-31         Q       N      NaN   0.000000        NaN
878          DDSC  2020-12-31         Q       N      NaN   0.000000        NaN

In [29]:
scf.check_scfi_60(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_60

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_60,SCFI_1,SCFI_2,SCFI_10,SCFI_18,SCFI_30
56,HVSC,2021-09-30,Q,N,-10028346500.000000,0.000000,0.000000,0.000000,0.000000,0.000000
289,MBS,2020-06-30,Q,Y,-1943266015938.000000,0.000000,21778938746.000000,-3433026550.000000,-2244456696.000000,0.000000
495,SJCS,2022-12-31,Y,Y,-14635531924.000000,-13094668751.000000,9431463260.000000,0.000000,0.000000,-10975326433.000000
866,BMS,2021-06-30,Q,Y,122256025399.000000,0.000000,0.000000,0.000000,0.000000,0.000000
872,DDSC,2020-09-30,Q,N,5258334299.000000,-4926782275202.000000,4884943239139.000000,-550829400.000000,NaN,-32050000000.000000
875,DDSC,2021-09-30,Q,N,52014828853.000000,-23118943913353.000000,22498569170068.000000,0.000000,NaN,-23519194000.000000
876,DDSC,2021-06-30,Q,N,52014828853.000000,-13751453823585.000000,13787302072504.000000,0.000000,NaN,-2636194000.000000
877,DDSC,2021-03-31,Q,N,52014828853.000000,-5538501127662.000000,5543003743202.000000,0.000000,NaN,-2156594000.000000
1007,BMS,2019-06-30,Q,Y,-20611057031.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1089,VPBS,2019-06-30,Q,Y,-662430201636.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1123,SBS,2019-06-30,Q,Y,18329965048.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [30]:
scf.check_scfi_62(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_62

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_62,SCFI_62_1,SCFI_62_2
12,NSIC,2022-12-31,Q,N,-3500000.000000,0.000000,0.000000
13,VDS,2022-09-30,Q,N,545455.000000,0.000000,0.000000
14,TCI,2022-12-31,Y,Y,863636364.000000,0.000000,13380228473.000000
24,PSI,2021-12-31,Y,Y,125454545.000000,0.000000,0.000000
33,EVS,2022-12-31,Y,Y,229090909.000000,0.000000,0.000000
...,...,...,...,...,...,...,...
1556,CTS,2018-12-31,Y,Y,10663636.000000,0.000000,0.000000
1568,VTSC,2018-12-31,Y,Y,424616287.000000,0.000000,0.000000
1570,CTS,2018-12-31,Q,N,8272727.000000,0.000000,0.000000
1578,VND,2018-12-31,Q,N,0.000000,0.000000,36360000000.000000
1580,HCM,2018-12-31,Q,N,25720000.000000,0.000000,0.000000

In [31]:
scf.check_scfi_70(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_70

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_70,SCFI_61,SCFI_62,SCFI_63,SCFI_64,SCFI_65
14,TCI,2022-12-31,Y,Y,-264832964180.000000,-4844463958.000000,863636364.000000,-322930902759.000000,0.000000,48698537700.000000
67,VFS,2021-12-31,Q,N,5587936145.000000,0.000000,0.000000,0.000000,0.000000,10921201340.000000
76,CSI,2022-03-31,Q,N,-40047487.000000,-47150000.000000,0.000000,0.000000,0.000000,0.000000
115,VFS,2021-09-30,Q,N,406322618.000000,0.000000,0.000000,0.000000,0.000000,-4926942577.000000
116,AAS,2021-09-30,Q,N,-995783046.000000,-1105379000.000000,0.000000,0.000000,0.000000,-144599188.000000
117,KEVS,2021-09-30,Q,N,1605935685.000000,-1123200000.000000,0.000000,0.000000,0.000000,-2593366038.000000
146,VDS,2021-06-30,Q,Y,-12381872103.000000,-8230798200.000000,418181817.000000,-51449919931.000000,0.000000,6080664211.000000
195,EVS,2021-09-30,Q,N,-5172028684.000000,-5655740000.000000,NaN,NaN,NaN,NaN
199,TVB,2021-09-30,Q,N,-23586426.000000,-46200000.000000,0.000000,0.000000,0.000000,-35371874.000000
202,NVSC,2021-03-31,Q,N,-223491812.000000,-246277900.000000,NaN,NaN,NaN,22786088.000000
212,KEVS,2021-12-31,Q,N,-5347073314.000000,-5987535345.000000,0.000000,0.000000,0.000000,5962963754.000000
400,VND,2021-03-31,Q,N,-2570697272.000000,-2210697272.000000,0.000000,0.000000,0.000000,0.000000
406,VDS,2021-03-31,Q,N,-33387112645.000000,-36850000.000000,9090908.000000,0.000000,0.000000,7440646447.000000
433,VND,2020-12-31,Y,Y,-13822478063.000000,-12322500463.000000,0.000000,0.000000,0.000000,0.000000
469,VFS,2022-12-31,Q,N,8818135741.000000,0.000000,0.000000,0.000000,0.000000,-7270940771.000000
603,CSI,2022-06-30,Q,Y,6154382.000000,0.000000,0.000000,0.000000,0.000000,13256895.000000
611,VND,2021-12-31,Q,N,-23563568186.000000,-12693288186.000000,0.000000,0.000000,0.000000,0.000000
617,SSI,2022-06-30,Q,Y,1364367858469.000000,-55871038790.000000,0.000000,0.000000,1390327500000.000000,-39305479462.000000
647,TVB,2021-12-31,Q,N,8791658618.000000,-301000000.000000,0.000000,0.000000,8600000000.000000,550644066.000000
683,AAS,2022-12-31,Q,N,-110227237144.000000,-110507790839.000000,0.000000,0.000000,0.000000,-640490142.000000
696,AAS,2021-12-31,Q,N,-236408514.000000,-401612000.000000,0.000000,0.000000,0.000000,419398628.000000
750,BMS,2022-12-31,Y,Y,-4473632590.000000,-4589709400.000000,0.000000,0.000000,0.000000,0.000000
768,ECCS,2022-12-31,Q,N,580949638.000000,0.000000,0.000000,0.000000,0.000000,-413785573.000000
799,NSIC,2022-06-30,Q,Y,28167827851.000000,0.000000,3500000.000000,23000000000.000000,0.000000,-24757450.000000
800,NSIC,2022-09-30,Q,N,15459831427.000000,0.000000,0.000000,0.000000,1000000.000000,20647916728.000000
831,CSI,2023-03-31,Q,N,-121790181.000000,-123150000.000000,0.000000,0.000000,0.000000,0.000000
840,SBBS,2022-12-31,Q,N,161684127.000000,0.000000,0.000000,0.000000,0.000000,-202681447.000000
841,SBBS,2022-12-31,Y,Y,325113494.000000,0.000000,0.000000,0.000000,0.000000,0.000000
859,SSI,2022-09-30,Q,N,481518813945.000000,-49387376965.000000,6190910.000000,-2650000000000.000000,3000000000000.000000,250116876721.000000
863,VND,2021-06-30,Q,Y,-7401060371.000000,-7761060371.000000,0.000000,0.000000,0.000000,0.000000
872,DDSC,2020-09-30,Q,N,12717325854.000000,5258334299.000000,0.000000,0.000000,NaN,NaN
875,DDSC,2021-09-30,Q,N,56655060836.000000,52014828853.000000,52014828853.000000,0.000000,NaN,NaN
876,DDSC,2021-06-30,Q,N,53662883893.000000,52014828853.000000,0.000000,0.000000,NaN,NaN
877,DDSC,2021-03-31,Q,N,39410269945.000000,52014828853.000000,0.000000,0.000000,NaN,NaN
1001,TCI,2019-12-31,Y,Y,1390598855.000000,-18549840000.000000,0.000000,0.000000,0.000000,6149778855.000000
1036,TVB,2019-12-31,Y,Y,-34340556599.000000,-1091209091.000000,0.000000,0.000000,0.000000,750652492.000000
1221,TVB,2019-12-31,Q,N,-25646736172.000000,0.000000,0.000000,8000000000.000000,0.000000,353263828.000000
1254,NSIC,2019-12-31,Q,N,-1495960062.000000,0.000000,46013666.000000,13900000000.000000,0.000000,-1541973728.000000
1274,APG,2023-06-30,Q,N,-129322288.000000,-143000000.000000,0.000000,0.000000,0.000000,0.000000
1380,NSIC,2023-06-30,Q,N,-59992142417.000000,0.000000,0.000000,-85027626030.000000,0.000000,-2417027343.000000
1385,CSI,2023-06-30,Q,N,1653551.000000,0.000000,0.000000,0.000000,0.000000,3013370.000000
1410,TCI,2018-12-31,Y,Y,-175062093.000000,-46750000.000000,354777273.000000,0.000000,0.000000,13307570634.000000
1428,IRSC,2018-09-30,Q,N,0.000000,0.000000,0.000000,0.000000,0.000000,48821548320.000000
1448,IRSC,2018-06-30,Q,N,48534548320.000000,-287000000.000000,0.000000,0.000000,0.000000,0.000000
1509,SSI,2023-06-30,Q,N,-110338065000.000000,-11757691696.000000,47485489710.000000,-146640000000.000000,0.000000,-19572602740.000000
1578,VND,2018-12-31,Q,N,34845678508.000000,-1514321492.000000,0.000000,0.000000,0.000000,0.000000

In [32]:
scf.check_scfi_73(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_73

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_73,SCFI_73_1,SCFI_73_2
195,EVS,2021-09-30,Q,N,528000000000.000000,NaN,528000000000.000000
202,NVSC,2021-03-31,Q,N,8800000000.000000,NaN,8800000000.000000
872,DDSC,2020-09-30,Q,N,0.000000,NaN,NaN
875,DDSC,2021-09-30,Q,N,0.000000,NaN,NaN
876,DDSC,2021-06-30,Q,N,0.000000,NaN,NaN
877,DDSC,2021-03-31,Q,N,0.000000,NaN,NaN

In [33]:
scf.check_scfi_74(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_74

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_74,SCFI_74_1,SCFI_74_2,SCFI_74_3
195,EVS,2021-09-30,Q,N,-161466835824.000000,NaN,NaN,-161466835824.000000
202,NVSC,2021-03-31,Q,N,-8800000000.000000,NaN,NaN,-8800000000.000000
872,DDSC,2020-09-30,Q,N,NaN,NaN,NaN,NaN
875,DDSC,2021-09-30,Q,N,NaN,NaN,NaN,NaN
876,DDSC,2021-06-30,Q,N,NaN,NaN,NaN,NaN
877,DDSC,2021-03-31,Q,N,NaN,NaN,NaN,NaN

In [34]:
scf.check_scfi_80(df=dfi)

CHECK ITEM & SUB-ITEMS SCFI_80

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_80,SCFI_71,SCFI_72,SCFI_73,SCFI_74,SCFI_75,SCFI_76
195,EVS,2021-09-30,Q,N,396533164176.000000,30000000000.000000,NaN,528000000000.000000,-161466835824.000000,NaN,NaN
202,NVSC,2021-03-31,Q,N,0.000000,NaN,NaN,8800000000.000000,-8800000000.000000,NaN,NaN
866,BMS,2021-06-30,Q,Y,642269255.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
872,DDSC,2020-09-30,Q,N,NaN,0.000000,12717325854.000000,0.000000,NaN,NaN,NaN
875,DDSC,2021-09-30,Q,N,NaN,56655060836.000000,0.000000,0.000000,NaN,NaN,NaN
876,DDSC,2021-06-30,Q,N,NaN,53662883893.000000,0.000000,0.000000,NaN,NaN,NaN
877,DDSC,2021-03-31,Q,N,NaN,39410269945.000000,0.000000,0.000000,NaN,NaN,NaN

In [35]:
scf.check_scfi_90(dfi)

CHECK ITEM & SUB-ITEMS SCFI_90

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,SCFI_90,SCFI_60,SCFI_70,SCFI_80
872,DDSC,2020-09-30,Q,N,NaN,5258334299.000000,12717325854.000000,NaN
875,DDSC,2021-09-30,Q,N,NaN,52014828853.000000,56655060836.000000,NaN
876,DDSC,2021-06-30,Q,N,NaN,52014828853.000000,53662883893.000000,NaN
877,DDSC,2021-03-31,Q,N,NaN,52014828853.000000,39410269945.000000,NaN