In [1]:
import pandas as pd
import numpy as np
import cx_Oracle
import os
import platform
import sys
import tomli
import datetime as dt
from check_py import check_company_bs as cbs

pd.set_option('float_format', '{:f}'.format)

In [2]:
# Assign pathlink
path_link_db_algo = r"E:\Tung\BSC_Config\algo_db.toml"

In [3]:
# Import files connfiq
with open(path_link_db_algo, mode="rb") as fp:
    config_acc = tomli.load(fp)

In [4]:
# Set up config for Oracle SQl Developer
host = config_acc["algo_acc"]["host"]
port = config_acc["algo_acc"]["port"]
service_name = config_acc["algo_acc"]["service_name"]
user = config_acc["algo_acc"]["user"]
password = config_acc["algo_acc"]["password"]

In [5]:
# Connect to the Oracle SQL Developer
# cx_Oracle.init_oracle_client(lib_dir=r"E:\Oracle\instantclient-basic-windows.x64-21.10.0.0.0dbru\instantclient_21_10")
lib_dir = r"E:\Oracle\instantclient-basic-windows.x64-21.10.0.0.0dbru\instantclient_21_10"

try:
    cx_Oracle.init_oracle_client(lib_dir=lib_dir)
except Exception as err:
    print("Error connecting: cx_Oracle.init_oracle_client()")
    print(err)

cx_Oracle.clientversion()
os.environ["PATH"] = lib_dir + ";" + os.environ["PATH"]


dsn_tns = cx_Oracle.makedsn(host, port, service_name=service_name) # if needed, place an 'r' before any parameter in order to address special characters such as '\'.
conn = cx_Oracle.connect(user=user, password=password, dsn=dsn_tns) # if needed, place an 'r' before any parameter in order to address special characters such as '\'. For example, if your user name contains '\', you'll need to place 'r' before the user name: user=r'User Name'
c = conn.cursor()

In [6]:
df = pd.read_sql_query(
    """ SELECT 
    *
    FROM COMPANY_BALANCE_SHEET CBS
    INNER JOIN SECURITY_INDUSTRY SI on SI.SECURITY_CODE = CBS.SECURITY_CODE
    WHERE SI.LEVEL3_CODE != 8350
    AND SI.LEVEL3_CODE != 8770
    AND SI.LEVEL3_CODE != 8530
    AND LENGTH(SI.SECURITY_CODE) = 3
    """, con=conn
)

c:\Users\tungtt1\Envs\quant\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [7]:
# df = pd.read_excel(r"/Users/rainmeteror/Desktop/BSC_Algo_Database_UAT/OneDrive_1_5-29-2023/company/algo_cbs.xlsx")

In [8]:
df

,SCN,REPORT_DATE,REPORTED_DATE,FREQ_CODE,SECURITY_CODE,AUDITED,MONTH_IN_PERIOD,CBS_100,CBS_110,CBS_111,...,LEVEL4_ORD,LEVEL4_NAME_VN,LEVEL4_NAME_EN,LEVEL4_NAME_CN,LEVEL4_NAME_KR,LEVEL4_NAME_JP,START_EFFECTIVE_DATE,END_EFFECTIVE_DATE,CREATED_DATE,UPDATED_DATE
0,52528,2020-12-31,NaT,Y,TDN,Y,12.000000,542099994864.000000,3371519299.000000,3371519299.000000,...,140,Khai thác than,Coal,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
1,52528,2020-12-31,NaT,Y,TDP,Y,12.000000,1280062458525.000000,68644581616.000000,68644581616.000000,...,80,Phân đạm và Hóa chất khác,Specialty Chemicals,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-04-18 20:49:10.006413
2,52528,2020-12-31,NaT,Y,TDS,Y,12.000000,361838511803.000000,101785773212.000000,1785773212.000000,...,130,Thép & Sản phẩm thép,Iron & Steel,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
3,52528,2020-12-31,NaT,Y,TDT,Y,12.000000,220141729188.000000,8745655851.000000,8745655851.000000,...,540,Hàng May mặc,Clothing & Accessories,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
4,52528,2020-12-31,NaT,Y,TDW,Y,12.000000,222484505307.000000,127644320566.000000,87644320566.000000,...,850,Nước,Water,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18222,43414051,2023-03-31,NaT,Q,HTT,N,3.000000,29021822877.000000,408540177.000000,408540177.000000,...,660,Bán lẻ phức hợp,Broadline Retailers,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
18223,43414051,2023-03-31,NaT,Q,V12,N,3.000000,328255779228.000000,4418575428.000000,4418575428.000000,...,200,Xây dựng,Heavy Construction,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-06-13 11:49:58.108008
18224,43414051,2023-03-31,NaT,Q,PVG,N,3.000000,975122773790.000000,427228076909.000000,45828076909.000000,...,830,Phân phối Xăng dầu & Khí đốt,Gas Distribution,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
18225,43414051,2023-03-31,NaT,Q,PBC,N,3.000000,1064833135745.000000,39898319955.000000,24498319955.000000,...,620,Dược phẩm,Pharmaceuticals,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
18226,43414051,2023-03-31,NaT,Q,TOT,N,3.000000,88412372417.000000,5610949157.000000,5610949157.000000,...,330,Dịch vụ vận tải,Trucking,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490

In [9]:
cbs.check_cbs_100(df=df)

CHECK ITEM & SUB-ITEMS CBS_100

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_100,CBS_110,CBS_120,CBS_130,CBS_140,CBS_150
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN
2118,LDW,LDW,2021-06-30,Q,Y,631303569408.000000,54244614144.000000,535335665664.000000,33430648832.000000,8245003776.000000,47614440.000000
2241,TNH,TNH,2021-06-30,Q,Y,204919095296.000000,44919451648.000000,0.000000,145575657472.000000,13936841728.000000,487143808.000000
2280,HSG,HSG,2021-06-30,Q,N,17185925758976.000000,505654083584.000000,23517532160.000000,3765465251840.000000,11646465474560.000000,1244823289856.000000
7270,VEF,VEF,2021-06-30,Q,N,5239867965440.000000,2200497553408.000000,1500000026624.000000,1528592728064.000000,0.000000,10777951232.000000
7434,SPD,SPD,2021-06-30,Q,N,349333618688.000000,81472626688.000000,0.000000,83552141312.000000,179234996224.000000,5073856512.000000
7681,PVA,PVA,2021-06-30,Q,N,390063390720.000000,1012260864.000000,0.000000,331791433728.000000,57137586176.000000,122085776.000000
7720,VET,VET,2021-06-30,Q,N,404871380992.000000,35878035456.000000,0.000000,152176279552.000000,211937476608.000000,4879592960.000000
7763,VTX,VTX,2021-06-30,Q,N,322579398656.000000,31379333120.000000,0.000000,189160751104.000000,89836257280.000000,12203049984.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000001.000000,1000000000002.000000,1000000000003.000000,1000000000004.000000,1000000000005.000000,1000000000006.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000001.000000,1000000000002.000000,1000000000003.000000,1000000000004.000000,1000000000005.000000,1000000000006.000000
14058,DFF,DFF,2021-03-31,Q,N,1095732559872.000000,2813509632.000000,0.000000,595438403584.000000,459884167168.000000,37596459008.000000
14130,LLM,LLM,2021-06-30,Q,N,6348948373504.000000,1104918085632.000000,3463000064.000000,4391068762112.000000,763797700608.000000,85700960256.000000

In [10]:
cbs.check_cbs_110(df=df)

CHECK ITEM & SUB-ITEMS CBS_110

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_110,CBS_111,CBS_112
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,3723524459.000000,3723524459.000000,NaN
2118,LDW,LDW,2021-06-30,Q,Y,54244614144.000000,33914163200.000000,20330448896.000000
2280,HSG,HSG,2021-06-30,Q,N,505654083584.000000,468312326144.000000,37341749248.000000
7270,VEF,VEF,2021-06-30,Q,N,2200497553408.000000,341198995456.000000,1859298525184.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000002.000000,3099218346665.000000,8782190000000.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000002.000000,3099218346665.000000,8782190000000.000000
14130,LLM,LLM,2021-06-30,Q,N,1104918085632.000000,537970245632.000000,566947938304.000000

In [11]:
cbs.check_cbs_120(df=df)

CHECK ITEM & SUB-ITEMS CBS_120

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_120,CBS_121,CBS_122,CBS_123
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN,NaN
2118,LDW,LDW,2021-06-30,Q,Y,535335665664.000000,0.000000,0.000000,535335676667.000000
2280,HSG,HSG,2021-06-30,Q,N,23517532160.000000,0.000000,0.000000,23517531836.000000
7270,VEF,VEF,2021-06-30,Q,N,1500000026624.000000,0.000000,0.000000,1500000000000.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000003.000000,0.000000,0.000000,27029902625837.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000003.000000,0.000000,0.000000,27029902625837.000000
13506,NVL,NVL,2021-03-31,Q,N,1011977986695.000000,NaN,NaN,1011977986695.000000
14130,LLM,LLM,2021-06-30,Q,N,3463000064.000000,0.000000,0.000000,3463000000.000000

In [12]:
cbs.check_cbs_130(df=df)

CHECK ITEM & SUB-ITEMS CBS_130

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_130,CBS_131,CBS_132,CBS_133,CBS_134,CBS_135,CBS_136,CBS_137,CBS_139
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,38755226995.000000,18474530400.000000,20240242050.000000,NaN,NaN,NaN,40454545.000000,NaN,NaN
2118,LDW,LDW,2021-06-30,Q,Y,33430648832.000000,4805440000.000000,4502324224.000000,0.000000,0.000000,0.000000,29176676352.000000,-5147524096.000000,93732518.000000
2241,TNH,TNH,2021-06-30,Q,Y,145575657472.000000,26944686080.000000,114605965312.000000,0.000000,0.000000,0.000000,4024999936.000000,0.000000,0.000000
2280,HSG,HSG,2021-06-30,Q,N,3765465251840.000000,2907748171776.000000,671614697472.000000,0.000000,0.000000,0.000000,203137155072.000000,-17034703872.000000,0.000000
7270,VEF,VEF,2021-06-30,Q,N,1528592728064.000000,69600000.000000,55026876416.000000,0.000000,0.000000,1240000000000.000000,233496248320.000000,0.000000,0.000000
7434,SPD,SPD,2021-06-30,Q,N,83552141312.000000,167054475264.000000,7025165312.000000,0.000000,0.000000,0.000000,574115328.000000,-91101618176.000000,0.000000
7681,PVA,PVA,2021-06-30,Q,N,331791433728.000000,88774262784.000000,38488719360.000000,0.000000,10618384384.000000,26880319116.000000,200169455616.000000,-33139707904.000000,0.000000
7720,VET,VET,2021-06-30,Q,N,152176279552.000000,115332931584.000000,26137473024.000000,0.000000,0.000000,0.000000,10705865728.000000,0.000000,0.000000
7763,VTX,VTX,2021-06-30,Q,N,189160751104.000000,142323351552.000000,35894734848.000000,0.000000,0.000000,0.000000,48340209664.000000,-37397540864.000000,0.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000004.000000,3304999656381.000000,6201220324465.000000,0.000000,0.000000,195948347214.000000,2344000106492.000000,-40545279851.000000,1880296035.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000004.000000,3304999656381.000000,6201220324465.000000,0.000000,0.000000,195948347214.000000,2344000106492.000000,-40545279851.000000,1880296035.000000
13506,NVL,NVL,2021-03-31,Q,N,16818356520514.000000,2133360457070.000000,1805529740671.000000,NaN,NaN,3927093447664.000000,8962636520887.000000,-10263645778.000000,NaN
14058,DFF,DFF,2021-03-31,Q,N,595438403584.000000,445094330368.000000,137966567424.000000,0.000000,0.000000,0.000000,12377526272.000000,0.000000,0.000000
14130,LLM,LLM,2021-06-30,Q,N,4391068762112.000000,4126594301952.000000,738754166784.000000,0.000000,0.000000,377105669770.000000,411848409088.000000,-1263233794048.000000,0.000000

In [13]:
cbs.check_cbs_140(df=df)

CHECK ITEM & SUB-ITEMS CBS_140

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_140,CBS_141,CBS_149
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,25441612058.000000,25441612058.000000,NaN
2118,LDW,LDW,2021-06-30,Q,Y,8245003776.000000,9491742720.000000,-1246739200.000000
2280,HSG,HSG,2021-06-30,Q,N,11646465474560.000000,11712491159552.000000,-66025385984.000000
7763,VTX,VTX,2021-06-30,Q,N,89836257280.000000,89979297792.000000,-143039184.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000005.000000,44779256645900.000000,-898989196955.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000005.000000,44779256645900.000000,-898989196955.000000

In [14]:
cbs.check_cbs_150(df=df)

CHECK ITEM & SUB-ITEMS CBS_150

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_150,CBS_151,CBS_152,CBS_153,CBS_154,CBS_155
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,898855221.000000,345853796.000000,553001425.000000,NaN,NaN,NaN
2118,LDW,LDW,2021-06-30,Q,Y,47614440.000000,46744864.000000,0.000000,869574.000000,0.000000,0.000000
2280,HSG,HSG,2021-06-30,Q,N,1244823289856.000000,147564691456.000000,1097172058112.000000,86496288.000000,0.000000,0.000000
7270,VEF,VEF,2021-06-30,Q,N,10777951232.000000,0.000000,10766989312.000000,10961787.000000,0.000000,0.000000
7434,SPD,SPD,2021-06-30,Q,N,5073856512.000000,3053042944.000000,1927117312.000000,93696328.000000,0.000000,0.000000
7681,PVA,PVA,2021-06-30,Q,N,122085776.000000,62937716.000000,59148064.000000,0.000000,0.000000,0.000000
7763,VTX,VTX,2021-06-30,Q,N,12203049984.000000,3789796352.000000,7648837632.000000,764416128.000000,0.000000,0.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000006.000000,382373843447.000000,1667295961834.000000,21801324159.000000,0.000000,0.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000006.000000,382373843447.000000,1667295961834.000000,21801324159.000000,0.000000,0.000000
13506,NVL,NVL,2021-03-31,Q,N,1186968548418.000000,154752333673.000000,945807189878.000000,86409024867.000000,NaN,NaN
14058,DFF,DFF,2021-03-31,Q,N,37596459008.000000,1177825792.000000,36418629632.000000,0.000000,0.000000,0.000000
14130,LLM,LLM,2021-06-30,Q,N,85700960256.000000,404865952.000000,54336606208.000000,30959486976.000000,0.000000,0.000000

In [15]:
cbs.check_cbs_200(df=df)

CHECK ITEM & SUB-ITEMS CBS_200

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_200,CBS_210,CBS_220,CBS_230,CBS_240,CBS_250,CBS_260
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1343,STG,STG,2020-03-31,Q,N,1265914237245.000000,6705091195.000000,724759661802.000000,0.000000,56000695630.000000,383508181028.000000,32813782134.000000
1871,TDH,TDH,2020-03-31,Q,N,2840801231445.000000,682007387264.000000,469499750853.000000,90825333945.000000,920241998396.000000,623968723057.000000,39758410710.000000
2118,LDW,LDW,2021-06-30,Q,Y,856571969536.000000,728036608.000000,807814234112.000000,0.000000,7359427703.000000,11125252096.000000,29544984576.000000
2241,TNH,TNH,2021-06-30,Q,Y,1029612044288.000000,0.000000,899010068480.000000,24423014400.000000,0.000000,74699997184.000000,31478988800.000000
2280,HSG,HSG,2021-06-30,Q,N,7975077937152.000000,174529888256.000000,6905427132416.000000,0.000000,536337337180.000000,21472159744.000000,337311924224.000000
2368,C21,C21,2020-03-31,Q,N,515976477154.000000,136505712975.000000,138996593886.000000,7291797526.000000,135225560701.000000,75800000000.000000,21080949888.000000
2733,FPT,FPT,2020-09-30,Q,N,15284122357685.000000,371632861351.000000,7238790571133.000000,0.000000,2619085803954.000000,2529556438447.000000,2318332539037.000000
3801,FPT,FPT,2020-06-30,Q,Y,14938070369160.000000,348427785518.000000,7365996280591.000000,0.000000,2233265003791.000000,2451568314545.000000,2325398922216.000000
4011,FCN,FCN,2020-12-31,Q,N,1198110017994.000000,48082541598.000000,674517511500.000000,0.000000,45205534272.000000,303763816009.000000,74388972330.000000
4299,ITD,ITD,2020-12-31,Q,N,103655556521.000000,5829069695.000000,68087377369.000000,18028936731.000000,328598902.000000,7367100000.000000,3930104497.000000
5602,FCM,FCM,2020-12-31,Y,Y,177448497543.000000,2648598398.000000,152795185440.000000,864700000.000000,20425740827.000000,0.000000,637897878.000000
7270,VEF,VEF,2021-06-30,Q,N,2530786410496.000000,1262883569664.000000,176442016.000000,0.000000,1267475476261.000000,0.000000,250805088.000000
7434,SPD,SPD,2021-06-30,Q,N,84589166592.000000,0.000000,63551983616.000000,0.000000,50000000.000000,20987176960.000000,0.000000
7580,ITD,ITD,2020-12-31,Y,N,103655556521.000000,5829069695.000000,68087377369.000000,18028936731.000000,328598902.000000,7367100000.000000,3930104497.000000
7681,PVA,PVA,2021-06-30,Q,N,117569945600.000000,102721708032.000000,11133306880.000000,0.000000,1090113570.000000,1956822912.000000,668000000.000000
7720,VET,VET,2021-06-30,Q,N,440736022528.000000,365641824.000000,204484820992.000000,0.000000,22207109123.000000,201500000256.000000,12178440192.000000
7763,VTX,VTX,2021-06-30,Q,N,177314971648.000000,2616741376.000000,157805101056.000000,0.000000,1954500259.000000,816000000.000000,14122628096.000000
9654,LAW,LAW,2022-03-31,Q,N,262930904488.000000,0.000000,243929595881.000000,0.000000,17088023151.000000,0.000000,1135164296.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000007.000000,1000000000008.000000,1000000000009.000000,1000000000010.000000,1000000000011.000000,1000000000012.000000,1000000000013.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000007.000000,1000000000008.000000,1000000000009.000000,1000000000010.000000,1000000000011.000000,1000000000012.000000,1000000000013.000000
14058,DFF,DFF,2021-03-31,Q,N,718740979712.000000,18540521472.000000,512209485824.000000,0.000000,77720172761.000000,0.000000,110270783488.000000
14130,LLM,LLM,2021-06-30,Q,N,966562873344.000000,9585300480.000000,182955868160.000000,21188380672.000000,41001732180.000000,628618428416.000000,83213189120.000000

In [16]:
cbs.check_cbs_210(df=df)

CHECK ITEM & SUB-ITEMS CBS_210

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_210,CBS_211,CBS_212,CBS_213,CBS_214,CBS_215,CBS_216,CBS_219
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7270,VEF,VEF,2021-06-30,Q,N,1262883569664.000000,0.000000,0.000000,0.000000,0.000000,1250000000000.000000,12883561472.000000,0.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000008.000000,0.000000,0.000000,0.000000,0.000000,107320214500.000000,792406327115.000000,0.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000008.000000,0.000000,0.000000,0.000000,0.000000,107320214500.000000,792406327115.000000,0.000000
13506,NVL,NVL,2021-03-31,Q,N,19721144918117.000000,NaN,NaN,NaN,NaN,175500000000.000000,19545644918117.000000,NaN

In [17]:
cbs.check_cbs_220(df=df)

CHECK ITEM & SUB-ITEMS CBS_220

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_220,CBS_221,CBS_224,CBS_227
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN
1450,DRC,DRC,2020-06-30,Q,Y,1130181648351.000000,1124774855156.000000,1607848514.000000,3798944675.000000
2118,LDW,LDW,2021-06-30,Q,Y,807814234112.000000,806318374912.000000,0.000000,1495889408.000000
2241,TNH,TNH,2021-06-30,Q,Y,899010068480.000000,886977527808.000000,0.000000,12032536576.000000
2280,HSG,HSG,2021-06-30,Q,N,6905427132416.000000,6692305633280.000000,0.000000,213121089536.000000
5223,PTO,PTO,2020-12-31,Y,Y,1126097186.000000,1126097186.000000,0.000000,265565930.000000
7434,SPD,SPD,2021-06-30,Q,N,63551983616.000000,60512301056.000000,0.000000,3039683328.000000
7763,VTX,VTX,2021-06-30,Q,N,157805101056.000000,72754126848.000000,77426638848.000000,7624332800.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000009.000000,71130462789491.000000,0.000000,594289368309.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000009.000000,71130462789491.000000,0.000000,594289368309.000000
14058,DFF,DFF,2021-03-31,Q,N,512209485824.000000,387677323264.000000,116705550336.000000,7826638336.000000
14130,LLM,LLM,2021-06-30,Q,N,182955868160.000000,146613403648.000000,19928528896.000000,16413929472.000000

In [18]:
cbs.check_cbs_221(df=df)

CHECK ITEM & SUB-ITEMS CBS_221

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_221,CBS_222,CBS_223
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
2241,TNH,TNH,2021-06-30,Q,Y,886977527808.000000,938709024768.000000,-51731501056.000000
2280,HSG,HSG,2021-06-30,Q,N,6692305633280.000000,13637271945216.000000,-6944966836224.000000
7270,VEF,VEF,2021-06-30,Q,N,176442016.000000,5522680320.000000,-5346238464.000000
7434,SPD,SPD,2021-06-30,Q,N,60512301056.000000,233186770944.000000,-172674465792.000000
7720,VET,VET,2021-06-30,Q,N,204484820992.000000,528857890816.000000,-324373053440.000000
7763,VTX,VTX,2021-06-30,Q,N,72754126848.000000,514942140416.000000,-442188005376.000000
14058,DFF,DFF,2021-03-31,Q,N,387677323264.000000,584147730432.000000,-196470423552.000000

In [19]:
cbs.check_cbs_224(df=df)

CHECK ITEM & SUB-ITEMS CBS_224

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_224,CBS_225,CBS_226
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN
7763,VTX,VTX,2021-06-30,Q,N,77426638848.000000,77859192832.000000,-432551072.000000
13506,NVL,NVL,2021-03-31,Q,N,0.000000,NaN,NaN
14058,DFF,DFF,2021-03-31,Q,N,116705550336.000000,128120905728.000000,-11415356416.000000
14130,LLM,LLM,2021-06-30,Q,N,19928528896.000000,26999052288.000000,-7070524928.000000

In [20]:
cbs.check_cbs_227(df=df)

CHECK ITEM & SUB-ITEMS CBS_227

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_227,CBS_228,CBS_229
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,466904696.000000,466904696.000000,NaN
2118,LDW,LDW,2021-06-30,Q,Y,1495889408.000000,1903591040.000000,-407701568.000000
2280,HSG,HSG,2021-06-30,Q,N,213121089536.000000,285209952256.000000,-72088879104.000000
7763,VTX,VTX,2021-06-30,Q,N,7624332800.000000,9498251264.000000,-1873918976.000000
14058,DFF,DFF,2021-03-31,Q,N,7826638336.000000,11299505152.000000,-3472866560.000000
14130,LLM,LLM,2021-06-30,Q,N,16413929472.000000,18370095104.000000,-1956165248.000000

In [21]:
cbs.check_cbs_230(df=df)

CHECK ITEM & SUB-ITEMS CBS_230

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_230,CBS_231,CBS_232
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN
2241,TNH,TNH,2021-06-30,Q,Y,24423014400.000000,24915812352.000000,-492797600.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000010.000000,699081218971.000000,-174140132821.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000010.000000,699081218971.000000,-174140132821.000000
14130,LLM,LLM,2021-06-30,Q,N,21188380672.000000,57127964672.000000,-35939581952.000000

In [22]:
cbs.check_cbs_230(df=df)

CHECK ITEM & SUB-ITEMS CBS_230

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_230,CBS_231,CBS_232
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN
2241,TNH,TNH,2021-06-30,Q,Y,24423014400.000000,24915812352.000000,-492797600.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000010.000000,699081218971.000000,-174140132821.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000010.000000,699081218971.000000,-174140132821.000000
14130,LLM,LLM,2021-06-30,Q,N,21188380672.000000,57127964672.000000,-35939581952.000000

In [23]:
cbs.check_cbs_240(df=df)

CHECK ITEM & SUB-ITEMS CBS_240

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_240,CBS_241,CBS_242
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN
11370,HPG,HPG,2022-09-30,Q,N,1000000000011.000000,46484597502.000000,9655145059043.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000011.000000,46484597502.000000,9655145059043.000000

In [24]:
cbs.check_cbs_250(df=df)

CHECK ITEM & SUB-ITEMS CBS_250

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_250,CBS_251,CBS_252,CBS_253,CBS_254,CBS_255,CBS_2691
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
796,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
1343,STG,STG,2020-03-31,Q,N,383508181028.000000,0.000000,351772708466.000000,1629124639.000000,0.000000,30106347923.000000,62126825456.000000
1871,TDH,TDH,2020-03-31,Q,N,623968723057.000000,0.000000,317672350837.000000,306746372220.000000,-450000000.000000,0.000000,14499627220.000000
2280,HSG,HSG,2021-06-30,Q,N,21472159744.000000,0.000000,0.000000,0.000000,0.000000,21472160000.000000,0.000000
2368,C21,C21,2020-03-31,Q,N,75800000000.000000,0.000000,75800000000.000000,6750000000.000000,-6750000000.000000,0.000000,1075862178.000000
2733,FPT,FPT,2020-09-30,Q,N,2529556438447.000000,0.000000,1910490057651.000000,922165806267.000000,-303299425471.000000,200000000.000000,206724143763.000000
3801,FPT,FPT,2020-06-30,Q,Y,2451568314545.000000,0.000000,1890355276994.000000,865250071864.000000,-304037034313.000000,0.000000,213414062499.000000
4011,FCN,FCN,2020-12-31,Q,N,303763816009.000000,0.000000,188633242500.000000,114630573509.000000,0.000000,500000000.000000,52151642285.000000
4299,ITD,ITD,2020-12-31,Q,N,7367100000.000000,0.000000,0.000000,7367100000.000000,0.000000,0.000000,84369327.000000
5602,FCM,FCM,2020-12-31,Y,Y,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,76375000.000000
6294,GEX,GEX,2020-12-31,Q,N,5798321861657.000000,0.000000,5673889499998.000000,124370401581.000000,0.000000,625000000.000000,0.000000
7434,SPD,SPD,2021-06-30,Q,N,20987176960.000000,0.000000,18365569024.000000,2121607424.000000,0.000000,500000000.000000,0.000000
7580,ITD,ITD,2020-12-31,Y,N,7367100000.000000,0.000000,0.000000,7367100000.000000,0.000000,0.000000,84369327.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000012.000000,0.000000,0.000000,700000000.000000,0.000000,532521643835.000000,NaN
11371,HPG,HPG,2022-09-30,Q,N,1000000000012.000000,0.000000,0.000000,700000000.000000,0.000000,532521643835.000000,NaN
13506,NVL,NVL,2021-03-31,Q,N,1785629241980.000000,NaN,1644265421980.000000,25349750000.000000,116014070000.000000,NaN,0.000000
14130,LLM,LLM,2021-06-30,Q,N,628618428416.000000,0.000000,396147261440.000000,255227052032.000000,-23075930112.000000,320000000.000000,0.000000

In [25]:
cbs.check_cbs_260(df=df)

CHECK ITEM & SUB-ITEMS CBS_260

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_260,CBS_261,CBS_262,CBS_263,CBS_268,CBS_269
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,338915725.000000,338915725.000000,NaN,NaN,NaN,NaN
2118,LDW,LDW,2021-06-30,Q,Y,29544984576.000000,20544944128.000000,0.000000,9000040985.000000,0.000000,0.000000
2280,HSG,HSG,2021-06-30,Q,N,337311924224.000000,222931845120.000000,114380087296.000000,0.000000,0.000000,0.000000
7270,VEF,VEF,2021-06-30,Q,N,250805088.000000,22908142.000000,227896944.000000,0.000000,0.000000,0.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000013.000000,3512918448027.000000,4737657938.000000,0.000000,0.000000,32630950665.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000013.000000,3512918448027.000000,4737657938.000000,0.000000,0.000000,32630950665.000000
13506,NVL,NVL,2021-03-31,Q,N,6337015379549.000000,487633399414.000000,104053368742.000000,NaN,NaN,5745328611393.000000
14130,LLM,LLM,2021-06-30,Q,N,83213189120.000000,83072131072.000000,0.000000,0.000000,0.000000,141057065.000000

In [26]:
cbs.check_cbs_300(df=df)

CHECK ITEM & SUB-ITEMS CBS_300

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_300,CBS_310,CBS_330
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
2118,LDW,LDW,2021-06-30,Q,Y,315485913088.000000,72848343040.000000,242637586432.000000
2241,TNH,TNH,2021-06-30,Q,Y,547253256192.000000,188327968768.000000,358925271040.000000
2280,HSG,HSG,2021-06-30,Q,N,15305000615936.000000,13666262974464.000000,1638738165760.000000
7434,SPD,SPD,2021-06-30,Q,N,318907121664.000000,308902920192.000000,10004196352.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000015.000000,1000000000016.000000,1000000000019.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000015.000000,1000000000016.000000,1000000000019.000000
14058,DFF,DFF,2021-03-31,Q,N,1342178983936.000000,994412986368.000000,347766063104.000000
14130,LLM,LLM,2021-06-30,Q,N,6233380618240.000000,6208592281600.000000,24788072448.000000

In [27]:
cbs.check_cbs_310(df=df)

CHECK ITEM & SUB-ITEMS CBS_310

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_310,CBS_311,CBS_312,CBS_313,CBS_314,CBS_315,CBS_316,CBS_317,CBS_318,CBS_319,CBS_320,CBS_321,CBS_322,CBS_323,CBS_324
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,17926616277.000000,542495962.000000,0.000000,508712215.000000,180637000.000000,NaN,NaN,NaN,NaN,0.000000,16694771100.000000,NaN,NaN,NaN,NaN
2118,LDW,LDW,2021-06-30,Q,Y,72848343040.000000,13569855488.000000,627972288.000000,4823732224.000000,8517284864.000000,2643337472.000000,0.000000,0.000000,0.000000,10309886976.000000,22793678848.000000,0.000000,9562599424.000000,0.000000,0.000000
2123,TCK,TCK,2020-12-31,Q,N,988013198200.000000,118091055136.000000,162673031731.000000,138579607776.000000,14985229054.000000,209361640589.000000,0.000000,0.000000,4002500028.000000,187954981485.000000,160296454766.000000,806389478.000000,385816786.000000,0.000000,0.000000
2241,TNH,TNH,2021-06-30,Q,Y,188327968768.000000,40254832640.000000,926926528.000000,1009694848.000000,4983936000.000000,907594496.000000,0.000000,0.000000,0.000000,820796672.000000,139424186368.000000,0.000000,0.000000,0.000000,0.000000
2280,HSG,HSG,2021-06-30,Q,N,13666262974464.000000,3461131010048.000000,320003899392.000000,586979999744.000000,72154284032.000000,239609774080.000000,0.000000,0.000000,0.000000,3450182828032.000000,5451456970752.000000,0.000000,84743725056.000000,0.000000,0.000000
4907,BBC,BBC,2020-12-31,Q,N,316050505485.000000,12188361330.000000,7593682693.000000,10295066593.000000,4433797639.000000,86337353511.000000,0.000000,0.000000,0.000000,5405907865.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7270,VEF,VEF,2021-06-30,Q,N,4935448002560.000000,1432951936.000000,130483616.000000,32177762304.000000,628488704.000000,0.000000,0.000000,0.000000,238310214.000000,4900840275968.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7434,SPD,SPD,2021-06-30,Q,N,308902920192.000000,17397237760.000000,70000000.000000,24801182.000000,3263002880.000000,1525882368.000000,0.000000,0.000000,430223264.000000,93030424576.000000,191862554624.000000,0.000000,1298787584.000000,0.000000,0.000000
7681,PVA,PVA,2021-06-30,Q,N,441669844992.000000,121349980160.000000,86357098496.000000,10112602112.000000,6296355328.000000,31030716416.000000,0.000000,10801668096.000000,0.000000,119645396992.000000,35991064576.000000,0.000000,20084951040.000000,0.000000,0.000000
7720,VET,VET,2021-06-30,Q,N,285794435072.000000,55187443712.000000,2500818688.000000,-2525091584.000000,0.000000,0.000000,0.000000,0.000000,53623192569.000000,173182664704.000000,0.000000,10982560768.000000,-7157148672.000000,0.000000,0.000000
7763,VTX,VTX,2021-06-30,Q,N,205150666752.000000,49053200384.000000,58949419008.000000,489554560.000000,4026894848.000000,28623296512.000000,0.000000,0.000000,0.000000,7924207616.000000,56050565120.000000,0.000000,33521788.000000,0.000000,0.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000016.000000,1000000000018.000000,655008097406.000000,964027308325.000000,236490648673.000000,580665753473.000000,0.000000,0.000000,34851995241.000000,739883139012.000000,1000000000017.000000,4131439230.000000,1856584734941.000000,0.000000,0.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000016.000000,1000000000018.000000,655008097406.000000,964027308325.000000,236490648673.000000,580665753473.000000,0.000000,0.000000,34851995241.000000,739883139012.000000,1000000000017.000000,4131439230.000000,1856584734941.000000,0.000000,0.000000
13506,NVL,NVL,2021-03-31,Q,N,35418652059614.000000,2676359388907.000000,5373051850224.000000,766624343283.000000,26146310784.000000,5248137197450.000000,NaN,NaN,5196639564.000000,4691629725750.000000,16608633013789.000000,17324724568.000000,5548865295.000000,NaN,NaN
14058,DFF,DFF,2021-03-31,Q,N,994412986368.000000,312701452288.000000,51239698432.000000,14865824768.000000,0.000000,12000000.000000,0.000000,0.000000,0.000000,49296064512.000000,566297952256.000000,0.000000,0.000000,0.000000,0.000000
14130,LLM,LLM,2021-06-30,Q,N,6208592281600.000000,3830724952064.000000,146532761600.000000,26176882688.000000,38128750592.000000,479796854784.000000,0.000000,0.000000,893927824.000000,125189136384.000000,1479769325568.000000,12796059648.000000,68583608320.000000,0.000000,0.000000
14930,TNH,TNH,2022-09-30,Q,N,269858196269.000000,25015412936.000000,3233235389.000000,1919289578.000000,7443818177.000000,0.000000,0.000000,0.000000,0.000000,0.000000,232212225987.000000,0.000000,0.000000,0.000000,0.000000
15202,SDC,SDC,2022-12-31,Q,N,31911212440.000000,2212053792.000000,7542417550.000000,645332161.000000,8595678076.000000,80009091.000000,0.000000,0.000000,0.000000,7937588547.000000,3616075400.000000,0.000000,1226502267.000000,0.000000,0.000000
17762,SBR,SBR,2022-06-30,Q,Y,162547226935.000000,4196658397.000000,5961409795.000000,29613076947.000000,9464843829.000000,52500000.000000,0.000000,0.000000,0.000000,14711642049.000000,0.000000,0.000000,98217095918.000000,0.000000,0.000000

In [28]:
cbs.check_cbs_330(df=df)

CHECK ITEM & SUB-ITEMS CBS_330

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_330,CBS_331,CBS_332,CBS_333,CBS_334,CBS_335,CBS_336,CBS_337,CBS_338,CBS_339,CBS_340,CBS_341,CBS_342,CBS_343
52,TL4,TL4,2020-12-31,Y,Y,266357051533.000000,0.000000,47635612447.000000,0.000000,0.000000,0.000000,0.000000,131063400000.000000,73058384858.000000,0.000000,0.000000,972730000.000000,0.000000,0.000000
159,ACC,ACC,2021-03-31,Q,N,10910181576.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,185610470.000000,0.000000,0.000000
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668,DTD,DTD,2021-03-31,Q,N,941620957977.000000,0.000000,0.000000,694144800378.000000,0.000000,0.000000,49848214793.000000,27708242000.000000,0.000000,0.000000,0.000000,1606680618.000000,0.000000,0.000000
765,GMC,GMC,2021-03-31,Q,N,16072121810.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7167693893.000000,0.000000,0.000000
796,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
841,KBC,KBC,2021-03-31,Q,N,6178358766991.000000,0.000000,0.000000,1194760831265.000000,0.000000,0.000000,4632208004.000000,30531288820.000000,4085865356568.000000,0.000000,0.000000,861617114372.000000,0.000000,0.000000
883,GMC,GMC,2021-06-30,Q,Y,15045573805.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6665356638.000000,0.000000,0.000000
2118,LDW,LDW,2021-06-30,Q,Y,242637586432.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,502782112.000000,241712889856.000000,0.000000,0.000000,0.000000,0.000000,421909952.000000
2123,TCK,TCK,2020-12-31,Q,N,14241246637.000000,0.000000,0.000000,0.000000,0.000000,0.000000,929137116.000000,41150000.000000,4632512898.000000,0.000000,0.000000,373403093.000000,0.000000,0.000000
2241,TNH,TNH,2021-06-30,Q,Y,358925271040.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7638181888.000000,0.000000,351287083008.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2280,HSG,HSG,2021-06-30,Q,N,1638738165760.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,709500032.000000,1624262180864.000000,0.000000,0.000000,0.000000,13766513664.000000,0.000000
3660,SAB,SAB,2020-06-30,Q,Y,844250361848.000000,88793875350.000000,22183449.000000,0.000000,0.000000,0.000000,0.000000,54010016000.000000,459456327274.000000,0.000000,0.000000,0.000000,127298621349.000000,81700729929.000000
4213,DTD,DTD,2020-12-31,Q,N,1213759729798.000000,0.000000,0.000000,948349855026.000000,0.000000,0.000000,24807776000.000000,78608242000.000000,0.000000,0.000000,0.000000,640753185.000000,0.000000,0.000000
4275,PVC,PVC,2020-12-31,Q,N,13793118839.000000,0.000000,0.000000,0.000000,0.000000,0.000000,312000000.000000,140200000.000000,0.000000,0.000000,0.000000,2546382889.000000,0.000000,0.000000
4390,ACC,ACC,2020-12-31,Q,N,47007951476.000000,0.000000,0.000000,32946001502.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,326114941.000000,0.000000,0.000000
4459,KBC,KBC,2020-12-31,Q,N,6107539517181.000000,0.000000,0.000000,1074837878371.000000,0.000000,0.000000,4664114060.000000,31820359756.000000,4218161587925.000000,0.000000,0.000000,777103609107.000000,0.000000,0.000000
5361,PVC,PVC,2020-12-31,Y,Y,34882930213.000000,0.000000,0.000000,0.000000,0.000000,0.000000,312000000.000000,140200000.000000,0.000000,0.000000,0.000000,2553931176.000000,0.000000,0.000000
5978,ACC,ACC,2020-12-31,Y,Y,41376446754.000000,0.000000,0.000000,27455001251.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,185610470.000000,0.000000,0.000000
6179,TL4,TL4,2020-12-31,Q,N,266357051533.000000,0.000000,47635612447.000000,0.000000,0.000000,0.000000,0.000000,131063400000.000000,73058384858.000000,0.000000,0.000000,972730000.000000,0.000000,0.000000
6462,GMC,GMC,2020-12-31,Q,N,16375015014.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7354595514.000000,0.000000,0.000000
7270,VEF,VEF,2021-06-30,Q,N,713048981504.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,49000000.000000,713000026112.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7620,KBC,KBC,2020-12-31,Y,Y,6170686623560.000000,0.000000,0.000000,1134633021863.000000,0.000000,0.000000,4664114060.000000,35537754956.000000,4218161587925.000000,0.000000,0.000000,776738176794.000000,0.000000,0.000000
7761,GMC,GMC,2020-12-31,Y,Y,16375015014.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7354595514.000000,0.000000,0.000000
7763,VTX,VTX,2021-06-30,Q,N,45857341440.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,139500000.000000,45717839872.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000019.000000,0.000000,0.000000,442814206975.000000,0.000000,0.000000,8803217550.000000,62796076046.000000,1000000000020.000000,0.000000,0.000000,194695464.000000,55955940904.000000,0.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000019.000000,0.000000,0.000000,442814206975.000000,0.000000,0.000000,8803217550.000000,62796076046.000000,1000000000020.000000,0.000000,0.000000,194695464.000000,55955940904.000000,0.000000
13506,NVL,NVL,2021-03-31,Q,N,80488681606332.000000,NaN,NaN,NaN,NaN,NaN,13812001719.000000,42500974723692.000000,28537305159101.000000,NaN,NaN,9303390966825.000000,133198754995.000000,NaN
14058,DFF,DFF,2021-03-31,Q,N,347766063104.000000,104031051776.000000,0.000000,0.000000,0.000000,0.000000,0.000000,410000000.000000,243325009920.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14130,LLM,LLM,2021-06-30,Q,N,24788072448.000000,0.000000,0.000000,1588264116.000000,0.000000,0.000000,15914414080.000000,842586816.000000,871457984.000000,0.000000,0.000000,2787618816.000000,2783731200.000000,0.000000

In [29]:
cbs.check_cbs_400(df=df)

CHECK ITEM & SUB-ITEMS CBS_400

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_400,CBS_410,CBS_430
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,0.000000
2118,LDW,LDW,2021-06-30,Q,Y,1172389625856.000000,864385433600.000000,308004159488.000000
7720,VET,VET,2021-06-30,Q,N,358312968192.000000,335243771904.000000,23069173760.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000021.000000,1000000000022.000000,0.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000021.000000,1000000000022.000000,0.000000
14130,LLM,LLM,2021-06-30,Q,N,1082130890752.000000,1080236507136.000000,1894347520.000000

In [30]:
cbs.check_cbs_410(df=df)

CHECK ITEM & SUB-ITEMS CBS_410

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_410,CBS_411,CBS_412,CBS_413,CBS_414,CBS_415,CBS_416,CBS_417,CBS_418,CBS_419,CBS_420,CBS_421,CBS_429
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,56464297994.000000,50000000000.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,6464297994.000000,NaN
2118,LDW,LDW,2021-06-30,Q,Y,864385433600.000000,788000014336.000000,28512122880.000000,0.000000,11874131968.000000,0.000000,0.000000,0.000000,12863714304.000000,0.000000,0.000000,23135455232.000000,0.000000
2241,TNH,TNH,2021-06-30,Q,Y,687277932544.000000,415000002560.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,272277913600.000000,0.000000
2280,HSG,HSG,2021-06-30,Q,N,9856003080192.000000,4446252171264.000000,157292544000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,98970607616.000000,5136785604608.000000,16702038776.000000
3195,TNI,TNI,2020-03-31,Q,N,708689349245.000000,525000000000.000000,3811400000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1393427931.000000,0.000000,0.000000,63574521314.000000,0.000000
3967,KMT,KMT,2020-12-31,Q,N,125952756467.000000,98465620000.000000,300347000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14355705817.000000,0.000000,0.000000,11340064961.000000,0.000000
7256,KMT,KMT,2020-12-31,Y,Y,125952756467.000000,98465620000.000000,300347000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14355705817.000000,0.000000,0.000000,11340064961.000000,0.000000
7270,VEF,VEF,2021-06-30,Q,N,2122157260800.000000,1666040463360.000000,5288133120.000000,0.000000,0.000000,-30150000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,450858778624.000000,0.000000
7434,SPD,SPD,2021-06-30,Q,N,115153313792.000000,120000004096.000000,-101650000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11388233728.000000,0.000000,0.000000,-16133268480.000000,0.000000
7681,PVA,PVA,2021-06-30,Q,N,-33843703808.000000,218459996160.000000,5000000000.000000,0.000000,380952384.000000,0.000000,0.000000,0.000000,23453681664.000000,0.000000,0.000000,-281138331648.000000,0.000000
7720,VET,VET,2021-06-30,Q,N,335243771904.000000,160000000000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,129267720192.000000,0.000000,0.000000,45976064000.000000,0.000000
7763,VTX,VTX,2021-06-30,Q,N,248886362112.000000,209723211776.000000,15257068544.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5352597504.000000,0.000000,0.000000,18553483264.000000,0.000000
11370,HPG,HPG,2022-09-30,Q,N,1000000000022.000000,58147857000000.000000,3211560416270.000000,0.000000,0.000000,0.000000,0.000000,-33173627407.000000,811606247382.000000,0.000000,0.000000,35825427344474.000000,112205547137.000000
11371,HPG,HPG,2022-09-30,Q,N,1000000000022.000000,58147857000000.000000,3211560416270.000000,0.000000,0.000000,0.000000,0.000000,-33173627407.000000,811606247382.000000,0.000000,0.000000,35825427344474.000000,112205547137.000000
13506,NVL,NVL,2021-03-31,Q,N,37758920568046.000000,10728120350000.000000,8234540694626.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,12588298117556.000000,6207961405864.000000
14058,DFF,DFF,2021-03-31,Q,N,472294457344.000000,399999991808.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,71994875904.000000,299593471.000000
14130,LLM,LLM,2021-06-30,Q,N,1080236507136.000000,797261037568.000000,0.000000,0.000000,1694624256.000000,0.000000,-32374321152.000000,-9637472256.000000,86487908352.000000,0.000000,18290852.000000,229250842624.000000,7535605319.000000

In [31]:
cbs.check_cbs_411(df=df)

CHECK ITEM & SUB-ITEMS CBS_411

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_411,CBS_411A,CBS_411B
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
796,HSV,HSV,2021-03-31,Q,N,50000000000.000000,50000000000.000000,NaN
2118,LDW,LDW,2021-06-30,Q,Y,788000014336.000000,788000000000.000000,0.000000
2241,TNH,TNH,2021-06-30,Q,Y,415000002560.000000,415000000000.000000,0.000000
2280,HSG,HSG,2021-06-30,Q,N,4446252171264.000000,4446252130000.000000,0.000000
7270,VEF,VEF,2021-06-30,Q,N,1666040463360.000000,1666040500000.000000,0.000000
7434,SPD,SPD,2021-06-30,Q,N,120000004096.000000,120000000000.000000,0.000000
7681,PVA,PVA,2021-06-30,Q,N,218459996160.000000,218460000000.000000,0.000000
7763,VTX,VTX,2021-06-30,Q,N,209723211776.000000,209723210000.000000,0.000000
13506,NVL,NVL,2021-03-31,Q,N,10728120350000.000000,10728120350000.000000,NaN
14058,DFF,DFF,2021-03-31,Q,N,399999991808.000000,400000000000.000000,0.000000
14130,LLM,LLM,2021-06-30,Q,N,797261037568.000000,797261040000.000000,0.000000

In [36]:
cbs.check_cbs_419(df=df)

CHECK ITEM & SUB-ITEMS CBS_419

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_419,CBS_4191,CBS_4192
65,TTZ,TTZ,2020-12-31,Y,Y,0.000000,NaN,0.000000
70,VC2,VC2,2020-12-31,Y,Y,0.000000,NaN,0.000000
72,VC6,VC6,2020-12-31,Y,Y,0.000000,NaN,0.000000
121,TNW,TNW,2020-12-31,Y,Y,0.000000,NaN,0.000000
122,TOP,TOP,2020-12-31,Y,Y,0.000000,NaN,0.000000
...,...,...,...,...,...,...,...,...
16797,HEJ,HEJ,2021-12-31,Y,Y,0.000000,NaN,0.000000
17082,ASM,ASM,2022-12-31,Y,Y,4878380532.000000,0.000000,0.000000
17083,ASM,ASM,2022-12-31,Q,N,4878380532.000000,0.000000,0.000000
17110,LQN,LQN,2022-12-31,Y,Y,665619980.000000,0.000000,0.000000
17414,DAT,DAT,2023-03-31,Q,N,10787990816.000000,0.000000,0.000000

In [33]:
cbs.check_cbs_421(df=df)

CHECK ITEM & SUB-ITEMS CBS_421

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_421,CBS_421A,CBS_421B
610,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
2118,LDW,LDW,2021-06-30,Q,Y,23135455232.000000,0.000000,23135454930.000000
2241,TNH,TNH,2021-06-30,Q,Y,272277913600.000000,222502211307.000000,49775700174.000000
2280,HSG,HSG,2021-06-30,Q,N,5136785604608.000000,1828407993863.000000,3308377450494.000000
7270,VEF,VEF,2021-06-30,Q,N,450858778624.000000,322304133059.000000,128554629924.000000
7434,SPD,SPD,2021-06-30,Q,N,-16133268480.000000,-16922778824.000000,789510257.000000
7681,PVA,PVA,2021-06-30,Q,N,-281138331648.000000,-281503387712.000000,365048883.000000
7720,VET,VET,2021-06-30,Q,N,45976064000.000000,0.000000,45976064269.000000
7763,VTX,VTX,2021-06-30,Q,N,18553483264.000000,10596165910.000000,7957317597.000000
8375,TNI,TNI,2022-09-30,Q,N,76049175956.000000,-10226150436.000000,86274205942.000000
14058,DFF,DFF,2021-03-31,Q,N,71994875904.000000,70629118587.000000,1365758301.000000
14130,LLM,LLM,2021-06-30,Q,N,229250842624.000000,215032820129.000000,14218027994.000000

In [34]:
cbs.check_cbs_430(df=df)

CHECK ITEM & SUB-ITEMS CBS_430

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_430,CBS_4301,CBS_431,CBS_432
610,VJC,VJC,2021-09-30,Q,Y,0.000000,0.000000,0.000000,NaN
796,HSV,HSV,2021-03-31,Q,N,0.000000,0.000000,NaN,NaN
2118,LDW,LDW,2021-06-30,Q,Y,308004159488.000000,0.000000,0.000000,308004168538.000000
7720,VET,VET,2021-06-30,Q,N,23069173760.000000,0.000000,21923549184.000000,1145625000.000000
11370,HPG,HPG,2022-09-30,Q,N,0.000000,NaN,0.000000,0.000000
11371,HPG,HPG,2022-09-30,Q,N,0.000000,NaN,0.000000,0.000000
13506,NVL,NVL,2021-03-31,Q,N,0.000000,0.000000,NaN,NaN