In [1]:
import pandas as pd
import numpy as np
import oracledb
import os
import platform
import sys
import tomli
import datetime as dt
from check_py import check_insurance_bs as ibs

pd.set_option('float_format', '{:f}'.format)

In [2]:
# Assign pathlink
path_link_db_algo = r"C:\Users\tungtt1\Desktop\bsc_config\config_algo.toml"

In [3]:
# Import files connfiq
with open(path_link_db_algo, mode="rb") as fp:
    config_acc = tomli.load(fp)

In [4]:
# Set up config for Oracle SQl Developer
host = config_acc["algo_acc"]["host"]
port = config_acc["algo_acc"]["port"]
service_name = config_acc["algo_acc"]["service_name"]
user = config_acc["algo_acc"]["user"]
password = config_acc["algo_acc"]["password"]

In [5]:
oracledb.init_oracle_client()

In [6]:
# Connect to database Oracle
conn = oracledb.connect(
    user=user,
    password=password,
    dsn=host+"/"+service_name
)

c = conn.cursor()

In [7]:
df = pd.read_sql_query(
    """ SELECT 
    * 
    FROM INSURANCE_BALANCE_SHEET
    WHERE LENGTH(SECURITY_CODE) = 3
    ORDER BY REPORT_DATE ASC, SECURITY_CODE ASC
    """, con=conn
)

C:\Users\tungtt1\AppData\Local\Temp\45\ipykernel_125132\239129382.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

In [8]:
# df = pd.read_excel(r"OneDrive_1_5-29-2023/insurance/algo_ibs.xlsx")

In [9]:
df

,SCN,REPORT_DATE,REPORTED_DATE,FREQ_CODE,SECURITY_CODE,AUDITED,MONTH_IN_PERIOD,IBS_100,IBS_110,IBS_111,...,IBS_4213,IBS_4214,IBS_4215,IBS_4216,IBS_4217,IBS_4218,IBS_4219,IBS_430,CREATED_DATE,UPDATED_DATE
0,125289,2018-03-31,None,Q,ABI,N,3,1729164214272.000000,372591165440.000000,60745883648.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1892936450048.000000,2021-06-27 04:54:32,2023-07-12 00:58:27.454757
1,125289,2018-03-31,None,Q,AIC,N,3,1075559727104.000000,82732261376.000000,82732261376.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1663821676544.000000,2021-06-27 04:54:32,2023-07-12 00:58:27.454757
2,125289,2018-03-31,None,Q,BIC,N,3,3645423222784.000000,112853295104.000000,112853295104.000000,...,0.000000,32129314191.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5018942963712.000000,2021-06-27 04:54:32,2023-07-12 00:58:27.454757
3,125289,2018-03-31,None,Q,BLI,N,3,1322212655104.000000,73758154752.000000,73758154752.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1707777327104.000000,2021-06-27 04:54:32,2023-07-12 00:58:27.454757
4,125289,2018-03-31,None,Q,BMI,N,3,4931058663424.000000,327148568576.000000,301603979264.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5692572303360.000000,2021-06-27 04:54:32,2023-07-12 00:58:27.454757
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,43650065,2023-06-30,None,Q,PGI,N,3,5806713416718.000000,117688763349.000000,117688763349.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7012188472946.000000,2023-07-26 16:53:37,2023-07-27 17:00:20.273501
335,43638183,2023-06-30,None,Q,PRE,N,3,5045420125947.000000,653696926554.000000,11253468637.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6273408668533.000000,2023-07-24 16:56:37,2023-07-24 20:10:00.596312
336,43687937,2023-06-30,None,Q,PTI,N,3,6019912355872.000000,63436950134.000000,63436950134.000000,...,0.000000,3858584035.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8831048935357.000000,2023-08-03 17:56:56,2023-08-07 00:57:54.399123
337,43626812,2023-06-30,None,Q,PVI,N,3,22001066707956.000000,1640749926408.000000,345306468491.000000,...,0.000000,272232846964.000000,0.000000,0.000000,0.000000,0.000000,0.000000,28393948875105.000000,2023-07-20 22:02:50,2023-07-21 17:00:21.883484
338,43662254,2023-06-30,None,Q,VNR,N,3,5606302322939.000000,79894918219.000000,32894918219.000000,...,0.000000,32540066591.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8004893938339.000000,2023-07-28 17:53:40,2023-07-31 17:00:22.572458

In [10]:
ibs.check_ibs_100(df=df)

CHECK ITEM & SUB-ITEMS IBS_100

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_100,IBS_110,IBS_120,IBS_130,IBS_140,IBS_150,IBS_190
0,ABI,2018-03-31,Q,N,1729164214272.000000,372591165440.000000,1059271999488.000000,103349428224.000000,3038469376.000000,134719135744.000000,56194023660.000000
1,AIC,2018-03-31,Q,N,1075559727104.000000,82732261376.000000,437305442304.000000,308813398016.000000,0.000000,18766313472.000000,227942297482.000000
2,BIC,2018-03-31,Q,N,3645423222784.000000,112853295104.000000,1836246761472.000000,472859410432.000000,482734432.000000,104727814144.000000,1118253139926.000000
3,BLI,2018-03-31,Q,N,1322212655104.000000,73758154752.000000,734189715456.000000,235188273152.000000,487610720.000000,79173984256.000000,199414933490.000000
4,BMI,2018-03-31,Q,N,4931058663424.000000,327148568576.000000,2200955256832.000000,1096628371456.000000,4748191744.000000,242023890944.000000,1059554628357.000000
5,BVH,2018-03-31,Q,N,55138525904896.000000,11230685167616.000000,34616939380736.000000,5932454510592.000000,154157629440.000000,608907165696.000000,2595382326646.000000
6,MIG,2018-03-31,Q,N,2342137626624.000000,17447958528.000000,1322969464832.000000,548723589120.000000,11970718720.000000,88473157632.000000,352552716879.000000
7,PGI,2018-03-31,Q,N,4251564113920.000000,125939113984.000000,2433602813952.000000,556073680896.000000,6413588480.000000,157758177280.000000,971776721160.000000
8,PTI,2018-03-31,Q,N,4722453905408.000000,115891560448.000000,2614741958656.000000,795744927744.000000,10361885696.000000,208703012864.000000,977010825579.000000
9,PVI,2018-03-31,Q,N,15626671226880.000000,909847232512.000000,7451914010624.000000,6995779780608.000000,11953507328.000000,257177108480.000000,0.000000
10,VNR,2018-03-31,Q,N,5196168560640.000000,70357712896.000000,2204285796352.000000,1197011763200.000000,59021268.000000,181932163072.000000,1542521718038.000000
11,ABI,2018-06-30,Q,Y,1741371867136.000000,302620409856.000000,1150617255936.000000,89610797056.000000,2886258176.000000,139211964416.000000,56425090763.000000
14,BLI,2018-06-30,Q,Y,1402565296128.000000,310079062016.000000,613919883264.000000,224943751168.000000,488550464.000000,50302164992.000000,202831835014.000000
15,BMI,2018-06-30,Q,Y,4816001040384.000000,309072592896.000000,2172371599360.000000,926751391744.000000,4692018688.000000,232544354304.000000,1170569200641.000000
18,PGI,2018-06-30,Q,Y,4515817848832.000000,138300440576.000000,2421966766080.000000,588021760000.000000,6763836928.000000,206796128256.000000,1153968718784.000000
20,PVI,2018-06-30,Q,Y,17535503171584.000000,1464900911104.000000,7093285814272.000000,8715096817664.000000,3856077312.000000,258363064320.000000,0.000000
21,VNR,2018-06-30,Q,Y,5129041346560.000000,77725745152.000000,1876795457536.000000,1293811843072.000000,68821264.000000,195280158720.000000,1685359351934.000000

In [11]:
ibs.check_ibs_110(df=df)

CHECK ITEM & SUB-ITEMS IBS_110

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_110,IBS_111,IBS_112
0,ABI,2018-03-31,Q,N,372591165440.000000,60745883648.000000,311845289984.000000
4,BMI,2018-03-31,Q,N,327148568576.000000,301603979264.000000,25544599552.000000
5,BVH,2018-03-31,Q,N,11230685167616.000000,10681711591424.000000,548974100480.000000
7,PGI,2018-03-31,Q,N,125939113984.000000,122189111296.000000,3750000128.000000
8,PTI,2018-03-31,Q,N,115891560448.000000,110966554624.000000,4925000192.000000
11,ABI,2018-06-30,Q,Y,302620409856.000000,70620397568.000000,231999995904.000000
14,BLI,2018-06-30,Q,Y,310079062016.000000,305079058432.000000,5000000000.000000
18,PGI,2018-06-30,Q,Y,138300440576.000000,134810443776.000000,3489999872.000000
234,HVB,2021-12-31,Y,Y,30643223316.000000,0.000000,0.000000

In [12]:
ibs.check_ibs_120(df=df)

CHECK ITEM & SUB-ITEMS IBS_120

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_120,IBS_121,IBS_129,IBS_1291
0,ABI,2018-03-31,Q,N,1059271999488.000000,0.000000,0.000000,1059272000000.000000
1,AIC,2018-03-31,Q,N,437305442304.000000,438668001280.000000,-1362551936.000000,0.000000
2,BIC,2018-03-31,Q,N,1836246761472.000000,136393400320.000000,-12922434560.000000,1712775755000.000000
3,BLI,2018-03-31,Q,N,734189715456.000000,745689513984.000000,-11499824128.000000,0.000000
4,BMI,2018-03-31,Q,N,2200955256832.000000,210753093632.000000,-43929182208.000000,2034131283333.000000
5,BVH,2018-03-31,Q,N,34616939380736.000000,2739455131648.000000,-303038529536.000000,32180523240105.000000
6,MIG,2018-03-31,Q,N,1322969464832.000000,324385636352.000000,-16416148480.000000,1015000000000.000000
7,PGI,2018-03-31,Q,N,2433602813952.000000,2449380474880.000000,-15777689600.000000,0.000000
8,PTI,2018-03-31,Q,N,2614741958656.000000,646438912000.000000,-32791285760.000000,2001094300000.000000
9,PVI,2018-03-31,Q,N,7451914010624.000000,1087654330368.000000,-39003770880.000000,6403263500000.000000
10,VNR,2018-03-31,Q,N,2204285796352.000000,173907024.000000,-173907024.000000,2204285866326.000000
11,ABI,2018-06-30,Q,Y,1150617255936.000000,0.000000,0.000000,1150617291700.000000
14,BLI,2018-06-30,Q,Y,613919883264.000000,92322865152.000000,-16934995968.000000,538532037321.000000
15,BMI,2018-06-30,Q,Y,2172371599360.000000,248131616768.000000,-66283470848.000000,1990523383333.000000
18,PGI,2018-06-30,Q,Y,2421966766080.000000,2442236002304.000000,-20269307904.000000,0.000000
20,PVI,2018-06-30,Q,Y,7093285814272.000000,466988138496.000000,-52245659648.000000,6678543500000.000000
21,VNR,2018-06-30,Q,Y,1876795457536.000000,173907024.000000,-173907024.000000,1876795409950.000000
234,HVB,2021-12-31,Y,Y,244351763465.000000,0.000000,0.000000,0.000000

In [13]:
ibs.check_ibs_130(df=df)

CHECK ITEM & SUB-ITEMS IBS_130

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_130,IBS_131,IBS_132,IBS_133,IBS_1351,IBS_1352,IBS_1353,IBS_1354,IBS_135,IBS_139
1,AIC,2018-03-31,Q,N,308813398016.000000,167267794944.000000,3255893760.000000,0.000000,0.000000,0.000000,0.000000,0.000000,175800893440.000000,-37511204864.000000
2,BIC,2018-03-31,Q,N,472859410432.000000,340085866496.000000,4520244736.000000,0.000000,0.000000,0.000000,0.000000,0.000000,145203281920.000000,-16949981184.000000
3,BLI,2018-03-31,Q,N,235188273152.000000,158314086400.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,87025229824.000000,-10151041024.000000
4,BMI,2018-03-31,Q,N,1096628371456.000000,937735159808.000000,4634100736.000000,0.000000,0.000000,0.000000,0.000000,0.000000,400493903872.000000,-246234775552.000000
5,BVH,2018-03-31,Q,N,5932454510592.000000,4251737915392.000000,33596641280.000000,0.000000,0.000000,1369872765390.000000,0.000000,0.000000,678070976512.000000,-400823451648.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,MIG,2022-03-31,Q,N,699605855536.000000,203150000694.000000,258563785156.000000,0.000000,NaN,0.000000,NaN,NaN,248381753995.000000,-10489684309.000000
255,PGI,2022-03-31,Q,N,456638036091.000000,478653720451.000000,12255678916.000000,0.000000,NaN,0.000000,NaN,NaN,42964712361.000000,-77236075637.000000
257,PTI,2022-03-31,Q,N,943784439444.000000,485398215610.000000,164521099968.000000,0.000000,NaN,6570000000.000000,NaN,NaN,399239322592.000000,-111944198726.000000
258,PVI,2022-03-31,Q,N,10961601287882.000000,10921074293988.000000,33094992279.000000,0.000000,NaN,0.000000,NaN,NaN,237716815550.000000,-230284813935.000000
259,VNR,2022-03-31,Q,N,876319976570.000000,722325655050.000000,199515550.000000,0.000000,NaN,0.000000,NaN,NaN,182132672179.000000,-28337866209.000000

In [14]:
ibs.check_ibs_131(df=df)

CHECK ITEM & SUB-ITEMS IBS_131

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_131,IBS_1311,IBS_1312
0,ABI,2018-03-31,Q,N,35651489792.000000,35651489137.000000,0.000000
1,AIC,2018-03-31,Q,N,167267794944.000000,96693311572.000000,70574486809.000000
2,BIC,2018-03-31,Q,N,340085866496.000000,338596281903.000000,1489572580.000000
3,BLI,2018-03-31,Q,N,158314086400.000000,158314079582.000000,0.000000
4,BMI,2018-03-31,Q,N,937735159808.000000,937735134859.000000,0.000000
5,BVH,2018-03-31,Q,N,4251737915392.000000,1733660844845.000000,2518076975921.000000
6,MIG,2018-03-31,Q,N,195685351424.000000,165384708969.000000,30300644357.000000
7,PGI,2018-03-31,Q,N,562163941376.000000,464529373181.000000,97634560069.000000
8,PTI,2018-03-31,Q,N,510334468096.000000,482004415433.000000,28330041076.000000
9,PVI,2018-03-31,Q,N,6789084479488.000000,0.000000,6789084305471.000000
10,VNR,2018-03-31,Q,N,1223477559296.000000,914133763003.000000,309343795929.000000
14,BLI,2018-06-30,Q,Y,170758946816.000000,170758945286.000000,0.000000
15,BMI,2018-06-30,Q,Y,850075516928.000000,850075548843.000000,0.000000
18,PGI,2018-06-30,Q,Y,591140618240.000000,491177941839.000000,99962676790.000000
20,PVI,2018-06-30,Q,Y,8543830278144.000000,0.000000,8543830202122.000000
21,VNR,2018-06-30,Q,Y,1316949065728.000000,958950115798.000000,357998940005.000000

In [15]:
ibs.check_ibs_140(df=df)

CHECK ITEM & SUB-ITEMS IBS_140

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_140,IBS_141,IBS_149
234,HVB,2021-12-31,Y,Y,129276900.000000,0.000000,0.000000

In [16]:
ibs.check_ibs_150(df=df)

CHECK ITEM & SUB-ITEMS IBS_150

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_150,IBS_151,IBS_152,IBS_154,IBS_157,IBS_158
1,AIC,2018-03-31,Q,N,18766313472.000000,18738544640.000000,27769416.000000,0.000000,0.000000,0.000000
3,BLI,2018-03-31,Q,N,79173984256.000000,41444986880.000000,7718706688.000000,1002135040.000000,0.000000,29008150528.000000
4,BMI,2018-03-31,Q,N,242023890944.000000,239880077312.000000,0.000000,2143802752.000000,0.000000,0.000000
5,BVH,2018-03-31,Q,N,608907165696.000000,569983893504.000000,31096733696.000000,0.000000,0.000000,7623619072.000000
6,MIG,2018-03-31,Q,N,88473157632.000000,73264881664.000000,10766047232.000000,4442227200.000000,0.000000,0.000000
7,PGI,2018-03-31,Q,N,157758177280.000000,157133750272.000000,624422272.000000,0.000000,0.000000,0.000000
8,PTI,2018-03-31,Q,N,208703012864.000000,197242765312.000000,8058405376.000000,3401843200.000000,0.000000,0.000000
9,PVI,2018-03-31,Q,N,257177108480.000000,167551434752.000000,78147190784.000000,11478481920.000000,0.000000,0.000000
10,VNR,2018-03-31,Q,N,181932163072.000000,181045018624.000000,887142848.000000,0.000000,0.000000,0.000000
14,BLI,2018-06-30,Q,Y,50302164992.000000,39705001984.000000,10526031872.000000,71129152.000000,0.000000,0.000000
15,BMI,2018-06-30,Q,Y,232544354304.000000,232154333184.000000,0.000000,390033888.000000,0.000000,0.000000
18,PGI,2018-06-30,Q,Y,206796128256.000000,205847199744.000000,948936000.000000,0.000000,0.000000,0.000000
20,PVI,2018-06-30,Q,Y,258363064320.000000,158882365440.000000,83140214784.000000,16340475904.000000,0.000000,0.000000
21,VNR,2018-06-30,Q,Y,195280158720.000000,194349776896.000000,930380864.000000,0.000000,0.000000,0.000000

In [17]:
ibs.check_ibs_190(df=df)

CHECK ITEM & SUB-ITEMS IBS_190

Empty DataFrame
Columns: [SECURITY_CODE, REPORT_DATE, FREQ_CODE, AUDITED, IBS_190, IBS_191, IBS_192]
Index: []

In [18]:
ibs.check_ibs_200(df=df)

CHECK ITEM & SUB-ITEMS IBS_200

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_200,IBS_210,IBS_220,IBS_240,IBS_250,IBS_260
0,ABI,2018-03-31,Q,N,163772235776.000000,6556203630.000000,125724188672.000000,0.000000,26000058368.000000,5491782144.000000
1,AIC,2018-03-31,Q,N,588274991104.000000,10342473938.000000,6929898496.000000,0.000000,569317392384.000000,1685219328.000000
2,BIC,2018-03-31,Q,N,1373519740928.000000,34003325302.000000,28601831424.000000,0.000000,1307138064384.000000,3776572928.000000
3,BLI,2018-03-31,Q,N,385564672000.000000,12000000000.000000,28533327872.000000,0.000000,331017486336.000000,14013829120.000000
4,BMI,2018-03-31,Q,N,761513705472.000000,12111562321.000000,398192607232.000000,72803000320.000000,255251169280.000000,23155394560.000000
...,...,...,...,...,...,...,...,...,...,...
330,BMI,2023-06-30,Q,N,749529851833.000000,16480825062.000000,251248650928.000000,153374527141.000000,251805924536.000000,41273381455.000000
331,BVH,2023-06-30,Q,N,89726114992420.000000,82805402088.000000,1820293193502.000000,45388992000.000000,87130037927510.000000,200167322213.000000
333,MIG,2023-06-30,Q,N,580380127408.000000,15890975968.000000,75099890139.000000,0.000000,119000000000.000000,17705511454.000000
336,PTI,2023-06-30,Q,N,2811136579485.000000,11027940669.000000,383445767476.000000,111607222015.000000,2226842388123.000000,18849185719.000000
338,VNR,2023-06-30,Q,N,2398591615400.000000,44506364382.000000,17446591131.000000,3681966540.000000,2307835983508.000000,9467896160.000000

In [19]:
ibs.check_ibs_210(df=df)

CHECK ITEM & SUB-ITEMS IBS_210

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_210,IBS_211,IBS_2111,IBS_212,IBS_213,IBS_2131,IBS_218,IBS_2183
113,PTI,2019-12-31,Y,Y,83259389178.000000,250000000.000000,250000000.000000,0.000000,0.000000,0.000000,83009389178.000000,0.000000
156,PVI,2020-09-30,Q,N,24091225283.000000,0.000000,NaN,0.000000,0.000000,NaN,24091225283.000000,0.000000
169,BVH,2020-12-31,Y,Y,70801065457.000000,0.000000,NaN,0.000000,0.000000,NaN,70801065457.000000,0.000000
180,PVI,2020-12-31,Q,N,24194552153.000000,0.000000,NaN,0.000000,0.000000,NaN,24194552153.000000,0.000000
190,HVB,2021-03-31,Q,N,6734482240.000000,0.000000,NaN,0.000000,0.000000,NaN,6734482240.000000,0.000000
196,PVI,2021-03-31,Q,N,24138871488.000000,0.000000,NaN,0.000000,0.000000,NaN,24138871488.000000,0.000000
202,BMI,2021-06-30,Q,Y,14969034949.000000,0.000000,NaN,0.000000,0.000000,NaN,14969034949.000000,0.000000
204,MIG,2021-06-30,Q,Y,15471801165.000000,0.000000,NaN,0.000000,0.000000,NaN,15471801165.000000,0.000000
205,PGI,2021-06-30,Q,Y,13166115541.000000,0.000000,NaN,0.000000,0.000000,NaN,13166115541.000000,0.000000
210,ABI,2021-09-30,Q,N,7812039046.000000,0.000000,NaN,0.000000,0.000000,NaN,7812039046.000000,0.000000
211,AIC,2021-09-30,Q,N,12919680319.000000,0.000000,NaN,0.000000,0.000000,NaN,12919680319.000000,0.000000
212,BIC,2021-09-30,Q,N,31981607668.000000,0.000000,NaN,0.000000,0.000000,NaN,31981607668.000000,0.000000
213,BLI,2021-09-30,Q,N,13054532733.000000,0.000000,NaN,0.000000,0.000000,NaN,13054532733.000000,0.000000
214,BMI,2021-09-30,Q,N,14810120181.000000,0.000000,NaN,0.000000,0.000000,NaN,14810120181.000000,0.000000
215,BVH,2021-09-30,Q,Y,68587523597.000000,0.000000,NaN,0.000000,0.000000,NaN,68587523597.000000,0.000000
216,MIG,2021-09-30,Q,N,15866609265.000000,0.000000,NaN,0.000000,0.000000,NaN,15866609265.000000,0.000000
217,PGI,2021-09-30,Q,N,13434377833.000000,0.000000,NaN,0.000000,0.000000,NaN,13434377833.000000,0.000000
218,PRE,2021-09-30,Q,N,8000000000.000000,0.000000,NaN,0.000000,0.000000,NaN,8000000000.000000,0.000000
219,PTI,2021-09-30,Q,N,34830300656.000000,0.000000,NaN,0.000000,0.000000,NaN,57879326768.000000,-23049026112.000000
220,PVI,2021-09-30,Q,N,24040238352.000000,0.000000,NaN,0.000000,0.000000,NaN,24040238352.000000,0.000000
221,VNR,2021-09-30,Q,N,25428657534.000000,0.000000,NaN,0.000000,0.000000,NaN,25428657534.000000,0.000000
222,ABI,2021-12-31,Y,Y,7726416513.000000,0.000000,NaN,0.000000,0.000000,NaN,7726416513.000000,0.000000
223,ABI,2021-12-31,Q,N,7726416513.000000,0.000000,NaN,0.000000,0.000000,NaN,7726416513.000000,0.000000
224,AIC,2021-12-31,Y,Y,13140842819.000000,0.000000,NaN,0.000000,0.000000,NaN,13140842819.000000,0.000000
225,AIC,2021-12-31,Q,N,13140842819.000000,0.000000,NaN,0.000000,0.000000,NaN,13140842819.000000,0.000000
226,BIC,2021-12-31,Q,N,31613172791.000000,0.000000,NaN,0.000000,0.000000,NaN,31613172791.000000,0.000000
227,BIC,2021-12-31,Y,Y,31613172791.000000,0.000000,NaN,0.000000,0.000000,NaN,31613172791.000000,0.000000
228,BLI,2021-12-31,Q,N,13068224306.000000,0.000000,NaN,0.000000,0.000000,NaN,13068224306.000000,0.000000
229,BLI,2021-12-31,Y,Y,13068224306.000000,0.000000,NaN,0.000000,0.000000,NaN,13068224306.000000,0.000000
230,BMI,2021-12-31,Q,N,14799951039.000000,0.000000,NaN,0.000000,0.000000,NaN,14799951039.000000,0.000000
231,BMI,2021-12-31,Y,Y,14979929121.000000,0.000000,NaN,0.000000,0.000000,NaN,14979929121.000000,0.000000
232,BVH,2021-12-31,Q,N,73349498240.000000,0.000000,NaN,0.000000,0.000000,NaN,73349498240.000000,0.000000
234,HVB,2021-12-31,Y,Y,6766265630.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
235,MIG,2021-12-31,Y,Y,16215822606.000000,0.000000,NaN,0.000000,0.000000,NaN,16215822606.000000,0.000000
236,MIG,2021-12-31,Q,N,16215822606.000000,0.000000,NaN,0.000000,0.000000,NaN,16215822606.000000,0.000000
237,PGI,2021-12-31,Q,N,13447768228.000000,0.000000,NaN,0.000000,0.000000,NaN,13447768228.000000,0.000000
239,PRE,2021-12-31,Q,N,8000000000.000000,0.000000,NaN,0.000000,0.000000,NaN,8000000000.000000,0.000000
240,PRE,2021-12-31,Y,Y,8000000000.000000,0.000000,NaN,0.000000,0.000000,NaN,8000000000.000000,0.000000
241,PTI,2021-12-31,Y,Y,18089886286.000000,0.000000,NaN,0.000000,0.000000,NaN,18089886286.000000,0.000000
242,PTI,2021-12-31,Q,N,35680233508.000000,0.000000,NaN,0.000000,0.000000,NaN,58729259620.000000,-23049026112.000000
243,PVI,2021-12-31,Y,Y,24477830206.000000,0.000000,NaN,0.000000,0.000000,NaN,24477830206.000000,0.000000
244,PVI,2021-12-31,Q,N,24477830206.000000,0.000000,NaN,0.000000,0.000000,NaN,24477830206.000000,0.000000
245,VNR,2021-12-31,Q,N,25936008219.000000,0.000000,NaN,0.000000,0.000000,NaN,25936008219.000000,0.000000
246,VNR,2021-12-31,Y,Y,25936008219.000000,0.000000,NaN,0.000000,0.000000,NaN,25936008219.000000,0.000000
247,ABI,2022-03-31,Q,N,7691605300.000000,0.000000,NaN,0.000000,0.000000,NaN,7691605300.000000,0.000000
248,AIC,2022-03-31,Q,N,13084184049.000000,0.000000,NaN,0.000000,0.000000,NaN,13084184049.000000,0.000000
249,BIC,2022-03-31,Q,N,30034499756.000000,0.000000,NaN,0.000000,0.000000,NaN,30034499756.000000,0.000000
250,BLI,2022-03-31,Q,N,12313103167.000000,0.000000,NaN,0.000000,0.000000,NaN,12313103167.000000,0.000000
251,BMI,2022-03-31,Q,N,16045055479.000000,0.000000,NaN,0.000000,0.000000,NaN,16045055479.000000,0.000000
254,MIG,2022-03-31,Q,N,16148022606.000000,0.000000,NaN,0.000000,0.000000,NaN,16148022606.000000,0.000000
255,PGI,2022-03-31,Q,N,13396123542.000000,0.000000,NaN,0.000000,0.000000,NaN,13396123542.000000,0.000000
257,PTI,2022-03-31,Q,N,17740456344.000000,0.000000,NaN,0.000000,0.000000,NaN,17740456344.000000,0.000000
258,PVI,2022-03-31,Q,N,24464349369.000000,0.000000,NaN,0.000000,0.000000,NaN,24464349369.000000,0.000000
259,VNR,2022-03-31,Q,N,22000000000.000000,0.000000,NaN,0.000000,0.000000,NaN,22000000000.000000,0.000000
319,IFA,2023-03-31,Q,N,61621034488.000000,84648685636.000000,84648685636.000000,0.000000,0.000000,0.000000,61621034488.000000,-84648685636.000000
332,IFA,2023-06-30,Q,N,61617278248.000000,84648685636.000000,84648685636.000000,0.000000,0.000000,0.000000,61617278248.000000,-84648685636.000000

In [20]:
ibs.check_ibs_218(df=df)

CHECK ITEM & SUB-ITEMS IBS_218

Empty DataFrame
Columns: [SECURITY_CODE, REPORT_DATE, FREQ_CODE, AUDITED, IBS_218, IBS_2181, IBS_2182]
Index: []

In [21]:
# Check these fields
ibs.check_ibs_220(df=df)

CHECK ITEM & SUB-ITEMS IBS_220

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_220,IBS_221,IBS_224,IBS_227,IBS_230
0,ABI,2018-03-31,Q,N,125724188672.000000,64692195328.000000,0.000000,61031997440.000000,0.000000
1,AIC,2018-03-31,Q,N,6929898496.000000,6481731584.000000,0.000000,448166560.000000,0.000000
2,BIC,2018-03-31,Q,N,28601831424.000000,21991030784.000000,0.000000,6610802176.000000,0.000000
3,BLI,2018-03-31,Q,N,28533327872.000000,17104196608.000000,0.000000,9766098944.000000,0.000000
4,BMI,2018-03-31,Q,N,398192607232.000000,103489585152.000000,0.000000,286437769216.000000,0.000000
...,...,...,...,...,...,...,...,...,...
332,IFA,2023-06-30,Q,N,382731535032.000000,231619841782.000000,0.000000,142216915730.000000,0.000000
333,MIG,2023-06-30,Q,N,75099890139.000000,49370062833.000000,0.000000,25729827306.000000,352683749847.000000
334,PGI,2023-06-30,Q,N,635532031516.000000,365812888519.000000,0.000000,256144080229.000000,0.000000
336,PTI,2023-06-30,Q,N,383445767476.000000,358674334095.000000,0.000000,24771433381.000000,59364075483.000000
338,VNR,2023-06-30,Q,N,17446591131.000000,8881981900.000000,0.000000,8564609231.000000,1616690000.000000

In [22]:
ibs.check_ibs_221(df=df)

CHECK ITEM & SUB-ITEMS IBS_221

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_221,IBS_222,IBS_223
1,AIC,2018-03-31,Q,N,6481731584.000000,22519136256.000000,-16037405696.000000
2,BIC,2018-03-31,Q,N,21991030784.000000,74231930880.000000,-52240896000.000000
3,BLI,2018-03-31,Q,N,17104196608.000000,38905503744.000000,-21801306112.000000
7,PGI,2018-03-31,Q,N,240018948096.000000,406433660928.000000,-166414729216.000000
8,PTI,2018-03-31,Q,N,75017183232.000000,166984499200.000000,-91967307776.000000
9,PVI,2018-03-31,Q,N,186322714624.000000,363548999680.000000,-177226268672.000000
10,VNR,2018-03-31,Q,N,4916164096.000000,25150906368.000000,-20234743808.000000
14,BLI,2018-06-30,Q,Y,16237201408.000000,36818731008.000000,-20581527552.000000
15,BMI,2018-06-30,Q,Y,102254911488.000000,234079469568.000000,-131824549888.000000
18,PGI,2018-06-30,Q,Y,236981026816.000000,409547407360.000000,-172566364160.000000
21,VNR,2018-06-30,Q,Y,4912239104.000000,25341263872.000000,-20429025280.000000
234,HVB,2021-12-31,Y,Y,2292719620.000000,0.000000,0.000000

In [23]:
ibs.check_ibs_224(df=df)

CHECK ITEM & SUB-ITEMS IBS_224

Empty DataFrame
Columns: [SECURITY_CODE, REPORT_DATE, FREQ_CODE, AUDITED, IBS_224, IBS_225, IBS_226]
Index: []

In [24]:
ibs.check_ibs_227(df=df)

CHECK ITEM & SUB-ITEMS IBS_227

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_227,IBS_228,IBS_229
0,ABI,2018-03-31,Q,N,61031997440.000000,65448742912.000000,-4416749568.000000
1,AIC,2018-03-31,Q,N,448166560.000000,1750349952.000000,-1302183424.000000
2,BIC,2018-03-31,Q,N,6610802176.000000,6886006272.000000,-275204384.000000
4,BMI,2018-03-31,Q,N,286437769216.000000,360364900352.000000,-73927147520.000000
5,BVH,2018-03-31,Q,N,802202779648.000000,1152131661824.000000,-349928947712.000000
6,MIG,2018-03-31,Q,N,17086489600.000000,19058534400.000000,-1972043776.000000
7,PGI,2018-03-31,Q,N,151605067776.000000,182927802368.000000,-31322748928.000000
8,PTI,2018-03-31,Q,N,9336837120.000000,15741792256.000000,-6404955648.000000
10,VNR,2018-03-31,Q,N,707229056.000000,32480196608.000000,-31772966912.000000
11,ABI,2018-06-30,Q,Y,60824539136.000000,65448742912.000000,-4624205312.000000
15,BMI,2018-06-30,Q,Y,285190488064.000000,359922892800.000000,-74732412928.000000
18,PGI,2018-06-30,Q,Y,158555947008.000000,191062622208.000000,-32506673152.000000
21,VNR,2018-06-30,Q,Y,82637096.000000,32434196480.000000,-32351559680.000000
234,HVB,2021-12-31,Y,Y,98285665.000000,0.000000,0.000000

In [25]:
ibs.check_ibs_240(df=df)

CHECK ITEM & SUB-ITEMS IBS_240

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_240,IBS_241,IBS_242
4,BMI,2018-03-31,Q,N,72803000320.000000,85439021056.000000,-12636022784.000000
7,PGI,2018-03-31,Q,N,83623821312.000000,96057876480.000000,-12434051072.000000
8,PTI,2018-03-31,Q,N,115147931648.000000,121055363072.000000,-5907437568.000000
9,PVI,2018-03-31,Q,N,1491465142272.000000,1621298905088.000000,-129833787392.000000
18,PGI,2018-06-30,Q,Y,83097878528.000000,96057876480.000000,-12959991808.000000
20,PVI,2018-06-30,Q,Y,1482972463104.000000,1621298905088.000000,-138326376448.000000

In [26]:
ibs.check_ibs_2421(df=df)

CHECK ITEM & SUB-ITEMS IBS_2421

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_2421,IBS_2422,IBS_2423
3,BLI,2018-03-31,Q,N,0.000000,0.000000,1663030819.000000
4,BMI,2018-03-31,Q,N,0.000000,0.000000,8265261012.000000
7,PGI,2018-03-31,Q,N,0.000000,0.000000,29048169062.000000
14,BLI,2018-06-30,Q,Y,0.000000,0.000000,2883971244.000000
15,BMI,2018-06-30,Q,Y,0.000000,0.000000,2984452673.000000
18,PGI,2018-06-30,Q,Y,0.000000,0.000000,22395573855.000000

In [27]:
ibs.check_ibs_250(df=df)

CHECK ITEM & SUB-ITEMS IBS_250

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_250,IBS_251,IBS_252,IBS_258,IBS_259,IBS_2591
0,ABI,2018-03-31,Q,N,26000058368.000000,0.000000,0.000000,0.000000,0.000000,26000058302.000000
1,AIC,2018-03-31,Q,N,569317392384.000000,0.000000,55550001152.000000,513767374848.000000,0.000000,0.000000
2,BIC,2018-03-31,Q,N,1307138064384.000000,0.000000,0.000000,75907366912.000000,-40776224768.000000,1272006918034.000000
3,BLI,2018-03-31,Q,N,331017486336.000000,0.000000,0.000000,332520488960.000000,-1503000064.000000,0.000000
4,BMI,2018-03-31,Q,N,255251169280.000000,0.000000,145350000640.000000,55901167616.000000,0.000000,54000000000.000000
5,BVH,2018-03-31,Q,N,41601824980992.000000,0.000000,2898313084928.000000,367843377152.000000,-32457601024.000000,38368128180362.000000
6,MIG,2018-03-31,Q,N,380000010240.000000,0.000000,0.000000,380006989824.000000,-7005000.000000,0.000000
7,PGI,2018-03-31,Q,N,224284491776.000000,0.000000,1350000000.000000,235923898368.000000,-12989419520.000000,0.000000
8,PTI,2018-03-31,Q,N,759241703424.000000,0.000000,128940638208.000000,120625815552.000000,-82355920896.000000,592031169809.000000
9,PVI,2018-03-31,Q,N,751738159104.000000,0.000000,0.000000,171465261056.000000,-79727099904.000000,660000000000.000000
10,VNR,2018-03-31,Q,N,1113112838144.000000,0.000000,239180398592.000000,470445064192.000000,-2870435328.000000,406357780116.000000
11,ABI,2018-06-30,Q,Y,69000060928.000000,0.000000,0.000000,0.000000,0.000000,69000058302.000000
14,BLI,2018-06-30,Q,Y,240057532416.000000,0.000000,0.000000,0.000000,-1503000064.000000,241560534246.000000
15,BMI,2018-06-30,Q,Y,301965312000.000000,0.000000,145350000640.000000,57615298560.000000,0.000000,99000000000.000000
18,PGI,2018-06-30,Q,Y,222979489792.000000,0.000000,1350000000.000000,235923898368.000000,-14294420480.000000,0.000000
20,PVI,2018-06-30,Q,Y,606509727744.000000,0.000000,0.000000,171465261056.000000,-84955553792.000000,520000000000.000000
21,VNR,2018-06-30,Q,Y,1454386839552.000000,0.000000,236579389440.000000,470445064192.000000,-3527687168.000000,750890036788.000000
234,HVB,2021-12-31,Y,Y,77302200000.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [28]:
ibs.check_ibs_270(df=df)

CHECK ITEM & SUB-ITEMS IBS_270

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_270,IBS_100,IBS_200
1,AIC,2018-03-31,Q,N,1663834652672.000000,1075559727104.000000,588274991104.000000
4,BMI,2018-03-31,Q,N,5692572303360.000000,4931058663424.000000,761513705472.000000
6,MIG,2018-03-31,Q,N,3187527385088.000000,2342137626624.000000,845389889536.000000
7,PGI,2018-03-31,Q,N,5000720285696.000000,4251564113920.000000,749156302848.000000
8,PTI,2018-03-31,Q,N,5746609094656.000000,4722453905408.000000,1024155123712.000000
9,PVI,2018-03-31,Q,N,19974598950912.000000,15626671226880.000000,4347927461888.000000
10,VNR,2018-03-31,Q,N,6429548216320.000000,5196168560640.000000,1233380179968.000000
11,ABI,2018-06-30,Q,Y,1950595809280.000000,1741371867136.000000,209223958528.000000
14,BLI,2018-06-30,Q,Y,1701848416256.000000,1402565296128.000000,299283185664.000000
15,BMI,2018-06-30,Q,Y,5602683125760.000000,4816001040384.000000,786681823232.000000
18,PGI,2018-06-30,Q,Y,5261001490432.000000,4515817848832.000000,745183838208.000000
20,PVI,2018-06-30,Q,Y,21756544811008.000000,17535503171584.000000,4221042688000.000000
21,VNR,2018-06-30,Q,Y,6728970141696.000000,5129041346560.000000,1599929057280.000000

In [29]:
ibs.check_ibs_300(df=df)

CHECK ITEM & SUB-ITEMS IBS_300

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_300,IBS_310,IBS_330
1,AIC,2018-03-31,Q,N,843383242752.000000,843280285696.000000,102895216.000000
2,BIC,2018-03-31,Q,N,2866273583104.000000,2864611328000.000000,1662235520.000000
3,BLI,2018-03-31,Q,N,1042140889088.000000,1037535150080.000000,4605728256.000000
4,BMI,2018-03-31,Q,N,3495161757696.000000,3495005782016.000000,155868736.000000
5,BVH,2018-03-31,Q,N,84420241391616.000000,25506263072768.000000,154105118720.000000
6,MIG,2018-03-31,Q,N,2285237174272.000000,2246395559936.000000,38841765888.000000
7,PGI,2018-03-31,Q,N,3604296499200.000000,3585956380672.000000,18340149248.000000
8,PTI,2018-03-31,Q,N,3813958221824.000000,3808075972608.000000,5882318848.000000
9,PVI,2018-03-31,Q,N,12713236365312.000000,12640393887744.000000,72842698752.000000
10,VNR,2018-03-31,Q,N,3645910548480.000000,3641087361024.000000,4823152128.000000
14,BLI,2018-06-30,Q,Y,1032488026112.000000,1029650841600.000000,2837188608.000000
15,BMI,2018-06-30,Q,Y,3380506001408.000000,3380325122048.000000,180868736.000000
16,BVH,2018-06-30,Q,Y,84639359401021.000000,20814126897009.000000,456892074210.000000
18,PGI,2018-06-30,Q,Y,3838558863360.000000,3806191943680.000000,32367020032.000000
20,PVI,2018-06-30,Q,Y,15065396805632.000000,14980052156416.000000,85344059392.000000
21,VNR,2018-06-30,Q,Y,3902453055488.000000,3897630130176.000000,4823152128.000000
27,BVH,2018-09-30,Q,N,85691040529592.000000,17806093209554.000000,606813367295.000000
43,BVH,2018-12-31,Q,N,98333430677236.000000,26361339731216.000000,638062711632.000000
44,BVH,2018-12-31,Y,Y,97698783565332.000000,25799328881234.000000,639218477238.000000
63,BVH,2019-03-31,Q,Y,100621481134980.000000,25565837522128.000000,644388606771.000000
75,BVH,2019-06-30,Q,Y,104871397612895.000000,25858745316509.000000,673835611287.000000
87,BVH,2019-09-30,Q,Y,105436914315142.000000,22189499702077.000000,734749585489.000000
104,BVH,2019-12-31,Q,N,108449824880444.000000,20772946980632.000000,854199504053.000000
105,BVH,2019-12-31,Y,Y,108335629665873.000000,20707174565073.000000,855860939229.000000
124,BVH,2020-03-31,Q,N,113413800601996.000000,22334214073228.000000,851907198805.000000
137,BVH,2020-06-30,Q,Y,117349687504109.000000,21980234137888.000000,577198476100.000000
150,BVH,2020-09-30,Q,N,124041611621122.000000,23565411425707.000000,554884299987.000000
168,BVH,2020-12-31,Q,N,126514550906586.000000,20680648643849.000000,567433558003.000000
189,BVH,2021-03-31,Q,N,125336258582216.000000,14723850536982.000000,560272140692.000000
203,BVH,2021-06-30,Q,Y,127366871444479.000000,12104193267388.000000,581697711422.000000

In [30]:
ibs.check_ibs_310(df=df)

CHECK ITEM & SUB-ITEMS IBS_310

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_310,IBS_311,IBS_312,IBS_313,IBS_314,IBS_315,...,IBS_317,IBS_3171,IBS_3172,IBS_3191,IBS_319,IBS_320,IBS_323,IBS_3231,IBS_327,IBS_329
0,ABI,2018-03-31,Q,N,1192792293376.000000,0.000000,82503704576.000000,0.000000,9830235136.000000,37247406080.000000,...,0.000000,0.000000,4281748609.000000,8317836788.000000,12494674944.000000,0.000000,31293419520.000000,0.000000,0.000000,1006823250397.000000
1,AIC,2018-03-31,Q,N,843280285696.000000,0.000000,140940492800.000000,7355121152.000000,10566885376.000000,8219406336.000000,...,0.000000,0.000000,0.000000,27537543818.000000,8780108800.000000,0.000000,23219806.000000,0.000000,0.000000,639857538697.000000
2,BIC,2018-03-31,Q,N,2864611328000.000000,0.000000,373627486208.000000,12700597248.000000,32440156160.000000,26853365760.000000,...,0.000000,0.000000,5278998066.000000,73251405481.000000,23783288832.000000,3072343309.000000,1518014848.000000,0.000000,0.000000,2261914316939.000000
3,BLI,2018-03-31,Q,N,1037535150080.000000,0.000000,130446336000.000000,0.000000,13499670528.000000,10449328128.000000,...,0.000000,0.000000,0.000000,32911080421.000000,35067392000.000000,0.000000,0.000000,0.000000,0.000000,814029399424.000000
4,BMI,2018-03-31,Q,N,3495005782016.000000,0.000000,758867755008.000000,0.000000,56009355264.000000,167496663040.000000,...,0.000000,0.000000,5949133691.000000,78320002107.000000,107125956608.000000,0.000000,5756604928.000000,0.000000,0.000000,2315480281889.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,PGI,2023-06-30,Q,N,5193848183680.000000,225586924336.000000,462383484178.000000,0.000000,51155108154.000000,158449108820.000000,...,0.000000,0.000000,0.000000,131430817621.000000,30729013710.000000,0.000000,135332613202.000000,0.000000,0.000000,0.000000
335,PRE,2023-06-30,Q,N,5320400134612.000000,265702656167.000000,626702706940.000000,0.000000,9675186435.000000,6013491445.000000,...,0.000000,0.000000,0.000000,118145939073.000000,656088165731.000000,0.000000,6984979182.000000,0.000000,0.000000,0.000000
336,PTI,2023-06-30,Q,N,6902392950208.000000,409760000000.000000,572365310920.000000,9646006030.000000,21649913328.000000,167512767428.000000,...,0.000000,0.000000,165072707758.000000,266877532581.000000,174284861478.000000,0.000000,43513466.000000,0.000000,0.000000,0.000000
337,PVI,2023-06-30,Q,N,19838682743208.000000,819207576758.000000,3165646744864.000000,422000091536.000000,142464014739.000000,233998282279.000000,...,0.000000,0.000000,30440244856.000000,0.000000,110545079168.000000,0.000000,37777490220.000000,0.000000,0.000000,0.000000
338,VNR,2023-06-30,Q,N,4389112406617.000000,0.000000,803184097612.000000,159615170.000000,27403744429.000000,43774494650.000000,...,0.000000,0.000000,0.000000,136071011982.000000,210634711108.000000,28102514160.000000,34028659109.000000,0.000000,0.000000,0.000000

In [31]:
ibs.check_ibs_312(df=df)

CHECK ITEM & SUB-ITEMS IBS_312

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_312,IBS_3121,IBS_3122
0,ABI,2018-03-31,Q,N,82503704576.000000,79613444071.000000,2890260479.000000
1,AIC,2018-03-31,Q,N,140940492800.000000,135478395144.000000,5462096790.000000
2,BIC,2018-03-31,Q,N,373627486208.000000,373321836183.000000,305634276.000000
3,BLI,2018-03-31,Q,N,130446336000.000000,130446338222.000000,0.000000
4,BMI,2018-03-31,Q,N,758867755008.000000,758867753294.000000,0.000000
5,BVH,2018-03-31,Q,N,2083017588736.000000,1970604256832.000000,112413332519.000000
6,MIG,2018-03-31,Q,N,206165508096.000000,197030027259.000000,9135484017.000000
7,PGI,2018-03-31,Q,N,316696100864.000000,303339321824.000000,13356773097.000000
8,PTI,2018-03-31,Q,N,498582224896.000000,468730590357.000000,29851632799.000000
9,PVI,2018-03-31,Q,N,2041102204928.000000,0.000000,2041102257601.000000
10,VNR,2018-03-31,Q,N,1009723441152.000000,808841672105.000000,200881746723.000000
11,ABI,2018-06-30,Q,Y,78173782016.000000,76572814607.000000,1600966508.000000
14,BLI,2018-06-30,Q,Y,158853726208.000000,158853725927.000000,0.000000
15,BMI,2018-06-30,Q,Y,636933570560.000000,636933550905.000000,0.000000
18,PGI,2018-06-30,Q,Y,329684025344.000000,298422895860.000000,31261140548.000000
20,PVI,2018-06-30,Q,Y,2243381166080.000000,0.000000,2243381221120.000000
21,VNR,2018-06-30,Q,Y,1044828848128.000000,832744881584.000000,212083974375.000000

In [32]:
ibs.check_ibs_3281(df=df)

CHECK ITEM & SUB-ITEMS IBS_3281

    SECURITY_CODE REPORT_DATE FREQ_CODE AUDITED  IBS_3281  IBS_3282  IBS_3283
156           PVI  2020-09-30         Q       N       NaN       NaN       NaN
169           BVH  2020-12-31         Y       Y       NaN       NaN       NaN
180           PVI  2020-12-31         Q       N       NaN       NaN       NaN
190           HVB  2021-03-31         Q       N       NaN       NaN       NaN
196           PVI  2021-03-31         Q       N       NaN       NaN       NaN
202           BMI  2021-06-30         Q       Y       NaN       NaN       NaN
204           MIG  2021-06-30         Q       Y       NaN       NaN       NaN
205           PGI  2021-06-30         Q       Y       NaN       NaN       NaN
210           ABI  2021-09-30         Q       N       NaN       NaN       NaN
211           AIC  2021-09-30         Q       N       NaN       NaN       NaN
212           BIC  2021-09-30         Q       N       NaN       NaN       NaN
213           BLI  2021-09-30         Q       N       NaN       NaN       NaN
214           BMI  2021-09-30         Q       N       NaN       NaN       NaN
215           BVH  2021-09-30         Q       Y       NaN       NaN       NaN
216           MIG  2021-09-30         Q       N       NaN       NaN       NaN
217           PGI  2021-09-30         Q       N       NaN       NaN       NaN
218           PRE  2021-09-30         Q       N       NaN       NaN       NaN
219           PTI  2021-09-30         Q       N       NaN       NaN       NaN
220           PVI  2021-09-30         Q       N       NaN       NaN       NaN
221           VNR  2021-09-30         Q       N       NaN       NaN       NaN
222           ABI  2021-12-31         Y       Y       NaN       NaN       NaN
223           ABI  2021-12-31         Q       N       NaN       NaN       NaN
224           AIC  2021-12-31         Y       Y       NaN       NaN       NaN
225           AIC  2021-12-31         Q       N       NaN       NaN       NaN
226           BIC  2021-12-31         Q       N       NaN       NaN       NaN
227           BIC  2021-12-31         Y       Y       NaN       NaN       NaN
228           BLI  2021-12-31         Q       N       NaN       NaN       NaN
229           BLI  2021-12-31         Y       Y       NaN       NaN       NaN
230           BMI  2021-12-31         Q       N       NaN       NaN       NaN
231           BMI  2021-12-31         Y       Y       NaN       NaN       NaN
232           BVH  2021-12-31         Q       N       NaN       NaN       NaN
235           MIG  2021-12-31         Y       Y       NaN       NaN       NaN
236           MIG  2021-12-31         Q       N       NaN       NaN       NaN
237           PGI  2021-12-31         Q       N       NaN       NaN       NaN
239           PRE  2021-12-31         Q       N       NaN       NaN       NaN
240           PRE  2021-12-31         Y       Y       NaN       NaN       NaN
241           PTI  2021-12-31         Y       Y       NaN       NaN       NaN
242           PTI  2021-12-31         Q       N       NaN       NaN       NaN
243           PVI  2021-12-31         Y       Y       NaN       NaN       NaN
244           PVI  2021-12-31         Q       N       NaN       NaN       NaN
245           VNR  2021-12-31         Q       N       NaN       NaN       NaN
246           VNR  2021-12-31         Y       Y       NaN       NaN       NaN
247           ABI  2022-03-31         Q       N       NaN       NaN       NaN
248           AIC  2022-03-31         Q       N       NaN       NaN       NaN
249           BIC  2022-03-31         Q       N       NaN       NaN       NaN
250           BLI  2022-03-31         Q       N       NaN       NaN       NaN
251           BMI  2022-03-31         Q       N       NaN       NaN       NaN
254           MIG  2022-03-31         Q       N       NaN       NaN       NaN
255           PGI  2022-03-31         Q       N       NaN       NaN       NaN
257           PTI  2022-03-31         Q       N       NaN       NaN       NaN
258           PVI  2022-03-31         Q       N       NaN       NaN       NaN
259           VNR  2022-03-31         Q       N       NaN       NaN       NaN

In [33]:
ibs.check_ibs_329(df=df)

CHECK ITEM & SUB-ITEMS IBS_329

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_329,IBS_3291,IBS_3294,IBS_3292,IBS_3293,IBS_3295,IBS_3296
156,PVI,2020-09-30,Q,N,11255789090278.000000,3830567140932.000000,NaN,7124602176149.000000,300619773197.000000,NaN,NaN
180,PVI,2020-12-31,Q,N,10592051884760.000000,3555979662687.000000,NaN,6750942691094.000000,285129530979.000000,NaN,NaN
190,HVB,2021-03-31,Q,N,92487922605.000000,52136482443.000000,NaN,27210027996.000000,13141412166.000000,NaN,NaN
196,PVI,2021-03-31,Q,N,11135886629137.000000,4416883362008.000000,NaN,6401851539124.000000,317151728005.000000,NaN,NaN
202,BMI,2021-06-30,Q,Y,2789478024428.000000,1448095196467.000000,NaN,1195749889524.000000,145632938437.000000,NaN,NaN
204,MIG,2021-06-30,Q,Y,2639899924775.000000,1801193609144.000000,NaN,690054684872.000000,148651630759.000000,NaN,NaN
205,PGI,2021-06-30,Q,Y,4037040342710.000000,1908123052296.000000,NaN,1792540592348.000000,336376698066.000000,NaN,NaN
210,ABI,2021-09-30,Q,N,1684997904202.000000,1223357808573.000000,NaN,325755850218.000000,135884245411.000000,NaN,NaN
211,AIC,2021-09-30,Q,N,1606795967710.000000,1052254567992.000000,NaN,475959754753.000000,78581644965.000000,NaN,NaN
212,BIC,2021-09-30,Q,N,2866425291235.000000,1526673942823.000000,NaN,1175087582599.000000,164663765813.000000,NaN,NaN
213,BLI,2021-09-30,Q,N,936429460490.000000,553130659231.000000,NaN,303662551387.000000,79636249872.000000,NaN,NaN
214,BMI,2021-09-30,Q,N,3876341148170.000000,1586626335984.000000,NaN,2135788964891.000000,153925847295.000000,NaN,NaN
216,MIG,2021-09-30,Q,N,2963453516969.000000,1865052965577.000000,NaN,946189005472.000000,152211545920.000000,NaN,NaN
217,PGI,2021-09-30,Q,N,4194909754670.000000,1794857149195.000000,NaN,2059623748619.000000,340428856856.000000,NaN,NaN
218,PRE,2021-09-30,Q,N,3009904109170.000000,854557544001.000000,NaN,2031847793974.000000,123498771195.000000,NaN,NaN
219,PTI,2021-09-30,Q,N,4545777656078.000000,3186673007846.000000,NaN,1286773828841.000000,72330819391.000000,NaN,NaN
220,PVI,2021-09-30,Q,N,11262272833699.000000,4150052781766.000000,NaN,6751869512797.000000,360350539136.000000,NaN,NaN
221,VNR,2021-09-30,Q,N,3146732288121.000000,1138239599252.000000,NaN,1827187651603.000000,181305037266.000000,NaN,NaN
222,ABI,2021-12-31,Y,Y,1710907571832.000000,1308712954645.000000,NaN,260972564476.000000,141222052711.000000,NaN,NaN
223,ABI,2021-12-31,Q,N,1707113247753.000000,1308712954645.000000,NaN,257178240397.000000,141222052711.000000,NaN,NaN
224,AIC,2021-12-31,Y,Y,1808091009884.000000,1205517281083.000000,NaN,518545249357.000000,84028479444.000000,NaN,NaN
225,AIC,2021-12-31,Q,N,1811635984329.000000,1205517281083.000000,NaN,522026304512.000000,84092398734.000000,NaN,NaN
226,BIC,2021-12-31,Q,N,2575515476302.000000,1663024063026.000000,NaN,741856905059.000000,170634508217.000000,NaN,NaN
227,BIC,2021-12-31,Y,Y,2554789230354.000000,1644375293045.000000,NaN,739705430333.000000,170708506976.000000,NaN,NaN
228,BLI,2021-12-31,Q,N,1059400135167.000000,642828375544.000000,NaN,334083034511.000000,82488725112.000000,NaN,NaN
229,BLI,2021-12-31,Y,Y,1059400135167.000000,642828375544.000000,NaN,334083034511.000000,82488725112.000000,NaN,NaN
230,BMI,2021-12-31,Q,N,3801490338737.000000,1546910210765.000000,NaN,2089571621944.000000,165008506028.000000,NaN,NaN
231,BMI,2021-12-31,Y,Y,3796667410579.000000,1548104092014.000000,NaN,2083544882985.000000,165018435580.000000,NaN,NaN
235,MIG,2021-12-31,Y,Y,3086118204880.000000,2142347192479.000000,NaN,784647965434.000000,159123046967.000000,NaN,NaN
236,MIG,2021-12-31,Q,N,3100208245887.000000,2143745792177.000000,NaN,797146404206.000000,159316049504.000000,NaN,NaN
237,PGI,2021-12-31,Q,N,3829133894759.000000,1813357963764.000000,NaN,1667815980362.000000,347959950633.000000,NaN,NaN
239,PRE,2021-12-31,Q,N,3354561109749.000000,796219120133.000000,NaN,2433029015249.000000,125312974367.000000,NaN,NaN
240,PRE,2021-12-31,Y,Y,3354561109749.000000,796219120133.000000,NaN,2433029015249.000000,125312974367.000000,NaN,NaN
241,PTI,2021-12-31,Y,Y,4901910119412.000000,3366993634760.000000,NaN,1450296486631.000000,84619998021.000000,NaN,NaN
242,PTI,2021-12-31,Q,N,4878058857613.000000,3366993634760.000000,NaN,1426445224832.000000,84619998021.000000,NaN,NaN
243,PVI,2021-12-31,Y,Y,12012097278748.000000,4060307061619.000000,NaN,7643686749853.000000,308103467276.000000,NaN,NaN
244,PVI,2021-12-31,Q,N,12012336236408.000000,4056909819088.000000,NaN,7647385959960.000000,308040457360.000000,NaN,NaN
245,VNR,2021-12-31,Q,N,3137347307042.000000,1095520329811.000000,NaN,1857062704442.000000,184764272789.000000,NaN,NaN
246,VNR,2021-12-31,Y,Y,3137347307042.000000,1095520329811.000000,NaN,1857062704442.000000,184764272789.000000,NaN,NaN
247,ABI,2022-03-31,Q,N,1763470970355.000000,1344284982104.000000,NaN,273124224764.000000,146061763487.000000,NaN,NaN
248,AIC,2022-03-31,Q,N,1881502295944.000000,1182353816391.000000,NaN,610247191325.000000,88901288228.000000,NaN,NaN
249,BIC,2022-03-31,Q,N,2747564151106.000000,1812644610359.000000,NaN,758645119581.000000,176274421166.000000,NaN,NaN
250,BLI,2022-03-31,Q,N,1097045798466.000000,661771227083.000000,NaN,350367026771.000000,84907544612.000000,NaN,NaN
251,BMI,2022-03-31,Q,N,3776931501376.000000,1723948758709.000000,NaN,1877276700686.000000,175706041981.000000,NaN,NaN
254,MIG,2022-03-31,Q,N,3458631505170.000000,2403524762510.000000,NaN,889590734475.000000,165516008185.000000,NaN,NaN
255,PGI,2022-03-31,Q,N,4141218175304.000000,1809749635769.000000,NaN,1976826441753.000000,354642097782.000000,NaN,NaN
257,PTI,2022-03-31,Q,N,5265949323222.000000,3585609842427.000000,NaN,1580636883929.000000,99702596866.000000,NaN,NaN
258,PVI,2022-03-31,Q,N,12823222652799.000000,5014377805036.000000,NaN,7478165354583.000000,330679493180.000000,NaN,NaN
259,VNR,2022-03-31,Q,N,3063148966570.000000,1109132700755.000000,NaN,1765875918560.000000,188140347255.000000,NaN,NaN

In [34]:
ibs.check_ibs_330(df=df)

CHECK ITEM & SUB-ITEMS IBS_330

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_330,IBS_331,IBS_3311,IBS_3312,IBS_3313,IBS_332,IBS_333,IBS_334,IBS_3341,IBS_3342,IBS_3343,IBS_335,IBS_336,IBS_337,IBS_338,IBS_339
1,AIC,2018-03-31,Q,N,102895216.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,101895219.000000,0.000000
2,BIC,2018-03-31,Q,N,1662235520.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1662235550.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,BLI,2018-03-31,Q,N,4605728256.000000,0.000000,0.000000,0.000000,0.000000,0.000000,30000000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2880455168.000000,0.000000,1695273048.000000,0.000000
4,BMI,2018-03-31,Q,N,155868736.000000,0.000000,0.000000,0.000000,0.000000,0.000000,155868730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,BVH,2018-03-31,Q,N,154105118720.000000,0.000000,0.000000,0.000000,0.000000,0.000000,143514452377.000000,3542622947.000000,0.000000,0.000000,0.000000,7048043520.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,BVH,2022-09-30,Q,N,142115185799283.000000,0.000000,0.000000,0.000000,0.000000,0.000000,280220251484.000000,192745387538.000000,0.000000,0.000000,0.000000,7046161673.000000,0.000000,0.000000,0.000000,0.000000
296,BVH,2022-12-31,Q,N,147760970588645.000000,0.000000,0.000000,0.000000,0.000000,0.000000,283934449583.000000,91299047538.000000,0.000000,0.000000,0.000000,4773922051.000000,0.000000,0.000000,0.000000,0.000000
297,BVH,2022-12-31,Y,Y,147889162247129.000000,0.000000,0.000000,0.000000,0.000000,0.000000,296696283981.000000,91023530915.000000,0.000000,0.000000,0.000000,4840608220.000000,0.000000,0.000000,0.000000,0.000000
318,BVH,2023-03-31,Q,N,152787594575751.000000,0.000000,0.000000,0.000000,0.000000,0.000000,298985478611.000000,54486350296.000000,0.000000,0.000000,0.000000,4147082949.000000,0.000000,0.000000,0.000000,0.000000
331,BVH,2023-06-30,Q,N,157278565566175.000000,0.000000,0.000000,0.000000,0.000000,0.000000,302561845166.000000,52762632119.000000,0.000000,0.000000,0.000000,4450686594.000000,0.000000,0.000000,0.000000,0.000000

In [35]:
ibs.check_ibs_3401(df=df)

CHECK ITEM & SUB-ITEMS IBS_3401

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_3401,IBS_3402,IBS_3403,IBS_3404,IBS_3405,IBS_3406,IBS_3407
5,BVH,2018-03-31,Q,N,58759871201280.000000,4657231953920.000000,49938083872768.000000,2572956205056.000000,58774011904.000000,1454837465088.000000,77986873344.000000
169,BVH,2020-12-31,Y,Y,105270361715051.000000,4970615412207.000000,93090719199763.000000,2575753599129.000000,16207748985.000000,1935346562096.000000,133720703795.000000
191,IFA,2021-03-31,Q,N,690742360242.000000,392119700923.000000,NaN,74245878447.000000,224376780872.000000,0.000000,NaN
215,BVH,2021-09-30,Q,Y,119393968521088.000000,4354376984643.000000,107417876017251.000000,2394566284975.000000,42069066193.000000,2029780797060.000000,196147843955.000000
232,BVH,2021-12-31,Q,N,125259541393200.000000,4636802667094.000000,112072915971376.000000,2432026922010.000000,54204542452.000000,2157438745997.000000,217817234608.000000
234,HVB,2021-12-31,Y,Y,91956367889.000000,47133020756.000000,NaN,31089280465.000000,13734066668.000000,0.000000,NaN
238,PGI,2021-12-31,Y,Y,3829133894759.000000,1813357963764.000000,NaN,1667815980362.000000,347959950633.000000,0.000000,NaN
253,IFA,2022-03-31,Q,N,496029851924.000000,215628649004.000000,NaN,49473561748.000000,230927641172.000000,0.000000,NaN
256,PRE,2022-03-31,Q,Y,3373470651142.000000,925412431749.000000,NaN,2312182371385.000000,135875848008.000000,0.000000,NaN
260,ABI,2022-06-30,Q,Y,1841280440032.000000,1425845288711.000000,NaN,264102460871.000000,151332690450.000000,0.000000,NaN
261,AIC,2022-06-30,Q,Y,1961473899181.000000,1185477418106.000000,NaN,681765475810.000000,94231005265.000000,0.000000,NaN
262,BIC,2022-06-30,Q,Y,2952161780135.000000,1977495553642.000000,NaN,793614148813.000000,181052077680.000000,0.000000,NaN
263,BLI,2022-06-30,Q,Y,1178365956972.000000,652175812962.000000,NaN,438648529709.000000,87541614301.000000,0.000000,NaN
264,BMI,2022-06-30,Q,Y,3569086302094.000000,1688758327840.000000,NaN,1694589832835.000000,185738141419.000000,0.000000,NaN
266,IFA,2022-06-30,Q,N,465936496636.000000,198308803457.000000,NaN,37367276977.000000,230260416202.000000,0.000000,NaN
267,MIG,2022-06-30,Q,Y,3845170994168.000000,2744016746757.000000,NaN,929273792139.000000,171880455272.000000,0.000000,NaN
268,PGI,2022-06-30,Q,Y,4306291014245.000000,1838103910486.000000,NaN,2106723076654.000000,361464027105.000000,0.000000,NaN
269,PRE,2022-06-30,Q,N,3433972589289.000000,967755117503.000000,NaN,2322072683919.000000,144144787867.000000,0.000000,NaN
270,PTI,2022-06-30,Q,Y,5225828684915.000000,3648292223794.000000,NaN,1466314694120.000000,111221767001.000000,0.000000,NaN
271,PVI,2022-06-30,Q,Y,13098146646194.000000,5410837877401.000000,NaN,7339473245797.000000,347835522996.000000,0.000000,NaN
272,VNR,2022-06-30,Q,Y,3125398224906.000000,1172233359396.000000,NaN,1761734672690.000000,191430192820.000000,0.000000,NaN
273,ABI,2022-09-30,Q,N,1797884233063.000000,1386397726859.000000,NaN,255790424946.000000,155696081258.000000,0.000000,NaN
274,AIC,2022-09-30,Q,N,2015272331288.000000,1247216759319.000000,NaN,669287699386.000000,98767872583.000000,0.000000,NaN
275,BIC,2022-09-30,Q,N,2914245843386.000000,1855819619225.000000,NaN,871485000666.000000,186941223495.000000,0.000000,NaN
276,BLI,2022-09-30,Q,N,1130772689897.000000,608009889895.000000,NaN,433213139600.000000,89549660402.000000,0.000000,NaN
277,BMI,2022-09-30,Q,N,3655427151382.000000,1841121629107.000000,NaN,1616439046917.000000,197866475358.000000,0.000000,NaN
279,IFA,2022-09-30,Q,N,457855629974.000000,180022427683.000000,NaN,44781830380.000000,233051371911.000000,0.000000,NaN
280,MIG,2022-09-30,Q,N,3819540592262.000000,2735601140970.000000,NaN,906758811368.000000,177180639924.000000,0.000000,NaN
281,PGI,2022-09-30,Q,N,4096852208240.000000,1898287587812.000000,NaN,1850604243577.000000,347960376851.000000,0.000000,NaN
282,PRE,2022-09-30,Q,N,3549530462495.000000,1055331348653.000000,NaN,2340208394186.000000,153990719656.000000,0.000000,NaN
283,PTI,2022-09-30,Q,N,5218729961171.000000,3618718673108.000000,NaN,1479340874189.000000,120670413874.000000,0.000000,NaN
284,PVI,2022-09-30,Q,N,13049550442860.000000,5106289983685.000000,NaN,7583463636583.000000,359796822592.000000,0.000000,NaN
285,VNR,2022-09-30,Q,N,3078579264763.000000,1187317390888.000000,NaN,1696543597703.000000,194718276172.000000,0.000000,NaN
286,ABI,2022-12-31,Y,Y,1796206541396.000000,1391539970783.000000,NaN,244082013294.000000,160584557319.000000,0.000000,NaN
287,ABI,2022-12-31,Q,N,1796206541396.000000,1391539970783.000000,NaN,244082013294.000000,160584557319.000000,0.000000,NaN
288,AIC,2022-12-31,Y,Y,1985731563089.000000,1243304655032.000000,NaN,638290134566.000000,104136773491.000000,0.000000,NaN
289,AIC,2022-12-31,Q,N,1980067650287.000000,1243381434094.000000,NaN,632519688794.000000,104166527399.000000,0.000000,NaN
290,BIC,2022-12-31,Q,N,2953500494467.000000,1942589923280.000000,NaN,818834593984.000000,192075977203.000000,0.000000,NaN
291,BIC,2022-12-31,Y,Y,2976968181133.000000,1964927094499.000000,NaN,819859988620.000000,192181098014.000000,0.000000,NaN
292,BLI,2022-12-31,Q,N,1174362793548.000000,663530871731.000000,NaN,417763513417.000000,93068408400.000000,0.000000,NaN
293,BLI,2022-12-31,Y,Y,1174362793548.000000,663530871731.000000,NaN,417763513417.000000,93068408400.000000,0.000000,NaN
294,BMI,2022-12-31,Y,Y,3344475120935.000000,1874304158642.000000,NaN,1259858297105.000000,210312665188.000000,0.000000,NaN
295,BMI,2022-12-31,Q,N,3235425199230.000000,1874304158748.000000,NaN,1150839772584.000000,210281267898.000000,0.000000,NaN
298,HVB,2022-12-31,Y,Y,91956367889.000000,47133020756.000000,NaN,31089280465.000000,13734066668.000000,0.000000,NaN
299,IFA,2022-12-31,Q,N,444149310266.000000,167930253176.000000,NaN,41971958112.000000,234247098978.000000,0.000000,NaN
300,IFA,2022-12-31,Y,Y,419931793114.000000,146199835148.000000,NaN,42000747725.000000,231731210241.000000,0.000000,NaN
301,MIG,2022-12-31,Q,N,4039586310102.000000,2786002348243.000000,NaN,1066941308705.000000,186642653154.000000,0.000000,NaN
302,MIG,2022-12-31,Y,Y,4039412614255.000000,2786002348243.000000,NaN,1066765346173.000000,186644919839.000000,0.000000,NaN
303,PGI,2022-12-31,Q,N,4094875805196.000000,1939462647262.000000,NaN,1792221143092.000000,363192014842.000000,0.000000,NaN
304,PGI,2022-12-31,Y,Y,4094875805196.000000,1939462647262.000000,NaN,1792221143092.000000,363192014842.000000,0.000000,NaN
305,PRE,2022-12-31,Q,N,3639542690200.000000,1187085767903.000000,NaN,2291366751963.000000,161090170334.000000,0.000000,NaN
306,PRE,2022-12-31,Y,Y,3639542690200.000000,1187085767903.000000,NaN,2291366751963.000000,161090170334.000000,0.000000,NaN
307,PTI,2022-12-31,Q,N,5274627487677.000000,3631789735305.000000,NaN,1511267231024.000000,131570521348.000000,0.000000,NaN
308,PTI,2022-12-31,Y,Y,5278628467097.000000,3631789735305.000000,NaN,1515268210444.000000,131570521348.000000,0.000000,NaN
309,PVI,2022-12-31,Y,Y,13528767393506.000000,4846907870296.000000,NaN,8313789757668.000000,368069765542.000000,0.000000,NaN
310,PVI,2022-12-31,Q,N,13528494348211.000000,4846558602727.000000,NaN,8313865979942.000000,368069765542.000000,0.000000,NaN
311,VNR,2022-12-31,Y,Y,2937956784312.000000,1148013393804.000000,NaN,1592468265070.000000,197475125438.000000,0.000000,NaN
312,VNR,2022-12-31,Q,N,2937956784312.000000,1148013393804.000000,NaN,1592468265070.000000,197475125438.000000,0.000000,NaN

In [36]:
ibs.check_ibs_400(df=df)

CHECK ITEM & SUB-ITEMS IBS_400

Empty DataFrame
Columns: [SECURITY_CODE, REPORT_DATE, FREQ_CODE, AUDITED, IBS_400, IBS_410, IBS_4219]
Index: []

In [37]:
ibs.check_ibs_410(df=df)

CHECK ITEM & SUB-ITEMS IBS_410

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_410,IBS_411,IBS_412,IBS_414,IBS_413,IBS_415,IBS_416,IBS_417,IBS_418,IBS_419,IBS_420,IBS_421,IBS_4213,IBS_4214
0,ABI,2018-03-31,Q,N,700144222208.000000,380000010240.000000,12000000000.000000,-13898399744.000000,0.000000,0.000000,0.000000,86133186560.000000,0.000000,33448652800.000000,0.000000,202460758016.000000,0.000000,0.000000
1,AIC,2018-03-31,Q,N,820438499328.000000,799999983616.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10985112576.000000,0.000000,9453371392.000000,0.000000,0.000000
2,BIC,2018-03-31,Q,N,2152669380608.000000,1172768948224.000000,655565062144.000000,0.000000,0.000000,0.000000,9988717568.000000,6457955840.000000,0.000000,42460262400.000000,0.000000,233299099648.000000,0.000000,32129314191.000000
3,BLI,2018-03-31,Q,N,665636438016.000000,599999971328.000000,-415994848.000000,-5260000.000000,0.000000,0.000000,0.000000,0.000000,13907191808.000000,1200000000.000000,0.000000,50950475776.000000,0.000000,0.000000
4,BMI,2018-03-31,Q,N,2197410938880.000000,913540382720.000000,974943682560.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,81332731904.000000,28085153439.000000,199508951040.000000,0.000000,0.000000
5,BVH,2018-03-31,Q,N,14909325705216.000000,6804714553344.000000,3184332374016.000000,0.000000,0.000000,0.000000,15445191680.000000,465791156224.000000,0.000000,0.000000,103568802818.000000,3230937907200.000000,388939138849.000000,715596492277.000000
6,MIG,2018-03-31,Q,N,902290276352.000000,799999983616.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18164377600.000000,0.000000,76884680704.000000,0.000000,7241199739.000000
7,PGI,2018-03-31,Q,N,1396423917568.000000,887177740288.000000,359463157760.000000,0.000000,0.000000,0.000000,0.000000,50153750528.000000,0.000000,50100772864.000000,0.000000,49528528896.000000,0.000000,0.000000
8,PTI,2018-03-31,Q,N,1932650872832.000000,803957112832.000000,827943026688.000000,0.000000,0.000000,0.000000,0.000000,21059047424.000000,0.000000,48967380992.000000,0.000000,229687656448.000000,0.000000,1036686881.000000
9,PVI,2018-03-31,Q,N,7261362585600.000000,2342418644992.000000,3478091726848.000000,-92960006144.000000,0.000000,0.000000,0.000000,179211812864.000000,0.000000,0.000000,161491450857.000000,965363171328.000000,0.000000,227745841180.000000
10,VNR,2018-03-31,Q,N,2783637929984.000000,1310759321600.000000,566368534528.000000,0.000000,0.000000,0.000000,0.000000,202028187648.000000,0.000000,128878583808.000000,0.000000,544854048768.000000,30749104249.000000,0.000000
11,ABI,2018-06-30,Q,Y,673013956608.000000,380000010240.000000,12000000000.000000,-13898399744.000000,0.000000,0.000000,0.000000,124633186304.000000,0.000000,33448652800.000000,0.000000,136830500864.000000,0.000000,0.000000
14,BLI,2018-06-30,Q,Y,669360455680.000000,599999971328.000000,-415994848.000000,-5260000.000000,0.000000,0.000000,0.000000,0.000000,13907191808.000000,1200000000.000000,0.000000,54674497536.000000,0.000000,0.000000
15,BMI,2018-06-30,Q,Y,2222177124352.000000,913540382720.000000,974943682560.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,81332731904.000000,28085153439.000000,224275054592.000000,0.000000,0.000000
18,PGI,2018-06-30,Q,Y,1422442627072.000000,887177740288.000000,359463157760.000000,0.000000,0.000000,0.000000,0.000000,51427348480.000000,0.000000,50100772864.000000,0.000000,74273611776.000000,0.000000,0.000000
20,PVI,2018-06-30,Q,Y,6691149053952.000000,2342418644992.000000,3508280492032.000000,-56956399616.000000,0.000000,0.000000,0.000000,179211812864.000000,0.000000,0.000000,165381504274.000000,323430612992.000000,0.000000,229382235858.000000
21,VNR,2018-06-30,Q,Y,2826517086208.000000,1310759321600.000000,566368534528.000000,0.000000,0.000000,0.000000,0.000000,203475877888.000000,0.000000,131075940352.000000,0.000000,584238432256.000000,30599083250.000000,0.000000

In [38]:
ibs.check_ibs_411(df=df)

CHECK ITEM & SUB-ITEMS IBS_411

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_411,IBS_4111,IBS_4112
0,ABI,2018-03-31,Q,N,380000010240.000000,380000000000.000000,0.000000
1,AIC,2018-03-31,Q,N,799999983616.000000,800000000000.000000,0.000000
2,BIC,2018-03-31,Q,N,1172768948224.000000,1172768950000.000000,0.000000
3,BLI,2018-03-31,Q,N,599999971328.000000,600000000000.000000,0.000000
4,BMI,2018-03-31,Q,N,913540382720.000000,913540378000.000000,0.000000
5,BVH,2018-03-31,Q,N,6804714553344.000000,6804714340000.000000,0.000000
6,MIG,2018-03-31,Q,N,799999983616.000000,800000000000.000000,0.000000
7,PGI,2018-03-31,Q,N,887177740288.000000,887177730000.000000,0.000000
8,PTI,2018-03-31,Q,N,803957112832.000000,803957090000.000000,0.000000
9,PVI,2018-03-31,Q,N,2342418644992.000000,2342418670000.000000,0.000000
10,VNR,2018-03-31,Q,N,1310759321600.000000,1310759370000.000000,0.000000
11,ABI,2018-06-30,Q,Y,380000010240.000000,380000000000.000000,0.000000
14,BLI,2018-06-30,Q,Y,599999971328.000000,600000000000.000000,0.000000
15,BMI,2018-06-30,Q,Y,913540382720.000000,913540378000.000000,0.000000
18,PGI,2018-06-30,Q,Y,887177740288.000000,887177730000.000000,0.000000
20,PVI,2018-06-30,Q,Y,2342418644992.000000,2342418670000.000000,0.000000
21,VNR,2018-06-30,Q,Y,1310759321600.000000,1310759370000.000000,0.000000
234,HVB,2021-12-31,Y,Y,300000000000.000000,0.000000,0.000000

In [39]:
ibs.check_ibs_421(df=df)

CHECK ITEM & SUB-ITEMS IBS_421

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_421,IBS_4211,IBS_4212
0,ABI,2018-03-31,Q,N,202460758016.000000,160088308359.000000,42372444930.000000
1,AIC,2018-03-31,Q,N,9453371392.000000,0.000000,9453371279.000000
2,BIC,2018-03-31,Q,N,233299099648.000000,4956376495.000000,228342726844.000000
3,BLI,2018-03-31,Q,N,50950475776.000000,0.000000,50950475577.000000
4,BMI,2018-03-31,Q,N,199508951040.000000,0.000000,199508952260.000000
5,BVH,2018-03-31,Q,N,3230937907200.000000,2806004266889.000000,424933526091.000000
6,MIG,2018-03-31,Q,N,76884680704.000000,0.000000,76884682583.000000
7,PGI,2018-03-31,Q,N,49528528896.000000,0.000000,49528527257.000000
8,PTI,2018-03-31,Q,N,229687656448.000000,0.000000,229687663522.000000
9,PVI,2018-03-31,Q,N,965363171328.000000,809995914002.000000,155367238000.000000
10,VNR,2018-03-31,Q,N,544854048768.000000,483692105013.000000,61161941174.000000
11,ABI,2018-06-30,Q,Y,136830500864.000000,40697938964.000000,96132562887.000000
14,BLI,2018-06-30,Q,Y,54674497536.000000,0.000000,54674499026.000000
15,BMI,2018-06-30,Q,Y,224275054592.000000,0.000000,224275057077.000000
18,PGI,2018-06-30,Q,Y,74273611776.000000,0.000000,74273615794.000000
20,PVI,2018-06-30,Q,Y,323430612992.000000,105622546269.000000,217808074402.000000
21,VNR,2018-06-30,Q,Y,584238432256.000000,457476917613.000000,126761486610.000000

In [40]:
ibs.check_ibs_4215(df=df)

CHECK ITEM & SUB-ITEMS IBS_4215

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_4215,IBS_4216,IBS_4217,IBS_4218
156,PVI,2020-09-30,Q,N,NaN,0.000000,NaN,NaN
169,BVH,2020-12-31,Y,Y,NaN,0.000000,NaN,NaN
180,PVI,2020-12-31,Q,N,NaN,0.000000,NaN,NaN
190,HVB,2021-03-31,Q,N,NaN,0.000000,NaN,NaN
196,PVI,2021-03-31,Q,N,NaN,0.000000,NaN,NaN
202,BMI,2021-06-30,Q,Y,NaN,0.000000,NaN,NaN
204,MIG,2021-06-30,Q,Y,NaN,0.000000,NaN,NaN
205,PGI,2021-06-30,Q,Y,NaN,0.000000,NaN,NaN
210,ABI,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
211,AIC,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
212,BIC,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
213,BLI,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
214,BMI,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
215,BVH,2021-09-30,Q,Y,NaN,0.000000,NaN,NaN
216,MIG,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
217,PGI,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
218,PRE,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
219,PTI,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
220,PVI,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
221,VNR,2021-09-30,Q,N,NaN,0.000000,NaN,NaN
222,ABI,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
223,ABI,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
224,AIC,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
225,AIC,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
226,BIC,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
227,BIC,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
228,BLI,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
229,BLI,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
230,BMI,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
231,BMI,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
232,BVH,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
235,MIG,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
236,MIG,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
237,PGI,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
239,PRE,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
240,PRE,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
241,PTI,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
242,PTI,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
243,PVI,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
244,PVI,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
245,VNR,2021-12-31,Q,N,NaN,0.000000,NaN,NaN
246,VNR,2021-12-31,Y,Y,NaN,0.000000,NaN,NaN
247,ABI,2022-03-31,Q,N,NaN,0.000000,NaN,NaN
248,AIC,2022-03-31,Q,N,NaN,0.000000,NaN,NaN
249,BIC,2022-03-31,Q,N,NaN,0.000000,NaN,NaN
250,BLI,2022-03-31,Q,N,NaN,0.000000,NaN,NaN
251,BMI,2022-03-31,Q,N,NaN,0.000000,NaN,NaN
254,MIG,2022-03-31,Q,N,NaN,0.000000,NaN,NaN
255,PGI,2022-03-31,Q,N,NaN,0.000000,NaN,NaN
257,PTI,2022-03-31,Q,N,NaN,0.000000,NaN,NaN
258,PVI,2022-03-31,Q,N,NaN,0.000000,NaN,NaN
259,VNR,2022-03-31,Q,N,NaN,0.000000,NaN,NaN

In [41]:
ibs.check_ibs_430(df=df)

CHECK ITEM & SUB-ITEMS IBS_430

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,IBS_430,IBS_300,IBS_400
0,ABI,2018-03-31,Q,N,1892936450048.000000,1192792293376.000000,700144222208.000000
1,AIC,2018-03-31,Q,N,1663821676544.000000,843383242752.000000,820438499328.000000
4,BMI,2018-03-31,Q,N,5692572303360.000000,3495161757696.000000,2197410938880.000000
5,BVH,2018-03-31,Q,N,99329566048256.000000,84420241391616.000000,14909325705216.000000
6,MIG,2018-03-31,Q,N,3187527385088.000000,2285237174272.000000,902290276352.000000
7,PGI,2018-03-31,Q,N,5000720285696.000000,3604296499200.000000,1396423917568.000000
10,VNR,2018-03-31,Q,N,6429548216320.000000,3645910548480.000000,2783637929984.000000
14,BLI,2018-06-30,Q,Y,1701848416256.000000,1032488026112.000000,669360455680.000000
20,PVI,2018-06-30,Q,Y,21756544811008.000000,15065396805632.000000,6691149053952.000000