In [1]:
import pandas as pd
import numpy as np
import oracledb
import os
import platform
import sys
import tomli
import datetime as dt
from check_py import check_company_bs as cbs

pd.set_option('float_format', '{:f}'.format)

In [2]:
# Assign pathlink
path_link_db_algo = r"C:\Users\tungtt1\Desktop\bsc_config\config_algo.toml"

In [3]:
# Import files connfiq
with open(path_link_db_algo, mode="rb") as fp:
    config_acc = tomli.load(fp)

In [4]:
# Set up config for Oracle SQl Developer
host = config_acc["algo_acc"]["host"]
port = config_acc["algo_acc"]["port"]
service_name = config_acc["algo_acc"]["service_name"]
user = config_acc["algo_acc"]["user"]
password = config_acc["algo_acc"]["password"]

In [5]:
oracledb.init_oracle_client()

In [6]:
# Connect to database Oracle
conn = oracledb.connect(
    user=user,
    password=password,
    dsn=host+"/"+service_name
)

c = conn.cursor()

In [8]:
df = pd.read_sql_query(
    """ SELECT 
    *
    FROM COMPANY_BALANCE_SHEET CBS
    INNER JOIN SECURITY_INDUSTRY SI on SI.SECURITY_CODE = CBS.SECURITY_CODE
    WHERE SI.LEVEL3_CODE != 8350
    AND SI.LEVEL3_CODE != 8770
    AND SI.LEVEL3_CODE != 8530
    AND LENGTH(SI.SECURITY_CODE) = 3
    ORDER BY CBS.REPORT_DATE ASC, CBS.SECURITY_CODE ASC
    """, con=conn
)

C:\Users\tungtt1\AppData\Local\Temp\45\ipykernel_91880\1341968065.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

In [9]:
# df = pd.read_excel(r"/Users/rainmeteror/Desktop/BSC_Algo_Database_UAT/OneDrive_1_5-29-2023/company/algo_cbs.xlsx")

In [10]:
df

,SCN,REPORT_DATE,REPORTED_DATE,FREQ_CODE,SECURITY_CODE,AUDITED,MONTH_IN_PERIOD,CBS_100,CBS_110,CBS_111,...,LEVEL4_ORD,LEVEL4_NAME_VN,LEVEL4_NAME_EN,LEVEL4_NAME_CN,LEVEL4_NAME_KR,LEVEL4_NAME_JP,START_EFFECTIVE_DATE,END_EFFECTIVE_DATE,CREATED_DATE,UPDATED_DATE
0,52528,2018-03-31,None,Q,AAA,N,3,2378121710833.000000,427747817583.000000,206316955286.000000,...,230,Containers & Đóng gói,Containers & Packaging,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-05-23 11:48:15.900474
1,52528,2018-03-31,None,Q,AAM,N,3,198525717897.000000,37096421529.000000,6096421529.000000,...,450,Nuôi trồng Nông & Hải sản,"Farming, Fishing & Plantations",None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
2,52528,2018-03-31,None,Q,AAV,N,3,133591409074.000000,3606431177.000000,3606431177.000000,...,920,Bất động sản,Real Estate Holding & Development,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
3,52528,2018-03-31,None,Q,ABC,N,3,682437548738.000000,99311467361.000000,29311467361.000000,...,800,Viễn thông di động,Mobile Telecommunications,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
4,52528,2018-03-31,None,Q,ABG,N,3,130062152175.000000,1703569204.000000,1703569204.000000,...,920,Bất động sản,Real Estate Holding & Development,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30918,43438740,2023-12-31,0001-01-01 00:00:00,Y,ITD,N,12,490135197942.000000,79539149212.000000,38849963529.000000,...,340,Dịch vụ Hỗ trợ Kinh doanh,Business Support Services,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-05-23 11:48:15.900474
30919,43376445,2023-12-31,0001-01-01 00:00:00,Y,KOS,Y,12,3340282524366.000000,45752508349.000000,34465931232.000000,...,920,Bất động sản,Real Estate Holding & Development,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-05-23 11:48:15.900474
30920,43373882,2023-12-31,0001-01-01 00:00:00,Y,MCG,Y,12,148934287933.000000,4098054436.000000,4098054436.000000,...,280,Máy công nghiệp,Industrial Machinery,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-05-23 11:48:15.900474
30921,43374494,2023-12-31,0001-01-01 00:00:00,Y,PGC,Y,12,1912555317945.000000,51142685869.000000,51142685869.000000,...,10,Sản xuất và Khai thác dầu khí,Exploration & Production,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490
30922,43374466,2023-12-31,0001-01-01 00:00:00,Y,PSD,Y,12,3343691677075.000000,72261768252.000000,71261768252.000000,...,1140,Thiết bị viễn thông,Telecommunications Equipment,None,None,None,2000-01-01,2099-12-31,2023-02-28 10:09:18.188490,2023-02-28 10:09:18.188490

In [11]:
cbs.check_cbs_100(df=df)

CHECK ITEM & SUB-ITEMS CBS_100

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_100,CBS_110,CBS_120,CBS_130,CBS_140,CBS_150
17505,DFF,DFF,2021-03-31,Q,N,1095732559872.000000,2813509632.000000,0.000000,595438403584.000000,459884167168.000000,37596459008.000000
18748,HSG,HSG,2021-06-30,Q,N,17185925758976.000000,505654083584.000000,23517532160.000000,3765465251840.000000,11646465474560.000000,1244823289856.000000
18851,LDW,LDW,2021-06-30,Q,Y,631303569408.000000,54244614144.000000,535335665664.000000,33430648832.000000,8245003776.000000,47614440.000000
18860,LLM,LLM,2021-06-30,Q,N,6348948373504.000000,1104918085632.000000,3463000064.000000,4391068762112.000000,763797700608.000000,85700960256.000000
19049,PVA,PVA,2021-06-30,Q,N,390063390720.000000,1012260864.000000,0.000000,331791433728.000000,57137586176.000000,122085776.000000
19173,SPD,SPD,2021-06-30,Q,N,349333618688.000000,81472626688.000000,0.000000,83552141312.000000,179234996224.000000,5073856512.000000
19271,TNH,TNH,2021-06-30,Q,Y,204919095296.000000,44919451648.000000,0.000000,145575657472.000000,13936841728.000000,487143808.000000
19346,VEF,VEF,2021-06-30,Q,N,5239867965440.000000,2200497553408.000000,1500000026624.000000,1528592728064.000000,0.000000,10777951232.000000
19347,VET,VET,2021-06-30,Q,N,404871380992.000000,35878035456.000000,0.000000,152176279552.000000,211937476608.000000,4879592960.000000
19427,VTX,VTX,2021-06-30,Q,N,322579398656.000000,31379333120.000000,0.000000,189160751104.000000,89836257280.000000,12203049984.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
cbs.check_cbs_110(df=df)

CHECK ITEM & SUB-ITEMS CBS_110

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_110,CBS_111,CBS_112
237,DUS,DUS,2018-03-31,Q,N,868091074.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,32996849756.000000,0.000000,0.000000
1861,STS,STS,2018-06-30,Q,N,38719397166.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,9179238513.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,3723524459.000000,3723524459.000000,NaN
18748,HSG,HSG,2021-06-30,Q,N,505654083584.000000,468312326144.000000,37341749248.000000
18851,LDW,LDW,2021-06-30,Q,Y,54244614144.000000,33914163200.000000,20330448896.000000
18860,LLM,LLM,2021-06-30,Q,N,1104918085632.000000,537970245632.000000,566947938304.000000
19346,VEF,VEF,2021-06-30,Q,N,2200497553408.000000,341198995456.000000,1859298525184.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [13]:
cbs.check_cbs_120(df=df)

CHECK ITEM & SUB-ITEMS CBS_120

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_120,CBS_121,CBS_122,CBS_123
237,DUS,DUS,2018-03-31,Q,N,56769416667.000000,0.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,33650000000.000000,0.000000,0.000000,0.000000
1861,STS,STS,2018-06-30,Q,N,26000000000.000000,0.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,54700000000.000000,0.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN,NaN
17892,NVL,NVL,2021-03-31,Q,N,1011977986695.000000,NaN,NaN,1011977986695.000000
18748,HSG,HSG,2021-06-30,Q,N,23517532160.000000,0.000000,0.000000,23517531836.000000
18851,LDW,LDW,2021-06-30,Q,Y,535335665664.000000,0.000000,0.000000,535335676667.000000
18860,LLM,LLM,2021-06-30,Q,N,3463000064.000000,0.000000,0.000000,3463000000.000000
19346,VEF,VEF,2021-06-30,Q,N,1500000026624.000000,0.000000,0.000000,1500000000000.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN

In [14]:
cbs.check_cbs_130(df=df)

CHECK ITEM & SUB-ITEMS CBS_130

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_130,CBS_131,CBS_132,CBS_133,CBS_134,CBS_135,CBS_136,CBS_137,CBS_139
237,DUS,DUS,2018-03-31,Q,N,7299562200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,8588102581.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1861,STS,STS,2018-06-30,Q,N,14107889916.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,7366773138.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8750,TCK,TCK,2019-09-30,Q,N,332494211782.000000,258960128562.000000,26140079421.000000,0.000000,0.000000,500000000.000000,194760899736.000000,-152661300557.000000,1469247303.000000
17505,DFF,DFF,2021-03-31,Q,N,595438403584.000000,445094330368.000000,137966567424.000000,0.000000,0.000000,0.000000,12377526272.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,38755226995.000000,18474530400.000000,20240242050.000000,NaN,NaN,NaN,40454545.000000,NaN,NaN
17892,NVL,NVL,2021-03-31,Q,N,16818356520514.000000,2133360457070.000000,1805529740671.000000,NaN,NaN,3927093447664.000000,8962636520887.000000,-10263645778.000000,NaN
18748,HSG,HSG,2021-06-30,Q,N,3765465251840.000000,2907748171776.000000,671614697472.000000,0.000000,0.000000,0.000000,203137155072.000000,-17034703872.000000,0.000000
18851,LDW,LDW,2021-06-30,Q,Y,33430648832.000000,4805440000.000000,4502324224.000000,0.000000,0.000000,0.000000,29176676352.000000,-5147524096.000000,93732518.000000
18860,LLM,LLM,2021-06-30,Q,N,4391068762112.000000,4126594301952.000000,738754166784.000000,0.000000,0.000000,377105669770.000000,411848409088.000000,-1263233794048.000000,0.000000
19049,PVA,PVA,2021-06-30,Q,N,331791433728.000000,88774262784.000000,38488719360.000000,0.000000,10618384384.000000,26880319116.000000,200169455616.000000,-33139707904.000000,0.000000
19173,SPD,SPD,2021-06-30,Q,N,83552141312.000000,167054475264.000000,7025165312.000000,0.000000,0.000000,0.000000,574115328.000000,-91101618176.000000,0.000000
19271,TNH,TNH,2021-06-30,Q,Y,145575657472.000000,26944686080.000000,114605965312.000000,0.000000,0.000000,0.000000,4024999936.000000,0.000000,0.000000
19346,VEF,VEF,2021-06-30,Q,N,1528592728064.000000,69600000.000000,55026876416.000000,0.000000,0.000000,1240000000000.000000,233496248320.000000,0.000000,0.000000
19347,VET,VET,2021-06-30,Q,N,152176279552.000000,115332931584.000000,26137473024.000000,0.000000,0.000000,0.000000,10705865728.000000,0.000000,0.000000
19427,VTX,VTX,2021-06-30,Q,N,189160751104.000000,142323351552.000000,35894734848.000000,0.000000,0.000000,0.000000,48340209664.000000,-37397540864.000000,0.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
cbs.check_cbs_140(df=df)

CHECK ITEM & SUB-ITEMS CBS_140

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_140,CBS_141,CBS_149
237,DUS,DUS,2018-03-31,Q,N,2007064039.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,2475167050.000000,0.000000,0.000000
1861,STS,STS,2018-06-30,Q,N,400549402.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,2569192351.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,25441612058.000000,25441612058.000000,NaN
18748,HSG,HSG,2021-06-30,Q,N,11646465474560.000000,11712491159552.000000,-66025385984.000000
18851,LDW,LDW,2021-06-30,Q,Y,8245003776.000000,9491742720.000000,-1246739200.000000
19427,VTX,VTX,2021-06-30,Q,N,89836257280.000000,89979297792.000000,-143039184.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [16]:
cbs.check_cbs_150(df=df)

CHECK ITEM & SUB-ITEMS CBS_150

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_150,CBS_151,CBS_152,CBS_153,CBS_154,CBS_155
237,DUS,DUS,2018-03-31,Q,N,1395447884.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1861,STS,STS,2018-06-30,Q,N,109653354.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,733831288.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17505,DFF,DFF,2021-03-31,Q,N,37596459008.000000,1177825792.000000,36418629632.000000,0.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,898855221.000000,345853796.000000,553001425.000000,NaN,NaN,NaN
17892,NVL,NVL,2021-03-31,Q,N,1186968548418.000000,154752333673.000000,945807189878.000000,86409024867.000000,NaN,NaN
18748,HSG,HSG,2021-06-30,Q,N,1244823289856.000000,147564691456.000000,1097172058112.000000,86496288.000000,0.000000,0.000000
18851,LDW,LDW,2021-06-30,Q,Y,47614440.000000,46744864.000000,0.000000,869574.000000,0.000000,0.000000
18860,LLM,LLM,2021-06-30,Q,N,85700960256.000000,404865952.000000,54336606208.000000,30959486976.000000,0.000000,0.000000
19049,PVA,PVA,2021-06-30,Q,N,122085776.000000,62937716.000000,59148064.000000,0.000000,0.000000,0.000000
19173,SPD,SPD,2021-06-30,Q,N,5073856512.000000,3053042944.000000,1927117312.000000,93696328.000000,0.000000,0.000000
19346,VEF,VEF,2021-06-30,Q,N,10777951232.000000,0.000000,10766989312.000000,10961787.000000,0.000000,0.000000
19427,VTX,VTX,2021-06-30,Q,N,12203049984.000000,3789796352.000000,7648837632.000000,764416128.000000,0.000000,0.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
cbs.check_cbs_200(df=df)

CHECK ITEM & SUB-ITEMS CBS_200

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_200,CBS_210,CBS_220,CBS_230,CBS_240,CBS_250,CBS_260
237,DUS,DUS,2018-03-31,Q,N,30809384666.000000,0.000000,27840555213.000000,0.000000,2141248986.000000,608015024.000000,156065443.000000
256,FCN,FCN,2018-03-31,Q,N,954476594172.000000,43504838812.000000,629378153910.000000,0.000000,11148275700.000000,208291590784.000000,62057334966.000000
453,LCG,LCG,2018-03-31,Q,N,1022741964382.000000,7000000.000000,240836306694.000000,0.000000,95496937695.000000,650733317484.000000,23740430264.000000
884,TSC,TSC,2018-03-31,Q,N,1601981625116.000000,4967845115.000000,238642416723.000000,0.000000,33439106369.000000,1309717709981.000000,5887867567.000000
1282,DUS,DUS,2018-06-30,Q,N,32637197050.000000,0.000000,30002255445.000000,0.000000,760403259.000000,608015024.000000,1126123322.000000
1415,HTN,HTN,2018-06-30,Q,Y,139236608420.000000,28700000000.000000,36381259078.000000,0.000000,0.000000,32494344015.000000,11810389889.000000
1453,ITD,ITD,2018-06-30,Q,N,98904492966.000000,5114722803.000000,71714314291.000000,15109896264.000000,491833848.000000,425000000.000000,5120663433.000000
1714,PVM,PVM,2018-06-30,Q,Y,279394034816.000000,2235325841.000000,34368711860.000000,93056967.000000,10947234872.000000,186306363777.000000,38215206366.000000
1861,STS,STS,2018-06-30,Q,N,22190478613.000000,10000000.000000,22190478613.000000,0.000000,6599094.000000,0.000000,0.000000
1953,TSC,TSC,2018-06-30,Q,Y,1597278154592.000000,5000000.000000,235605304646.000000,0.000000,38862030376.000000,1308031378024.000000,5769371819.000000
2002,VCG,VCG,2018-06-30,Q,Y,8117219500012.000000,1099241433491.000000,2654199395584.000000,1631874063413.000000,1758560657642.000000,772928412003.000000,152714912611.000000
2294,DCL,DCL,2018-09-30,Q,N,574434685003.000000,2000000.000000,438870943618.000000,0.000000,4417332262.000000,87800000000.000000,7676142863.000000
2353,DUS,DUS,2018-09-30,Q,N,30739715506.000000,0.000000,29426358780.000000,0.000000,413976259.000000,608015024.000000,156065443.000000
2918,STG,STG,2018-09-30,Q,N,1219967368228.000000,2167994370.000000,650882995332.000000,0.000000,44508363498.000000,419957367237.000000,24947969735.000000
2956,TDH,TDH,2018-09-30,Q,N,2440391622345.000000,369925237340.000000,512412708645.000000,80872469662.000000,1082609294962.000000,372320913695.000000,16559360629.000000
3010,TSC,TSC,2018-09-30,Q,N,1580020956725.000000,5000000.000000,248996577200.000000,0.000000,23414445575.000000,1290364086637.000000,8557387219.000000
4238,ITD,ITD,2018-12-31,Y,N,96374735978.000000,5736716000.000000,68853711792.000000,16234168360.000000,222665000.000000,425000000.000000,4143151099.000000
4239,ITD,ITD,2018-12-31,Q,N,96374735978.000000,5736716000.000000,68853711792.000000,16234168360.000000,222665000.000000,425000000.000000,4143151099.000000
4354,LCG,LCG,2018-12-31,Q,N,1290130087312.000000,0.000000,369577585057.000000,0.000000,75652069644.000000,798057336171.000000,35105124195.000000
5189,STG,STG,2018-12-31,Q,N,1246212109148.000000,498327170.000000,652392860159.000000,0.000000,63308645522.000000,427975960849.000000,27096279492.000000
5281,TDH,TDH,2018-12-31,Q,N,2428035307092.000000,361338861727.000000,505658259866.000000,61310118771.000000,1064066878865.000000,394971517211.000000,22706285982.000000
5410,TSC,TSC,2018-12-31,Q,N,1574464054011.000000,15000000.000000,242427118512.000000,0.000000,24204762803.000000,1289268086569.000000,10187235666.000000
5411,TSC,TSC,2018-12-31,Y,Y,1574464054011.000000,15000000.000000,242427118512.000000,0.000000,24204762803.000000,1289268086569.000000,10187235666.000000
5983,DCL,DCL,2019-03-31,Q,N,486953928637.000000,2000000.000000,430590094220.000000,0.000000,4306952474.000000,10000000000.000000,11873586668.000000
6649,TDH,TDH,2019-03-31,Q,N,2358587449877.000000,280278540895.000000,498709141333.000000,60530105895.000000,1097968666618.000000,368102211942.000000,35486170253.000000
6704,TSC,TSC,2019-03-31,Q,N,1572254857244.000000,15000000.000000,239075397803.000000,0.000000,24734251783.000000,1289213293243.000000,11176673587.000000
6822,VPI,VPI,2019-03-31,Q,N,2893831370005.000000,1462075953156.000000,11408730706.000000,0.000000,759553996264.000000,631231966677.000000,24645128941.000000
7121,FCM,FCM,2019-06-30,Q,Y,207420655582.000000,2579548398.000000,200416955762.000000,133100000.000000,1648353957.000000,0.000000,2541947465.000000
7883,VPI,VPI,2019-06-30,Q,Y,2359085068886.000000,1028325183264.000000,19087853362.000000,0.000000,689772969626.000000,545562560217.000000,66057520211.000000
8336,ITD,ITD,2019-09-30,Q,N,94936790048.000000,5856016000.000000,64956589257.000000,18214478699.000000,333602648.000000,0.000000,5069887617.000000
8722,STG,STG,2019-09-30,Q,N,1197667890643.000000,13665322966.000000,686672056534.000000,0.000000,20407249092.000000,384379398908.000000,25291753487.000000
8933,VPI,VPI,2019-09-30,Q,N,2616091088152.000000,1067423416021.000000,21876165669.000000,0.000000,883335248550.000000,555168256476.000000,81981523772.000000
9210,C21,C21,2019-12-31,Y,Y,437750357244.000000,135921255413.000000,122286376994.000000,7570184746.000000,148729953229.000000,800000000.000000,21306954563.000000
9673,FPT,FPT,2019-12-31,Y,Y,14414988134764.000000,262484590350.000000,7492167954088.000000,0.000000,1650470873492.000000,2496552054488.000000,2287383247074.000000
11044,TCO,TCO,2019-12-31,Q,N,102931609680.000000,3145239293.000000,92282086617.000000,785200660.000000,0.000000,0.000000,2105401959.000000
11476,VPI,VPI,2019-12-31,Q,N,2747836579061.000000,1136639456669.000000,381075721184.000000,0.000000,182462237123.000000,559465456761.000000,485859734202.000000
11666,C21,C21,2020-03-31,Q,N,515976477154.000000,136505712975.000000,138996593886.000000,7291797526.000000,135225560701.000000,75800000000.000000,21080949888.000000
12369,STG,STG,2020-03-31,Q,N,1265914237245.000000,6705091195.000000,724759661802.000000,0.000000,56000695630.000000,383508181028.000000,32813782134.000000
12407,TDH,TDH,2020-03-31,Q,N,2840801231445.000000,682007387264.000000,469499750853.000000,90825333945.000000,920241998396.000000,623968723057.000000,39758410710.000000
12889,FPT,FPT,2020-06-30,Q,Y,14938070369160.000000,348427785518.000000,7365996280591.000000,0.000000,2233265003791.000000,2451568314545.000000,2325398922216.000000
13938,FPT,FPT,2020-09-30,Q,N,15284122357685.000000,371632861351.000000,7238790571133.000000,0.000000,2619085803954.000000,2529556438447.000000,2318332539037.000000
15388,FCM,FCM,2020-12-31,Y,Y,177448497543.000000,2648598398.000000,152795185440.000000,864700000.000000,20425740827.000000,0.000000,637897878.000000
15391,FCN,FCN,2020-12-31,Q,N,1198110017994.000000,48082541598.000000,674517511500.000000,0.000000,45205534272.000000,303763816009.000000,74388972330.000000
15778,ITD,ITD,2020-12-31,Y,N,103655556521.000000,5829069695.000000,68087377369.000000,18028936731.000000,328598902.000000,7367100000.000000,3930104497.000000
15779,ITD,ITD,2020-12-31,Q,N,103655556521.000000,5829069695.000000,68087377369.000000,18028936731.000000,328598902.000000,7367100000.000000,3930104497.000000
17505,DFF,DFF,2021-03-31,Q,N,718740979712.000000,18540521472.000000,512209485824.000000,0.000000,77720172761.000000,0.000000,110270783488.000000
18748,HSG,HSG,2021-06-30,Q,N,7975077937152.000000,174529888256.000000,6905427132416.000000,0.000000,536337337180.000000,21472159744.000000,337311924224.000000
18851,LDW,LDW,2021-06-30,Q,Y,856571969536.000000,728036608.000000,807814234112.000000,0.000000,7359427703.000000,11125252096.000000,29544984576.000000
18860,LLM,LLM,2021-06-30,Q,N,966562873344.000000,9585300480.000000,182955868160.000000,21188380672.000000,41001732180.000000,628618428416.000000,83213189120.000000
19049,PVA,PVA,2021-06-30,Q,N,117569945600.000000,102721708032.000000,11133306880.000000,0.000000,1090113570.000000,1956822912.000000,668000000.000000
19173,SPD,SPD,2021-06-30,Q,N,84589166592.000000,0.000000,63551983616.000000,0.000000,50000000.000000,20987176960.000000,0.000000
19271,TNH,TNH,2021-06-30,Q,Y,1029612044288.000000,0.000000,899010068480.000000,24423014400.000000,0.000000,74699997184.000000,31478988800.000000
19346,VEF,VEF,2021-06-30,Q,N,2530786410496.000000,1262883569664.000000,176442016.000000,0.000000,1267475476261.000000,0.000000,250805088.000000
19347,VET,VET,2021-06-30,Q,N,440736022528.000000,365641824.000000,204484820992.000000,0.000000,22207109123.000000,201500000256.000000,12178440192.000000
19427,VTX,VTX,2021-06-30,Q,N,177314971648.000000,2616741376.000000,157805101056.000000,0.000000,1954500259.000000,816000000.000000,14122628096.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23572,LAW,LAW,2022-03-31,Q,N,262930904488.000000,0.000000,243929595881.000000,0.000000,17088023151.000000,0.000000,1135164296.000000

In [18]:
cbs.check_cbs_210(df=df)

CHECK ITEM & SUB-ITEMS CBS_210

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_210,CBS_211,CBS_212,CBS_213,CBS_214,CBS_215,CBS_216,CBS_219
1861,STS,STS,2018-06-30,Q,N,10000000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17892,NVL,NVL,2021-03-31,Q,N,19721144918117.000000,NaN,NaN,NaN,NaN,175500000000.000000,19545644918117.000000,NaN
19346,VEF,VEF,2021-06-30,Q,N,1262883569664.000000,0.000000,0.000000,0.000000,0.000000,1250000000000.000000,12883561472.000000,0.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
cbs.check_cbs_220(df=df)

CHECK ITEM & SUB-ITEMS CBS_220

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_220,CBS_221,CBS_224,CBS_227
110,CDP,CDP,2018-03-31,Q,N,193254043163.000000,43495258702.000000,0.000000,57988983704.000000
237,DUS,DUS,2018-03-31,Q,N,27840555213.000000,27840555213.000000,0.000000,63500000.000000
1282,DUS,DUS,2018-06-30,Q,N,30002255445.000000,30002255445.000000,0.000000,140400000.000000
2353,DUS,DUS,2018-09-30,Q,N,29426358780.000000,29426358780.000000,0.000000,135300000.000000
3465,CDP,CDP,2018-12-31,Q,N,191053912179.000000,133346037381.000000,0.000000,56997289798.000000
4081,HNF,HNF,2018-12-31,Q,N,224067948425.000000,141735819640.000000,15089955750.000000,0.000000
6401,PEG,PEG,2019-03-31,Q,N,709350143394.000000,344947662931.000000,0.000000,300108795760.000000
12840,DRC,DRC,2020-06-30,Q,Y,1130181648351.000000,1124774855156.000000,1607848514.000000,3798944675.000000
16367,PTO,PTO,2020-12-31,Y,Y,1126097186.000000,1126097186.000000,0.000000,265565930.000000
17505,DFF,DFF,2021-03-31,Q,N,512209485824.000000,387677323264.000000,116705550336.000000,7826638336.000000
18748,HSG,HSG,2021-06-30,Q,N,6905427132416.000000,6692305633280.000000,0.000000,213121089536.000000
18851,LDW,LDW,2021-06-30,Q,Y,807814234112.000000,806318374912.000000,0.000000,1495889408.000000
18860,LLM,LLM,2021-06-30,Q,N,182955868160.000000,146613403648.000000,19928528896.000000,16413929472.000000
19173,SPD,SPD,2021-06-30,Q,N,63551983616.000000,60512301056.000000,0.000000,3039683328.000000
19271,TNH,TNH,2021-06-30,Q,Y,899010068480.000000,886977527808.000000,0.000000,12032536576.000000
19427,VTX,VTX,2021-06-30,Q,N,157805101056.000000,72754126848.000000,77426638848.000000,7624332800.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN

In [20]:
cbs.check_cbs_221(df=df)

CHECK ITEM & SUB-ITEMS CBS_221

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_221,CBS_222,CBS_223
17505,DFF,DFF,2021-03-31,Q,N,387677323264.000000,584147730432.000000,-196470423552.000000
18748,HSG,HSG,2021-06-30,Q,N,6692305633280.000000,13637271945216.000000,-6944966836224.000000
19173,SPD,SPD,2021-06-30,Q,N,60512301056.000000,233186770944.000000,-172674465792.000000
19271,TNH,TNH,2021-06-30,Q,Y,886977527808.000000,938709024768.000000,-51731501056.000000
19346,VEF,VEF,2021-06-30,Q,N,176442016.000000,5522680320.000000,-5346238464.000000
19347,VET,VET,2021-06-30,Q,N,204484820992.000000,528857890816.000000,-324373053440.000000
19427,VTX,VTX,2021-06-30,Q,N,72754126848.000000,514942140416.000000,-442188005376.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [21]:
cbs.check_cbs_224(df=df)

CHECK ITEM & SUB-ITEMS CBS_224

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_224,CBS_225,CBS_226
17505,DFF,DFF,2021-03-31,Q,N,116705550336.000000,128120905728.000000,-11415356416.000000
17692,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN
17892,NVL,NVL,2021-03-31,Q,N,0.000000,NaN,NaN
18860,LLM,LLM,2021-06-30,Q,N,19928528896.000000,26999052288.000000,-7070524928.000000
19427,VTX,VTX,2021-06-30,Q,N,77426638848.000000,77859192832.000000,-432551072.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [22]:
cbs.check_cbs_227(df=df)

CHECK ITEM & SUB-ITEMS CBS_227

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_227,CBS_228,CBS_229
237,DUS,DUS,2018-03-31,Q,N,63500000.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,140400000.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,135300000.000000,0.000000,0.000000
17505,DFF,DFF,2021-03-31,Q,N,7826638336.000000,11299505152.000000,-3472866560.000000
17692,HSV,HSV,2021-03-31,Q,N,466904696.000000,466904696.000000,NaN
18748,HSG,HSG,2021-06-30,Q,N,213121089536.000000,285209952256.000000,-72088879104.000000
18851,LDW,LDW,2021-06-30,Q,Y,1495889408.000000,1903591040.000000,-407701568.000000
18860,LLM,LLM,2021-06-30,Q,N,16413929472.000000,18370095104.000000,-1956165248.000000
19427,VTX,VTX,2021-06-30,Q,N,7624332800.000000,9498251264.000000,-1873918976.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [23]:
cbs.check_cbs_230(df=df)

CHECK ITEM & SUB-ITEMS CBS_230

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_230,CBS_231,CBS_232
17692,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN
18860,LLM,LLM,2021-06-30,Q,N,21188380672.000000,57127964672.000000,-35939581952.000000
19271,TNH,TNH,2021-06-30,Q,Y,24423014400.000000,24915812352.000000,-492797600.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [24]:
cbs.check_cbs_230(df=df)

CHECK ITEM & SUB-ITEMS CBS_230

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_230,CBS_231,CBS_232
17692,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN
18860,LLM,LLM,2021-06-30,Q,N,21188380672.000000,57127964672.000000,-35939581952.000000
19271,TNH,TNH,2021-06-30,Q,Y,24423014400.000000,24915812352.000000,-492797600.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [25]:
cbs.check_cbs_240(df=df)

CHECK ITEM & SUB-ITEMS CBS_240

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_240,CBS_241,CBS_242
237,DUS,DUS,2018-03-31,Q,N,2141248986.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,760403259.000000,0.000000,0.000000
1861,STS,STS,2018-06-30,Q,N,6599094.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,413976259.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [26]:
cbs.check_cbs_250(df=df)

CHECK ITEM & SUB-ITEMS CBS_250

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_250,CBS_251,CBS_252,CBS_253,CBS_254,CBS_255,CBS_2691
237,DUS,DUS,2018-03-31,Q,N,608015024.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
256,FCN,FCN,2018-03-31,Q,N,208291590784.000000,0.000000,208291590784.000000,0.000000,0.000000,0.000000,96400000.000000
453,LCG,LCG,2018-03-31,Q,N,650733317484.000000,0.000000,117288492129.000000,508785305856.000000,0.000000,24659519499.000000,11927972245.000000
884,TSC,TSC,2018-03-31,Q,N,1309717709981.000000,0.000000,770735529981.000000,26982180000.000000,512000000000.000000,0.000000,9326679361.000000
1282,DUS,DUS,2018-06-30,Q,N,608015024.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1415,HTN,HTN,2018-06-30,Q,Y,32494344015.000000,0.000000,32494344015.000000,0.000000,0.000000,0.000000,29850615438.000000
1453,ITD,ITD,2018-06-30,Q,N,425000000.000000,0.000000,0.000000,0.000000,0.000000,425000000.000000,928062327.000000
1714,PVM,PVM,2018-06-30,Q,Y,186306363777.000000,0.000000,574532035.000000,189168719573.000000,-3436887831.000000,0.000000,7228135133.000000
1953,TSC,TSC,2018-06-30,Q,Y,1308031378024.000000,0.000000,770079198024.000000,25952180000.000000,0.000000,512000000000.000000,9005069727.000000
2002,VCG,VCG,2018-06-30,Q,Y,772928412003.000000,0.000000,591205168930.000000,208418415600.000000,-66695172527.000000,40000000000.000000,47700625268.000000
2294,DCL,DCL,2018-09-30,Q,N,87800000000.000000,0.000000,0.000000,0.000000,0.000000,87800000000.000000,35668266260.000000
2353,DUS,DUS,2018-09-30,Q,N,608015024.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2918,STG,STG,2018-09-30,Q,N,419957367237.000000,0.000000,407358442598.000000,1629124639.000000,0.000000,10969800000.000000,77502678056.000000
2956,TDH,TDH,2018-09-30,Q,N,372320913695.000000,0.000000,192045541475.000000,180725372220.000000,-450000000.000000,0.000000,5691637412.000000
3010,TSC,TSC,2018-09-30,Q,N,1290364086637.000000,0.000000,752411906637.000000,25952180000.000000,0.000000,512000000000.000000,8683460094.000000
4238,ITD,ITD,2018-12-31,Y,N,425000000.000000,0.000000,0.000000,0.000000,0.000000,425000000.000000,759323727.000000
4239,ITD,ITD,2018-12-31,Q,N,425000000.000000,0.000000,0.000000,0.000000,0.000000,425000000.000000,759323727.000000
4354,LCG,LCG,2018-12-31,Q,N,798057336171.000000,0.000000,286000786671.000000,487397030000.000000,0.000000,24659519500.000000,11737972245.000000
5189,STG,STG,2018-12-31,Q,N,427975960849.000000,0.000000,410754336210.000000,1629124639.000000,0.000000,15592500000.000000,74940035956.000000
5281,TDH,TDH,2018-12-31,Q,N,394971517211.000000,0.000000,193696144991.000000,201725372220.000000,-450000000.000000,0.000000,17983384670.000000
5410,TSC,TSC,2018-12-31,Q,N,1289268086569.000000,0.000000,751315906569.000000,25952180000.000000,0.000000,512000000000.000000,8361850461.000000
5411,TSC,TSC,2018-12-31,Y,Y,1289268086569.000000,0.000000,751315906569.000000,25952180000.000000,0.000000,512000000000.000000,8361850461.000000
5983,DCL,DCL,2019-03-31,Q,N,10000000000.000000,0.000000,0.000000,10000000000.000000,0.000000,0.000000,30181295275.000000
6649,TDH,TDH,2019-03-31,Q,N,368102211942.000000,0.000000,181095748603.000000,190446372220.000000,-3439908881.000000,0.000000,17512612941.000000
6704,TSC,TSC,2019-03-31,Q,N,1289213293243.000000,0.000000,751261113243.000000,25952180000.000000,0.000000,512000000000.000000,8040240828.000000
6822,VPI,VPI,2019-03-31,Q,N,631231966677.000000,0.000000,540931966677.000000,90300000000.000000,0.000000,0.000000,4915594261.000000
7121,FCM,FCM,2019-06-30,Q,Y,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100750000.000000
7883,VPI,VPI,2019-06-30,Q,Y,545562560217.000000,0.000000,545562560217.000000,0.000000,0.000000,0.000000,10278982206.000000
8336,ITD,ITD,2019-09-30,Q,N,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,506215827.000000
8722,STG,STG,2019-09-30,Q,N,384379398908.000000,0.000000,371545118460.000000,1629124639.000000,0.000000,11205155809.000000,67252109656.000000
8933,VPI,VPI,2019-09-30,Q,N,555168256476.000000,0.000000,555168256476.000000,0.000000,0.000000,0.000000,6306477664.000000
9210,C21,C21,2019-12-31,Y,Y,800000000.000000,0.000000,800000000.000000,6750000000.000000,-6750000000.000000,0.000000,1135632299.000000
9673,FPT,FPT,2019-12-31,Y,Y,2496552054488.000000,0.000000,1912712694571.000000,893623994517.000000,-309784634600.000000,0.000000,225929415272.000000
11044,TCO,TCO,2019-12-31,Q,N,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4613681151.000000
11476,VPI,VPI,2019-12-31,Q,N,559465456761.000000,0.000000,559465456761.000000,0.000000,0.000000,0.000000,2333973122.000000
11666,C21,C21,2020-03-31,Q,N,75800000000.000000,0.000000,75800000000.000000,6750000000.000000,-6750000000.000000,0.000000,1075862178.000000
12369,STG,STG,2020-03-31,Q,N,383508181028.000000,0.000000,351772708466.000000,1629124639.000000,0.000000,30106347923.000000,62126825456.000000
12407,TDH,TDH,2020-03-31,Q,N,623968723057.000000,0.000000,317672350837.000000,306746372220.000000,-450000000.000000,0.000000,14499627220.000000
12889,FPT,FPT,2020-06-30,Q,Y,2451568314545.000000,0.000000,1890355276994.000000,865250071864.000000,-304037034313.000000,0.000000,213414062499.000000
13938,FPT,FPT,2020-09-30,Q,N,2529556438447.000000,0.000000,1910490057651.000000,922165806267.000000,-303299425471.000000,200000000.000000,206724143763.000000
15388,FCM,FCM,2020-12-31,Y,Y,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,76375000.000000
15391,FCN,FCN,2020-12-31,Q,N,303763816009.000000,0.000000,188633242500.000000,114630573509.000000,0.000000,500000000.000000,52151642285.000000
15441,GEX,GEX,2020-12-31,Q,N,5798321861657.000000,0.000000,5673889499998.000000,124370401581.000000,0.000000,625000000.000000,0.000000
15778,ITD,ITD,2020-12-31,Y,N,7367100000.000000,0.000000,0.000000,7367100000.000000,0.000000,0.000000,84369327.000000
15779,ITD,ITD,2020-12-31,Q,N,7367100000.000000,0.000000,0.000000,7367100000.000000,0.000000,0.000000,84369327.000000
17692,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
17892,NVL,NVL,2021-03-31,Q,N,1785629241980.000000,NaN,1644265421980.000000,25349750000.000000,116014070000.000000,NaN,0.000000
18748,HSG,HSG,2021-06-30,Q,N,21472159744.000000,0.000000,0.000000,0.000000,0.000000,21472160000.000000,0.000000
18860,LLM,LLM,2021-06-30,Q,N,628618428416.000000,0.000000,396147261440.000000,255227052032.000000,-23075930112.000000,320000000.000000,0.000000
19173,SPD,SPD,2021-06-30,Q,N,20987176960.000000,0.000000,18365569024.000000,2121607424.000000,0.000000,500000000.000000,0.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [27]:
cbs.check_cbs_260(df=df)

CHECK ITEM & SUB-ITEMS CBS_260

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_260,CBS_261,CBS_262,CBS_263,CBS_268,CBS_269
237,DUS,DUS,2018-03-31,Q,N,156065443.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,1126123322.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,156065443.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,338915725.000000,338915725.000000,NaN,NaN,NaN,NaN
17892,NVL,NVL,2021-03-31,Q,N,6337015379549.000000,487633399414.000000,104053368742.000000,NaN,NaN,5745328611393.000000
18748,HSG,HSG,2021-06-30,Q,N,337311924224.000000,222931845120.000000,114380087296.000000,0.000000,0.000000,0.000000
18851,LDW,LDW,2021-06-30,Q,Y,29544984576.000000,20544944128.000000,0.000000,9000040985.000000,0.000000,0.000000
18860,LLM,LLM,2021-06-30,Q,N,83213189120.000000,83072131072.000000,0.000000,0.000000,0.000000,141057065.000000
19346,VEF,VEF,2021-06-30,Q,N,250805088.000000,22908142.000000,227896944.000000,0.000000,0.000000,0.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
cbs.check_cbs_300(df=df)

CHECK ITEM & SUB-ITEMS CBS_300

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_300,CBS_310,CBS_330
17505,DFF,DFF,2021-03-31,Q,N,1342178983936.000000,994412986368.000000,347766063104.000000
18748,HSG,HSG,2021-06-30,Q,N,15305000615936.000000,13666262974464.000000,1638738165760.000000
18851,LDW,LDW,2021-06-30,Q,Y,315485913088.000000,72848343040.000000,242637586432.000000
18860,LLM,LLM,2021-06-30,Q,N,6233380618240.000000,6208592281600.000000,24788072448.000000
19173,SPD,SPD,2021-06-30,Q,N,318907121664.000000,308902920192.000000,10004196352.000000
19271,TNH,TNH,2021-06-30,Q,Y,547253256192.000000,188327968768.000000,358925271040.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [29]:
cbs.check_cbs_310(df=df)

CHECK ITEM & SUB-ITEMS CBS_310

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_310,CBS_311,CBS_312,CBS_313,CBS_314,CBS_315,CBS_316,CBS_317,CBS_318,CBS_319,CBS_320,CBS_321,CBS_322,CBS_323,CBS_324
237,DUS,DUS,2018-03-31,Q,N,21250210216.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,40989951976.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1861,STS,STS,2018-06-30,Q,N,24584961017.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,33612409534.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7103,DUS,DUS,2019-06-30,Q,Y,36165661993.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14809,BBC,BBC,2020-12-31,Q,N,316050505485.000000,12188361330.000000,7593682693.000000,10295066593.000000,4433797639.000000,86337353511.000000,0.000000,0.000000,0.000000,5405907865.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16775,TCK,TCK,2020-12-31,Q,N,988013198200.000000,118091055136.000000,162673031731.000000,138579607776.000000,14985229054.000000,209361640589.000000,0.000000,0.000000,4002500028.000000,187954981485.000000,160296454766.000000,806389478.000000,385816786.000000,0.000000,0.000000
17505,DFF,DFF,2021-03-31,Q,N,994412986368.000000,312701452288.000000,51239698432.000000,14865824768.000000,0.000000,12000000.000000,0.000000,0.000000,0.000000,49296064512.000000,566297952256.000000,0.000000,0.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,17926616277.000000,542495962.000000,0.000000,508712215.000000,180637000.000000,NaN,NaN,NaN,NaN,0.000000,16694771100.000000,NaN,NaN,NaN,NaN
17892,NVL,NVL,2021-03-31,Q,N,35418652059614.000000,2676359388907.000000,5373051850224.000000,766624343283.000000,26146310784.000000,5248137197450.000000,NaN,NaN,5196639564.000000,4691629725750.000000,16608633013789.000000,17324724568.000000,5548865295.000000,NaN,NaN
18748,HSG,HSG,2021-06-30,Q,N,13666262974464.000000,3461131010048.000000,320003899392.000000,586979999744.000000,72154284032.000000,239609774080.000000,0.000000,0.000000,0.000000,3450182828032.000000,5451456970752.000000,0.000000,84743725056.000000,0.000000,0.000000
18851,LDW,LDW,2021-06-30,Q,Y,72848343040.000000,13569855488.000000,627972288.000000,4823732224.000000,8517284864.000000,2643337472.000000,0.000000,0.000000,0.000000,10309886976.000000,22793678848.000000,0.000000,9562599424.000000,0.000000,0.000000
18860,LLM,LLM,2021-06-30,Q,N,6208592281600.000000,3830724952064.000000,146532761600.000000,26176882688.000000,38128750592.000000,479796854784.000000,0.000000,0.000000,893927824.000000,125189136384.000000,1479769325568.000000,12796059648.000000,68583608320.000000,0.000000,0.000000
19049,PVA,PVA,2021-06-30,Q,N,441669844992.000000,121349980160.000000,86357098496.000000,10112602112.000000,6296355328.000000,31030716416.000000,0.000000,10801668096.000000,0.000000,119645396992.000000,35991064576.000000,0.000000,20084951040.000000,0.000000,0.000000
19173,SPD,SPD,2021-06-30,Q,N,308902920192.000000,17397237760.000000,70000000.000000,24801182.000000,3263002880.000000,1525882368.000000,0.000000,0.000000,430223264.000000,93030424576.000000,191862554624.000000,0.000000,1298787584.000000,0.000000,0.000000
19271,TNH,TNH,2021-06-30,Q,Y,188327968768.000000,40254832640.000000,926926528.000000,1009694848.000000,4983936000.000000,907594496.000000,0.000000,0.000000,0.000000,820796672.000000,139424186368.000000,0.000000,0.000000,0.000000,0.000000
19346,VEF,VEF,2021-06-30,Q,N,4935448002560.000000,1432951936.000000,130483616.000000,32177762304.000000,628488704.000000,0.000000,0.000000,0.000000,238310214.000000,4900840275968.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19347,VET,VET,2021-06-30,Q,N,285794435072.000000,55187443712.000000,2500818688.000000,-2525091584.000000,0.000000,0.000000,0.000000,0.000000,53623192569.000000,173182664704.000000,0.000000,10982560768.000000,-7157148672.000000,0.000000,0.000000
19427,VTX,VTX,2021-06-30,Q,N,205150666752.000000,49053200384.000000,58949419008.000000,489554560.000000,4026894848.000000,28623296512.000000,0.000000,0.000000,0.000000,7924207616.000000,56050565120.000000,0.000000,33521788.000000,0.000000,0.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24902,SBR,SBR,2022-06-30,Q,Y,162547226935.000000,4196658397.000000,5961409795.000000,29613076947.000000,9464843829.000000,52500000.000000,0.000000,0.000000,0.000000,14711642049.000000,0.000000,0.000000,98217095918.000000,0.000000,0.000000
26139,TNH,TNH,2022-09-30,Q,N,269858196269.000000,25015412936.000000,3233235389.000000,1919289578.000000,7443818177.000000,0.000000,0.000000,0.000000,0.000000,0.000000,232212225987.000000,0.000000,0.000000,0.000000,0.000000
28077,SDC,SDC,2022-12-31,Q,N,31911212440.000000,2212053792.000000,7542417550.000000,645332161.000000,8595678076.000000,80009091.000000,0.000000,0.000000,0.000000,7937588547.000000,3616075400.000000,0.000000,1226502267.000000,0.000000,0.000000

In [30]:
cbs.check_cbs_330(df=df)

CHECK ITEM & SUB-ITEMS CBS_330

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_330,CBS_331,CBS_332,CBS_333,CBS_334,CBS_335,CBS_336,CBS_337,CBS_338,CBS_339,CBS_340,CBS_341,CBS_342,CBS_343
216,DPG,DPG,2018-03-31,Q,N,1757071197608.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,43073236000.000000,1691356878731.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325,HIG,HIG,2018-03-31,Q,N,4240615093.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1044257442.000000,0.000000,0.000000,0.000000,149455892.000000,0.000000,0.000000
357,HSM,HSM,2018-03-31,Q,N,636423133000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,561597505430.000000,0.000000,0.000000,6724232274.000000,0.000000,100110331.000000
400,ITD,ITD,2018-03-31,Q,Y,30617143166.000000,0.000000,0.000000,104805400.000000,0.000000,0.000000,229914888.000000,322008526.000000,0.000000,0.000000,0.000000,3111800000.000000,0.000000,1940049372.000000
452,LCD,LCD,2018-03-31,Q,N,9184190418.000000,1386572823.000000,0.000000,0.000000,0.000000,0.000000,0.000000,801519233.000000,1450787000.000000,0.000000,0.000000,0.000000,0.000000,0.000000
610,PLX,PLX,2018-03-31,Q,N,2628600887633.000000,0.000000,10676460920.000000,1097675105.000000,0.000000,0.000000,15637661850.000000,164079420370.000000,2390670966127.000000,0.000000,0.000000,5777229887.000000,0.000000,3065761000.000000
1003,VPH,VPH,2018-03-31,Q,N,182566685133.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,62269200.000000,181954165933.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,189134089.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1407,HSM,HSM,2018-06-30,Q,Y,631933317319.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,556349026984.000000,0.000000,0.000000,7497911588.000000,0.000000,85093782.000000
1505,LCD,LCD,2018-06-30,Q,Y,10944680251.000000,1386572823.000000,0.000000,0.000000,0.000000,0.000000,0.000000,583491566.000000,3429304500.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1861,STS,STS,2018-06-30,Q,N,240000000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2075,VPH,VPH,2018-06-30,Q,Y,180566685133.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,62269200.000000,179954165933.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2475,HSM,HSM,2018-09-30,Q,N,630032682035.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,555237087562.000000,0.000000,0.000000,6724232274.000000,0.000000,70077234.000000
2573,LCD,LCD,2018-09-30,Q,N,11648869725.000000,1386572823.000000,0.000000,0.000000,0.000000,0.000000,0.000000,583491566.000000,4263539500.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3131,VPH,VPH,2018-09-30,Q,N,180504415933.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,179954165933.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3737,DPG,DPG,2018-12-31,Q,N,1920808035212.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,45626005021.000000,1862885394145.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3738,DPG,DPG,2018-12-31,Y,Y,1981294115840.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,45626005021.000000,1923371474773.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4125,HSM,HSM,2018-12-31,Q,N,625899670544.000000,0.000000,0.000000,0.000000,0.000000,0.000000,886362687.000000,0.000000,550232729936.000000,0.000000,0.000000,6724232274.000000,0.000000,55060682.000000
4582,NLG,NLG,2018-12-31,Q,N,1596286318532.000000,0.000000,0.000000,0.000000,0.000000,0.000000,718151289307.000000,9100824610.000000,805983254317.000000,0.000000,0.000000,12180096634.000000,0.000000,0.000000
4583,NLG,NLG,2018-12-31,Y,Y,1596286318532.000000,0.000000,0.000000,0.000000,0.000000,0.000000,718151289307.000000,9100824610.000000,805983254317.000000,0.000000,0.000000,12180096634.000000,0.000000,0.000000
4672,PC1,PC1,2018-12-31,Q,N,1578419839168.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2755446321.000000,1553956591681.000000,0.000000,0.000000,11613705190.000000,0.000000,0.000000
4673,PC1,PC1,2018-12-31,Y,Y,1576712596353.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1048203506.000000,1553956591681.000000,0.000000,0.000000,11613705190.000000,0.000000,0.000000
6022,DPG,DPG,2019-03-31,Q,N,1970204935016.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,49368515021.000000,1908539783949.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6355,NLG,NLG,2019-03-31,Q,N,1666717578766.000000,0.000000,0.000000,0.000000,0.000000,0.000000,714345357626.000000,9138870692.000000,639221615157.000000,0.000000,0.000000,253215734543.000000,0.000000,0.000000
7083,DPG,DPG,2019-06-30,Q,Y,1853689033617.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,49837515021.000000,1803167428855.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7103,DUS,DUS,2019-06-30,Q,Y,129175003.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7143,GEX,GEX,2019-06-30,Q,Y,3410078308510.000000,0.000000,0.000000,0.000000,0.000000,0.000000,44187127558.000000,38694876132.000000,3084059212376.000000,0.000000,0.000000,167572946754.000000,0.000000,0.000000
7417,NLG,NLG,2019-06-30,Q,Y,1909046106895.000000,0.000000,0.000000,0.000000,0.000000,0.000000,762472444933.000000,73083356985.000000,769857105800.000000,0.000000,0.000000,253325535254.000000,0.000000,0.000000
8139,DPG,DPG,2019-09-30,Q,N,2002952701910.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,55490515021.000000,1946778097148.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8472,NLG,NLG,2019-09-30,Q,N,1966781162549.000000,0.000000,0.000000,0.000000,0.000000,0.000000,772559925428.000000,100625094809.000000,791521328093.000000,0.000000,0.000000,252344477587.000000,0.000000,0.000000
10665,PVX,PVX,2019-12-31,Q,N,279722249459.000000,0.000000,0.000000,76558042948.000000,0.000000,0.000000,87091612061.000000,24480680638.000000,89449936014.000000,0.000000,0.000000,2015851650.000000,0.000000,0.000000
13325,SAB,SAB,2020-06-30,Q,Y,844250361848.000000,88793875350.000000,22183449.000000,0.000000,0.000000,0.000000,0.000000,54010016000.000000,459456327274.000000,0.000000,0.000000,0.000000,127298621349.000000,81700729929.000000
14720,ACC,ACC,2020-12-31,Q,N,47007951476.000000,0.000000,0.000000,32946001502.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,326114941.000000,0.000000,0.000000
14721,ACC,ACC,2020-12-31,Y,Y,41376446754.000000,0.000000,0.000000,27455001251.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,185610470.000000,0.000000,0.000000
15311,DTD,DTD,2020-12-31,Q,N,1213759729798.000000,0.000000,0.000000,948349855026.000000,0.000000,0.000000,24807776000.000000,78608242000.000000,0.000000,0.000000,0.000000,640753185.000000,0.000000,0.000000
15462,GMC,GMC,2020-12-31,Q,N,16375015014.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7354595514.000000,0.000000,0.000000
15463,GMC,GMC,2020-12-31,Y,Y,16375015014.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7354595514.000000,0.000000,0.000000
15788,KBC,KBC,2020-12-31,Y,Y,6170686623560.000000,0.000000,0.000000,1134633021863.000000,0.000000,0.000000,4664114060.000000,35537754956.000000,4218161587925.000000,0.000000,0.000000,776738176794.000000,0.000000,0.000000
15789,KBC,KBC,2020-12-31,Q,N,6107539517181.000000,0.000000,0.000000,1074837878371.000000,0.000000,0.000000,4664114060.000000,31820359756.000000,4218161587925.000000,0.000000,0.000000,777103609107.000000,0.000000,0.000000
16380,PVC,PVC,2020-12-31,Y,Y,34882930213.000000,0.000000,0.000000,0.000000,0.000000,0.000000,312000000.000000,140200000.000000,0.000000,0.000000,0.000000,2553931176.000000,0.000000,0.000000
16381,PVC,PVC,2020-12-31,Q,N,13793118839.000000,0.000000,0.000000,0.000000,0.000000,0.000000,312000000.000000,140200000.000000,0.000000,0.000000,0.000000,2546382889.000000,0.000000,0.000000
16775,TCK,TCK,2020-12-31,Q,N,14241246637.000000,0.000000,0.000000,0.000000,0.000000,0.000000,929137116.000000,41150000.000000,4632512898.000000,0.000000,0.000000,373403093.000000,0.000000,0.000000
16861,TL4,TL4,2020-12-31,Q,N,266357051533.000000,0.000000,47635612447.000000,0.000000,0.000000,0.000000,0.000000,131063400000.000000,73058384858.000000,0.000000,0.000000,972730000.000000,0.000000,0.000000
16862,TL4,TL4,2020-12-31,Y,Y,266357051533.000000,0.000000,47635612447.000000,0.000000,0.000000,0.000000,0.000000,131063400000.000000,73058384858.000000,0.000000,0.000000,972730000.000000,0.000000,0.000000
17321,ACC,ACC,2021-03-31,Q,N,10910181576.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,185610470.000000,0.000000,0.000000
17505,DFF,DFF,2021-03-31,Q,N,347766063104.000000,104031051776.000000,0.000000,0.000000,0.000000,0.000000,0.000000,410000000.000000,243325009920.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17554,DTD,DTD,2021-03-31,Q,N,941620957977.000000,0.000000,0.000000,694144800378.000000,0.000000,0.000000,49848214793.000000,27708242000.000000,0.000000,0.000000,0.000000,1606680618.000000,0.000000,0.000000
17614,GMC,GMC,2021-03-31,Q,N,16072121810.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7167693893.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17744,KBC,KBC,2021-03-31,Q,N,6178358766991.000000,0.000000,0.000000,1194760831265.000000,0.000000,0.000000,4632208004.000000,30531288820.000000,4085865356568.000000,0.000000,0.000000,861617114372.000000,0.000000,0.000000
17892,NVL,NVL,2021-03-31,Q,N,80488681606332.000000,NaN,NaN,NaN,NaN,NaN,13812001719.000000,42500974723692.000000,28537305159101.000000,NaN,NaN,9303390966825.000000,133198754995.000000,NaN
18676,GMC,GMC,2021-06-30,Q,Y,15045573805.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6665356638.000000,0.000000,0.000000
18748,HSG,HSG,2021-06-30,Q,N,1638738165760.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,709500032.000000,1624262180864.000000,0.000000,0.000000,0.000000,13766513664.000000,0.000000
18851,LDW,LDW,2021-06-30,Q,Y,242637586432.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,502782112.000000,241712889856.000000,0.000000,0.000000,0.000000,0.000000,421909952.000000
18860,LLM,LLM,2021-06-30,Q,N,24788072448.000000,0.000000,0.000000,1588264116.000000,0.000000,0.000000,15914414080.000000,842586816.000000,871457984.000000,0.000000,0.000000,2787618816.000000,2783731200.000000,0.000000
19271,TNH,TNH,2021-06-30,Q,Y,358925271040.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7638181888.000000,0.000000,351287083008.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19346,VEF,VEF,2021-06-30,Q,N,713048981504.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,49000000.000000,713000026112.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19427,VTX,VTX,2021-06-30,Q,N,45857341440.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,139500000.000000,45717839872.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
cbs.check_cbs_400(df=df)

CHECK ITEM & SUB-ITEMS CBS_400

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_400,CBS_410,CBS_430
18851,LDW,LDW,2021-06-30,Q,Y,1172389625856.000000,864385433600.000000,308004159488.000000
18860,LLM,LLM,2021-06-30,Q,N,1082130890752.000000,1080236507136.000000,1894347520.000000
19347,VET,VET,2021-06-30,Q,N,358312968192.000000,335243771904.000000,23069173760.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,0.000000

In [32]:
cbs.check_cbs_410(df=df)

CHECK ITEM & SUB-ITEMS CBS_410

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_410,CBS_411,CBS_412,CBS_413,CBS_414,CBS_415,CBS_416,CBS_417,CBS_418,CBS_419,CBS_420,CBS_421,CBS_429
129,CMF,CMF,2018-03-31,Q,N,286984563602.000000,81000000000.000000,38500000000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,80301597960.000000,0.000000,0.000000,78125621159.000000,0.000000
237,DUS,DUS,2018-03-31,Q,N,77946830230.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
751,SHI,SHI,2018-03-31,Q,N,947848762895.000000,642324060000.000000,16061097352.000000,0.000000,0.000000,-4186322972.000000,0.000000,0.000000,0.000000,0.000000,0.000000,242159902543.000000,33186658691.000000
752,SHI,SHI,2018-03-31,Q,N,947848762895.000000,642324060000.000000,16061097352.000000,0.000000,0.000000,-4186322972.000000,0.000000,0.000000,0.000000,0.000000,0.000000,242159902543.000000,33186658691.000000
1174,CMF,CMF,2018-06-30,Q,N,289932674417.000000,81000000000.000000,38500000000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100301597960.000000,0.000000,0.000000,61073731974.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,69430548944.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2248,CMF,CMF,2018-09-30,Q,N,330709791794.000000,81000000000.000000,38500000000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100301597960.000000,0.000000,0.000000,101850849351.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,71689892598.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7103,DUS,DUS,2019-06-30,Q,Y,71442691242.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12452,TNI,TNI,2020-03-31,Q,N,708689349245.000000,525000000000.000000,3811400000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1393427931.000000,0.000000,0.000000,63574521314.000000,0.000000
15819,KMT,KMT,2020-12-31,Q,N,125952756467.000000,98465620000.000000,300347000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14355705817.000000,0.000000,0.000000,11340064961.000000,0.000000
15820,KMT,KMT,2020-12-31,Y,Y,125952756467.000000,98465620000.000000,300347000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14355705817.000000,0.000000,0.000000,11340064961.000000,0.000000
17505,DFF,DFF,2021-03-31,Q,N,472294457344.000000,399999991808.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,71994875904.000000,299593471.000000
17692,HSV,HSV,2021-03-31,Q,N,56464297994.000000,50000000000.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,6464297994.000000,NaN
17892,NVL,NVL,2021-03-31,Q,N,37758920568046.000000,10728120350000.000000,8234540694626.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,12588298117556.000000,6207961405864.000000
18748,HSG,HSG,2021-06-30,Q,N,9856003080192.000000,4446252171264.000000,157292544000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,98970607616.000000,5136785604608.000000,16702038776.000000
18851,LDW,LDW,2021-06-30,Q,Y,864385433600.000000,788000014336.000000,28512122880.000000,0.000000,11874131968.000000,0.000000,0.000000,0.000000,12863714304.000000,0.000000,0.000000,23135455232.000000,0.000000
18860,LLM,LLM,2021-06-30,Q,N,1080236507136.000000,797261037568.000000,0.000000,0.000000,1694624256.000000,0.000000,-32374321152.000000,-9637472256.000000,86487908352.000000,0.000000,18290852.000000,229250842624.000000,7535605319.000000
19049,PVA,PVA,2021-06-30,Q,N,-33843703808.000000,218459996160.000000,5000000000.000000,0.000000,380952384.000000,0.000000,0.000000,0.000000,23453681664.000000,0.000000,0.000000,-281138331648.000000,0.000000
19173,SPD,SPD,2021-06-30,Q,N,115153313792.000000,120000004096.000000,-101650000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11388233728.000000,0.000000,0.000000,-16133268480.000000,0.000000
19271,TNH,TNH,2021-06-30,Q,Y,687277932544.000000,415000002560.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,272277913600.000000,0.000000
19346,VEF,VEF,2021-06-30,Q,N,2122157260800.000000,1666040463360.000000,5288133120.000000,0.000000,0.000000,-30150000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,450858778624.000000,0.000000
19347,VET,VET,2021-06-30,Q,N,335243771904.000000,160000000000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,129267720192.000000,0.000000,0.000000,45976064000.000000,0.000000
19427,VTX,VTX,2021-06-30,Q,N,248886362112.000000,209723211776.000000,15257068544.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5352597504.000000,0.000000,0.000000,18553483264.000000,0.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
cbs.check_cbs_411(df=df)

CHECK ITEM & SUB-ITEMS CBS_411

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_411,CBS_411A,CBS_411B
237,DUS,DUS,2018-03-31,Q,N,0.000000,56143000000.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,0.000000,56143000000.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,0.000000,56143000000.000000,0.000000
7103,DUS,DUS,2019-06-30,Q,Y,0.000000,56143000000.000000,0.000000
17505,DFF,DFF,2021-03-31,Q,N,399999991808.000000,400000000000.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,50000000000.000000,50000000000.000000,NaN
17892,NVL,NVL,2021-03-31,Q,N,10728120350000.000000,10728120350000.000000,NaN
18748,HSG,HSG,2021-06-30,Q,N,4446252171264.000000,4446252130000.000000,0.000000
18851,LDW,LDW,2021-06-30,Q,Y,788000014336.000000,788000000000.000000,0.000000
18860,LLM,LLM,2021-06-30,Q,N,797261037568.000000,797261040000.000000,0.000000
19049,PVA,PVA,2021-06-30,Q,N,218459996160.000000,218460000000.000000,0.000000
19173,SPD,SPD,2021-06-30,Q,N,120000004096.000000,120000000000.000000,0.000000
19271,TNH,TNH,2021-06-30,Q,Y,415000002560.000000,415000000000.000000,0.000000
19346,VEF,VEF,2021-06-30,Q,N,1666040463360.000000,1666040500000.000000,0.000000
19427,VTX,VTX,2021-06-30,Q,N,209723211776.000000,209723210000.000000,0.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN

In [34]:
# Check this field
cbs.check_cbs_419(df=df)

CHECK ITEM & SUB-ITEMS CBS_419

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_419,CBS_4191,CBS_4192
46,BCM,BCM,2018-03-31,Q,N,1362110178212.000000,0.000000,0.000000
129,CMF,CMF,2018-03-31,Q,N,0.000000,9057344483.000000,0.000000
168,DAT,DAT,2018-03-31,Q,N,1220836595.000000,0.000000,0.000000
380,HVN,HVN,2018-03-31,Q,N,1068628929237.000000,0.000000,0.000000
386,IDI,IDI,2018-03-31,Q,N,967463663.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
29913,ASM,ASM,2023-06-30,Q,N,5987831202.000000,0.000000,0.000000
30049,DAT,DAT,2023-06-30,Q,N,13521013335.000000,0.000000,0.000000
30071,DHD,DHD,2023-06-30,Q,N,149315764888.000000,0.000000,0.000000
30272,IDI,IDI,2023-06-30,Q,N,10714897031.000000,0.000000,0.000000
30687,TCK,TCK,2023-06-30,Q,N,10946368209.000000,0.000000,0.000000

In [35]:
cbs.check_cbs_421(df=df)

CHECK ITEM & SUB-ITEMS CBS_421

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_421,CBS_421A,CBS_421B
1861,STS,STS,2018-06-30,Q,N,37559165266.000000,0.000000,0.000000
17505,DFF,DFF,2021-03-31,Q,N,71994875904.000000,70629118587.000000,1365758301.000000
18748,HSG,HSG,2021-06-30,Q,N,5136785604608.000000,1828407993863.000000,3308377450494.000000
18851,LDW,LDW,2021-06-30,Q,Y,23135455232.000000,0.000000,23135454930.000000
18860,LLM,LLM,2021-06-30,Q,N,229250842624.000000,215032820129.000000,14218027994.000000
19049,PVA,PVA,2021-06-30,Q,N,-281138331648.000000,-281503387712.000000,365048883.000000
19173,SPD,SPD,2021-06-30,Q,N,-16133268480.000000,-16922778824.000000,789510257.000000
19271,TNH,TNH,2021-06-30,Q,Y,272277913600.000000,222502211307.000000,49775700174.000000
19346,VEF,VEF,2021-06-30,Q,N,450858778624.000000,322304133059.000000,128554629924.000000
19347,VET,VET,2021-06-30,Q,N,45976064000.000000,0.000000,45976064269.000000
19427,VTX,VTX,2021-06-30,Q,N,18553483264.000000,10596165910.000000,7957317597.000000
20440,VJC,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
26140,TNI,TNI,2022-09-30,Q,N,76049175956.000000,-10226150436.000000,86274205942.000000

In [36]:
cbs.check_cbs_430(df=df)

CHECK ITEM & SUB-ITEMS CBS_430

,SECURITY_CODE,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_430,CBS_4301,CBS_431,CBS_432
237,DUS,DUS,2018-03-31,Q,N,-48073916.000000,0.000000,0.000000,0.000000
1282,DUS,DUS,2018-06-30,Q,N,-262318572.000000,0.000000,0.000000,0.000000
2353,DUS,DUS,2018-09-30,Q,N,-13551336.000000,0.000000,0.000000,0.000000
7103,DUS,DUS,2019-06-30,Q,Y,-279245896.000000,0.000000,0.000000,0.000000
17692,HSV,HSV,2021-03-31,Q,N,0.000000,0.000000,NaN,NaN
17892,NVL,NVL,2021-03-31,Q,N,0.000000,0.000000,NaN,NaN
18851,LDW,LDW,2021-06-30,Q,Y,308004159488.000000,0.000000,0.000000,308004168538.000000
19347,VET,VET,2021-06-30,Q,N,23069173760.000000,0.000000,21923549184.000000,1145625000.000000
20440,VJC,VJC,2021-09-30,Q,Y,0.000000,0.000000,0.000000,NaN