In [1]:
import pandas as pd
import numpy as np
from check_py import check_company_bs as cbs

In [2]:
df = pd.read_excel(r"/Users/rainmeteror/Desktop/BSC_Algo_Database_UAT/OneDrive_1_5-29-2023/company/algo_cbs.xlsx")

In [3]:
cbs.check_cbs_100(df=df)

CHECK ITEM & SUB-ITEMS CBS_100

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_100,CBS_110,CBS_120,CBS_130,CBS_140,CBS_150
40,VCI,2020-12-31,Y,Y,8.312171e+12,6.425130e+11,NaN,2.217986e+11,NaN,9.752765e+10
79,AAS,2021-03-31,Q,N,4.673326e+11,1.011688e+11,2.058632e+11,1.577507e+11,0.0,3.918581e+09
180,AGR,2021-03-31,Q,N,1.771013e+12,6.593075e+10,1.631220e+12,-5.400658e+11,0.0,2.911659e+10
191,VDS,2020-12-31,Y,Y,2.514896e+12,5.822544e+11,NaN,9.612885e+09,NaN,2.940973e+09
305,VND,2020-12-31,Y,Y,1.321897e+13,9.735269e+11,NaN,2.721103e+11,NaN,1.413177e+10
...,...,...,...,...,...,...,...,...,...,...
18552,ASIAS,2021-12-31,Q,N,2.657729e+11,8.114172e+10,NaN,3.100819e+08,NaN,2.434741e+09
18656,APS,2021-12-31,Q,N,1.594590e+12,1.591105e+11,NaN,7.349657e+09,NaN,1.494383e+09
18658,KBSV,2021-12-31,Q,N,8.760537e+12,5.691005e+11,NaN,1.155571e+11,NaN,7.862363e+09
18659,KBSV,2021-12-31,Y,Y,8.760470e+12,5.691005e+11,NaN,1.154901e+11,NaN,7.862363e+09
18774,DVSC,2021-12-31,Y,Y,2.403894e+11,4.608989e+10,NaN,1.040460e+09,NaN,3.223107e+08

In [4]:
cbs.check_cbs_110(df=df)

CHECK ITEM & SUB-ITEMS CBS_110

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_110,CBS_111,CBS_112
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
860,HSV,2021-03-31,Q,N,3.723524e+09,3.723524e+09,NaN
2345,LDW,2021-06-30,Q,Y,5.424461e+10,3.391416e+10,2.033045e+10
2524,HSG,2021-06-30,Q,N,5.056541e+11,4.683123e+11,3.734175e+10
8096,VEF,2021-06-30,Q,N,2.200498e+12,3.411990e+11,1.859299e+12
11128,TDCAP,2022-03-31,Q,N,1.581471e+10,0.000000e+00,0.000000e+00
11129,TDCAP,2021-09-30,Q,N,1.677609e+10,0.000000e+00,0.000000e+00
12727,HPG,2022-09-30,Q,N,1.000000e+12,3.099218e+12,8.782190e+12
15811,LLM,2021-06-30,Q,N,1.104918e+12,5.379702e+11,5.669479e+11
18497,HVB,2021-12-31,Y,Y,3.064322e+10,0.000000e+00,0.000000e+00

In [5]:
cbs.check_cbs_120(df=df)

CHECK ITEM & SUB-ITEMS CBS_120

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_120,CBS_121,CBS_123
14,TLH,2020-12-31,Y,Y,1.538826e+11,2.152484e+10,1.338522e+11
19,TMC,2020-12-31,Y,Y,2.135410e+09,2.270159e+09,0.000000e+00
23,TH1,2020-12-31,Y,Y,1.731977e+11,1.629812e+11,1.021673e+10
29,THP,2020-12-31,Y,Y,5.107731e+09,1.347614e+08,5.000000e+09
40,VCI,2020-12-31,Y,Y,NaN,6.148236e+11,1.060000e+11
...,...,...,...,...,...,...,...
20431,MASC,2023-03-31,Q,N,1.706459e+13,1.356916e+13,3.560424e+12
20435,DNSE,2023-03-31,Q,N,5.001935e+12,3.015471e+12,2.026050e+12
20455,VHG,2023-03-31,Q,N,9.026000e+07,3.500000e+08,0.000000e+00
20466,PGC,2023-03-31,Q,N,1.263306e+12,2.610000e+09,1.262600e+12
20473,IDV,2023-03-31,Q,Y,3.520961e+11,7.000769e+09,3.452326e+11

In [6]:
cbs.check_cbs_130(df=df)

CHECK ITEM & SUB-ITEMS CBS_131

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_131,CBS_132,CBS_133,CBS_134,CBS_135,CBS_136,CBS_137,CBS_139
0,TDN,2020-12-31,Y,Y,2.174686e+11,8.937714e+09,2.532280e+09,0.0,0.000000e+00,7.183830e+08,0.000000e+00,0.0
1,TDP,2020-12-31,Y,Y,1.117786e+11,1.272985e+10,0.000000e+00,0.0,5.700000e+10,9.143903e+10,0.000000e+00,0.0
2,TDS,2020-12-31,Y,Y,1.420847e+11,3.256049e+09,0.000000e+00,0.0,0.000000e+00,3.263411e+08,-2.851314e+09,0.0
3,TDT,2020-12-31,Y,Y,2.522344e+10,4.204435e+08,0.000000e+00,0.0,2.135000e+09,4.964400e+09,0.000000e+00,0.0
4,TDW,2020-12-31,Y,Y,8.312088e+09,6.021190e+09,0.000000e+00,0.0,0.000000e+00,3.965661e+09,-2.758980e+09,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
20475,HTT,2023-03-31,Q,N,6.383089e+09,1.731488e+10,1.269090e+07,0.0,0.000000e+00,1.590626e+10,-1.162087e+10,0.0
20476,V12,2023-03-31,Q,N,1.503823e+11,5.079116e+10,0.000000e+00,0.0,0.000000e+00,1.318838e+11,-4.192543e+10,0.0
20477,PVG,2023-03-31,Q,N,3.796904e+11,4.362482e+09,0.000000e+00,0.0,0.000000e+00,1.237870e+10,-6.981913e+10,0.0
20478,PBC,2023-03-31,Q,N,1.355108e+11,2.736603e+11,0.000000e+00,0.0,0.000000e+00,1.190808e+11,-3.041002e+06,0.0
20479,TOT,2023-03-31,Q,N,3.401469e+10,3.367256e+08,0.000000e+00,0.0,0.000000e+00,4.430371e+10,-5.494928e+08,0.0

In [7]:
cbs.check_cbs_140(df=df)

CHECK ITEM & SUB-ITEMS CBS_140

      SECURITY_CODE REPORT_DATE FREQ_CODE AUDITED  CBS_140  CBS_141  CBS_149
40              VCI  2020-12-31         Y       Y      NaN      NaN      NaN
191             VDS  2020-12-31         Y       Y      NaN      NaN      NaN
305             VND  2020-12-31         Y       Y      NaN      NaN      NaN
321            VPBS  2020-12-31         Y       Y      NaN      NaN      NaN
659             VJC  2021-09-30         Q       Y      NaN      NaN      NaN
...             ...         ...       ...     ...      ...      ...      ...
18552         ASIAS  2021-12-31         Q       N      NaN      NaN      NaN
18656           APS  2021-12-31         Q       N      NaN      NaN      NaN
18658          KBSV  2021-12-31         Q       N      NaN      NaN      NaN
18659          KBSV  2021-12-31         Y       Y      NaN      NaN      NaN
18774          DVSC  2021-12-31         Y       Y      NaN      NaN      NaN

[231 rows x 7 columns]

In [8]:
cbs.check_cbs_150(df=df)

CHECK ITEM & SUB-ITEMS CBS_150

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_150,CBS_151,CBS_152,CBS_153,CBS_154,CBS_155
40,VCI,2020-12-31,Y,Y,9.752765e+10,5.499113e+09,0.0,0.0,0.0,9.133380e+10
191,VDS,2020-12-31,Y,Y,2.940973e+09,2.550539e+09,0.0,10367122.0,0.0,0.000000e+00
305,VND,2020-12-31,Y,Y,1.413177e+10,1.287241e+09,30971290.0,114236335.0,0.0,7.316325e+09
321,VPBS,2020-12-31,Y,Y,1.313763e+10,6.493557e+09,0.0,0.0,0.0,0.000000e+00
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
18552,ASIAS,2021-12-31,Q,N,2.434741e+09,1.425385e+09,0.0,0.0,0.0,0.000000e+00
18656,APS,2021-12-31,Q,N,1.494383e+09,9.312341e+07,0.0,0.0,0.0,0.000000e+00
18658,KBSV,2021-12-31,Q,N,7.862363e+09,4.110347e+09,0.0,0.0,0.0,0.000000e+00
18659,KBSV,2021-12-31,Y,Y,7.862363e+09,4.110347e+09,0.0,0.0,0.0,0.000000e+00
18774,DVSC,2021-12-31,Y,Y,3.223107e+08,2.006007e+08,0.0,0.0,0.0,0.000000e+00

In [9]:
cbs.check_cbs_200(df=df)

CHECK ITEM & SUB-ITEMS CBS_200

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_200,CBS_210,CBS_220,CBS_230,CBS_240,CBS_250,CBS_260
321,VPBS,2020-12-31,Y,Y,2.756965e+11,0.000000e+00,1.688318e+11,0.000000e+00,4.165030e+10,4.200000e+10,3.247546e+10
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN
878,HVB,2021-03-31,Q,N,2.174549e+10,6.734482e+09,3.143910e+09,0.000000e+00,0.000000e+00,3.380220e+10,1.471521e+09
1103,MIG,2021-06-30,Q,Y,9.979989e+11,1.547180e+10,7.641531e+10,0.000000e+00,3.460032e+11,1.179445e+12,6.153163e+10
1211,VPBS,2021-09-30,Q,N,2.937982e+11,0.000000e+00,2.007339e+11,0.000000e+00,2.519536e+10,4.450000e+10,3.263000e+10
...,...,...,...,...,...,...,...,...,...,...,...
17915,AIC,2021-12-31,Q,N,6.619421e+11,1.314084e+10,8.334242e+09,0.000000e+00,0.000000e+00,7.604650e+11,3.256471e+10
18343,BMS,2022-03-31,Q,N,1.051432e+10,0.000000e+00,0.000000e+00,0.000000e+00,1.230757e+10,0.000000e+00,4.631715e+09
18344,TVSI,2022-03-31,Q,N,1.588378e+11,0.000000e+00,0.000000e+00,0.000000e+00,2.025247e+10,0.000000e+00,1.349158e+11
18403,VNR,2021-12-31,Q,N,1.617656e+12,2.593601e+10,7.763665e+09,6.409861e+09,1.710790e+10,1.675987e+12,9.773950e+09
18756,KEVS,2022-03-31,Q,N,5.261917e+10,0.000000e+00,0.000000e+00,0.000000e+00,2.998292e+10,0.000000e+00,3.889759e+10

In [10]:
cbs.check_cbs_210(df=df)

CHECK ITEM & SUB-ITEMS CBS_210

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_210,CBS_211,CBS_212,CBS_213,CBS_214,CBS_215,CBS_216,CBS_219
40,VCI,2020-12-31,Y,Y,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,VDS,2020-12-31,Y,Y,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,VND,2020-12-31,Y,Y,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,VPBS,2020-12-31,Y,Y,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
18552,ASIAS,2021-12-31,Q,N,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18656,APS,2021-12-31,Q,N,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18658,KBSV,2021-12-31,Q,N,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18659,KBSV,2021-12-31,Y,Y,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18774,DVSC,2021-12-31,Y,Y,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
cbs.check_cbs_220(df=df)

CHECK ITEM & SUB-ITEMS CBS_220

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_220,CBS_221,CBS_224,CBS_227,CBS_2601
40,VCI,2020-12-31,Y,Y,1.438420e+10,8.034948e+09,0.0,6.349254e+09,5.649600e+09
305,VND,2020-12-31,Y,Y,4.426376e+10,3.427007e+10,0.0,9.993687e+09,7.272564e+09
321,VPBS,2020-12-31,Y,Y,1.688318e+11,7.174934e+10,0.0,9.708242e+10,4.165030e+10
469,BVH,2021-03-31,Q,N,1.742595e+12,8.299791e+11,0.0,9.126161e+11,NaN
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,0.000000e+00
...,...,...,...,...,...,...,...,...,...
18551,ASIAS,2021-12-31,Y,Y,5.357984e+08,9.019803e+07,0.0,4.456004e+08,1.308074e+10
18552,ASIAS,2021-12-31,Q,N,5.357984e+08,9.019803e+07,0.0,4.456004e+08,1.308074e+10
18656,APS,2021-12-31,Q,N,1.891916e+08,1.834432e+07,0.0,1.708472e+08,6.334245e+09
18756,KEVS,2022-03-31,Q,N,0.000000e+00,0.000000e+00,0.0,9.588266e+09,0.000000e+00
19092,PGI,2022-12-31,Q,N,5.446937e+11,3.106871e+11,0.0,1.944446e+11,0.000000e+00

In [12]:
cbs.check_cbs_221(df=df)

CHECK ITEM & SUB-ITEMS CBS_221

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_221,CBS_222,CBS_223
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
2481,TNH,2021-06-30,Q,Y,8.869775e+11,9.387090e+11,-5.173150e+10
2524,HSG,2021-06-30,Q,N,6.692306e+12,1.363727e+13,-6.944967e+12
7497,TCI,2022-03-31,Q,N,2.400000e+11,5.700000e+10,0.000000e+00
7527,SSV,2022-03-31,Q,N,0.000000e+00,4.950000e+11,0.000000e+00
7836,SASC,2022-03-31,Q,N,8.515053e+11,0.000000e+00,0.000000e+00
7972,APG,2022-03-31,Q,N,1.537500e+11,1.668700e+11,0.000000e+00
8063,HAC,2022-03-31,Q,N,1.507340e+10,0.000000e+00,0.000000e+00
8096,VEF,2021-06-30,Q,N,1.764420e+08,5.522680e+09,-5.346238e+09
8268,SPD,2021-06-30,Q,N,6.051230e+10,2.331868e+11,-1.726745e+11
8594,VET,2021-06-30,Q,N,2.044848e+11,5.288579e+11,-3.243731e+11
8640,VTX,2021-06-30,Q,N,7.275413e+10,5.149421e+11,-4.421880e+11
8828,IVS,2022-03-31,Q,N,0.000000e+00,6.000000e+10,0.000000e+00
9011,NVSC,2022-03-31,Q,N,3.300000e+09,0.000000e+00,0.000000e+00
9013,JSIC,2022-03-31,Q,N,0.000000e+00,1.200000e+11,0.000000e+00
9226,JBSV,2022-03-31,Q,N,0.000000e+00,1.187347e+11,0.000000e+00
9227,VFS,2022-03-31,Q,N,0.000000e+00,2.500000e+11,0.000000e+00
9935,PSI,2022-03-31,Q,N,0.000000e+00,5.001250e+10,0.000000e+00
10411,BVS,2022-03-31,Q,N,1.890311e+11,0.000000e+00,0.000000e+00
10412,VIX,2022-03-31,Q,N,1.500000e+09,0.000000e+00,0.000000e+00
10419,SJCS,2022-03-31,Q,N,1.000000e+09,0.000000e+00,0.000000e+00
12524,BSI,2022-03-31,Q,N,0.000000e+00,2.295205e+11,0.000000e+00
13953,HBS,2022-03-31,Q,N,5.896160e+09,0.000000e+00,0.000000e+00
14092,WSS,2022-03-31,Q,N,1.975000e+10,0.000000e+00,0.000000e+00
14477,VND,2022-03-31,Q,N,1.800000e+10,0.000000e+00,0.000000e+00
15722,DFF,2021-03-31,Q,N,3.876773e+11,5.841477e+11,-1.964704e+11
17302,SSI,2022-03-31,Q,N,3.381972e+12,0.000000e+00,6.111587e+11
17414,BETA,2022-03-31,Q,N,8.700950e+10,0.000000e+00,0.000000e+00
17841,MASC,2022-03-31,Q,N,5.726180e+08,2.100000e+11,0.000000e+00
18497,HVB,2021-12-31,Y,Y,2.292720e+09,0.000000e+00,0.000000e+00

In [13]:
cbs.check_cbs_224(df=df)

CHECK ITEM & SUB-ITEMS CBS_224

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_224,CBS_225,CBS_226
305,VND,2020-12-31,Y,Y,0.0,30971290.0,0.000000e+00
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
860,HSV,2021-03-31,Q,N,0.0,NaN,NaN
1100,DNSE,2021-06-30,Q,Y,0.0,30524321.0,0.000000e+00
1165,TVSI,2021-06-30,Q,Y,0.0,24542325.0,0.000000e+00
...,...,...,...,...,...,...,...
18333,FTS,2021-12-31,Y,Y,0.0,229033.0,0.000000e+00
18343,BMS,2022-03-31,Q,N,0.0,0.0,5.882608e+09
18344,TVSI,2022-03-31,Q,N,0.0,0.0,2.047826e+10
18371,FTS,2021-12-31,Q,N,0.0,229033.0,0.000000e+00
18756,KEVS,2022-03-31,Q,N,0.0,0.0,1.344353e+10

In [14]:
cbs.check_cbs_227(df=df)

CHECK ITEM & SUB-ITEMS CBS_227

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_227,CBS_228,CBS_229
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
860,HSV,2021-03-31,Q,N,4.669047e+08,4.669047e+08,NaN
2345,LDW,2021-06-30,Q,Y,1.495889e+09,1.903591e+09,-4.077016e+08
2524,HSG,2021-06-30,Q,N,2.131211e+11,2.852100e+11,-7.208888e+10
8640,VTX,2021-06-30,Q,N,7.624333e+09,9.498251e+09,-1.873919e+09
15722,DFF,2021-03-31,Q,N,7.826638e+09,1.129951e+10,-3.472867e+09
15811,LLM,2021-06-30,Q,N,1.641393e+10,1.837010e+10,-1.956165e+09
18497,HVB,2021-12-31,Y,Y,9.828566e+07,0.000000e+00,0.000000e+00

In [15]:
cbs.check_cbs_230(df=df)

CHECK ITEM & SUB-ITEMS CBS_230

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_230,CBS_231,CBS_232
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
860,HSV,2021-03-31,Q,N,0.000000e+00,NaN,NaN
2481,TNH,2021-06-30,Q,Y,2.442301e+10,2.491581e+10,-4.927976e+08
7497,TCI,2022-03-31,Q,N,0.000000e+00,0.000000e+00,8.453817e+09
7524,CASC,2022-03-31,Q,N,0.000000e+00,0.000000e+00,9.115671e+08
...,...,...,...,...,...,...,...
17841,MASC,2022-03-31,Q,N,0.000000e+00,0.000000e+00,1.067107e+10
17882,VCI,2022-03-31,Q,N,0.000000e+00,0.000000e+00,2.408367e+09
18343,BMS,2022-03-31,Q,N,0.000000e+00,0.000000e+00,1.612518e+09
18344,TVSI,2022-03-31,Q,N,0.000000e+00,0.000000e+00,3.468744e+09
18756,KEVS,2022-03-31,Q,N,0.000000e+00,0.000000e+00,3.855260e+09

In [30]:
cbs.check_cbs_230(df=df)

CHECK ITEM & SUB-ITEMS CBS_230

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_230,CBS_231,CBS_232
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
860,HSV,2021-03-31,Q,N,0.000000e+00,NaN,NaN
2481,TNH,2021-06-30,Q,Y,2.442301e+10,2.491581e+10,-4.927976e+08
7497,TCI,2022-03-31,Q,N,0.000000e+00,0.000000e+00,8.453817e+09
7524,CASC,2022-03-31,Q,N,0.000000e+00,0.000000e+00,9.115671e+08
...,...,...,...,...,...,...,...
17841,MASC,2022-03-31,Q,N,0.000000e+00,0.000000e+00,1.067107e+10
17882,VCI,2022-03-31,Q,N,0.000000e+00,0.000000e+00,2.408367e+09
18343,BMS,2022-03-31,Q,N,0.000000e+00,0.000000e+00,1.612518e+09
18344,TVSI,2022-03-31,Q,N,0.000000e+00,0.000000e+00,3.468744e+09
18756,KEVS,2022-03-31,Q,N,0.000000e+00,0.000000e+00,3.855260e+09

In [17]:
cbs.check_cbs_240(df=df)

CHECK ITEM & SUB-ITEMS CBS_240

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_240,CBS_241,CBS_242
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
860,HSV,2021-03-31,Q,N,0.000000e+00,NaN,NaN
7497,TCI,2022-03-31,Q,N,2.987466e+10,-2.142084e+10,0.0
7524,CASC,2022-03-31,Q,N,1.208120e+09,-2.965529e+08,0.0
7525,DDSC,2022-03-31,Q,N,5.261700e+10,-3.051372e+10,0.0
...,...,...,...,...,...,...,...
17841,MASC,2022-03-31,Q,N,2.639785e+10,-1.572679e+10,0.0
17882,VCI,2022-03-31,Q,N,4.998143e+10,-4.757306e+10,0.0
18343,BMS,2022-03-31,Q,N,1.230757e+10,-1.069505e+10,0.0
18344,TVSI,2022-03-31,Q,N,2.025247e+10,-1.678373e+10,0.0
18756,KEVS,2022-03-31,Q,N,2.998292e+10,-2.612766e+10,0.0

In [18]:
cbs.check_cbs_250(df=df)

CHECK ITEM & SUB-ITEMS CBS_250

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_250,CBS_251,CBS_252,CBS_253,CBS_254,CBS_255
321,VPBS,2020-12-31,Y,Y,4.200000e+10,0.0,0.0,4.200000e+10,-9.261000e+09,0.000000e+00
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN
860,HSV,2021-03-31,Q,N,0.000000e+00,NaN,NaN,NaN,NaN,NaN
1211,VPBS,2021-09-30,Q,N,4.450000e+10,0.0,0.0,4.450000e+10,-9.261000e+09,0.000000e+00
1814,SJCS,2020-03-31,Q,N,-1.000000e+09,0.0,0.0,1.000000e+09,-1.000000e+09,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
17882,VCI,2022-03-31,Q,N,0.000000e+00,0.0,0.0,6.064600e+09,0.000000e+00,6.064600e+09
18344,TVSI,2022-03-31,Q,N,0.000000e+00,0.0,0.0,3.443796e+09,0.000000e+00,3.443796e+09
18497,HVB,2021-12-31,Y,Y,7.730220e+10,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00
18756,KEVS,2022-03-31,Q,N,0.000000e+00,0.0,0.0,2.780500e+08,0.000000e+00,2.780500e+08
19177,IVS,2022-12-31,Q,N,0.000000e+00,0.0,0.0,0.000000e+00,-1.700000e+10,0.000000e+00

In [19]:
cbs.check_cbs_260(df=df)

CHECK ITEM & SUB-ITEMS CBS_260

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_260,CBS_261,CBS_262,CBS_263,CBS_268,CBS_269
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN,NaN,NaN,NaN
860,HSV,2021-03-31,Q,N,3.389157e+08,3.389157e+08,NaN,NaN,NaN,NaN
878,HVB,2021-03-31,Q,N,1.471521e+09,1.471521e+09,0.000000e+00,NaN,0.000000e+00,0.0
1103,MIG,2021-06-30,Q,Y,6.153163e+10,6.153163e+10,0.000000e+00,NaN,0.000000e+00,0.0
2338,BMI,2021-06-30,Q,Y,5.543284e+10,2.592289e+10,2.950994e+10,NaN,0.000000e+00,0.0
...,...,...,...,...,...,...,...,...,...,...
17159,AIC,2022-03-31,Q,N,2.734228e+10,2.734228e+10,0.000000e+00,NaN,0.000000e+00,0.0
17914,AIC,2021-12-31,Y,Y,3.256471e+10,3.256471e+10,0.000000e+00,NaN,0.000000e+00,0.0
17915,AIC,2021-12-31,Q,N,3.256471e+10,3.256471e+10,0.000000e+00,NaN,0.000000e+00,0.0
18403,VNR,2021-12-31,Q,N,9.773950e+09,9.646636e+08,9.509530e+08,NaN,7.858333e+09,0.0
18497,HVB,2021-12-31,Y,Y,7.389664e+08,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0

In [20]:
cbs.check_cbs_300(df=df)

CHECK ITEM & SUB-ITEMS CBS_300

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_300,CBS_310,CBS_330
469,BVH,2021-03-31,Q,N,1.253363e+14,1.472385e+13,5.602721e+11
530,BVH,2021-06-30,Q,Y,1.273669e+14,1.210419e+13,5.816977e+11
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
2068,BVH,2020-06-30,Q,Y,1.173497e+14,2.198023e+13,5.771985e+11
2345,LDW,2021-06-30,Q,Y,3.154859e+11,7.284834e+10,2.426376e+11
2481,TNH,2021-06-30,Q,Y,5.472533e+11,1.883280e+11,3.589253e+11
2524,HSG,2021-06-30,Q,N,1.530500e+13,1.366626e+13,1.638738e+12
2536,BVH,2020-03-31,Q,N,1.134138e+14,2.233421e+13,8.519072e+11
3218,BVH,2020-09-30,Q,N,1.240416e+14,2.356541e+13,5.548843e+11
4911,BVH,2020-12-31,Q,N,1.265146e+14,2.068065e+13,5.674336e+11
8268,SPD,2021-06-30,Q,N,3.189071e+11,3.089029e+11,1.000420e+10
12727,HPG,2022-09-30,Q,N,1.000000e+12,1.000000e+12,1.000000e+12
15722,DFF,2021-03-31,Q,N,1.342179e+12,9.944130e+11,3.477661e+11
15811,LLM,2021-06-30,Q,N,6.233381e+12,6.208592e+12,2.478807e+10

In [21]:
cbs.check_cbs_310(df=df)

CHECK ITEM & SUB-ITEMS CBS_310

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_310,CBS_311,CBS_312,CBS_313,CBS_314,CBS_315,CBS_316,CBS_317,CBS_318,CBS_319,CBS_320,CBS_321,CBS_322,CBS_323,CBS_324,CBS_3241
40,VCI,2020-12-31,Y,Y,3.733857e+12,1.001139e+11,7.971370e+09,9.585542e+10,8.908669e+10,2.982053e+10,0.0,0.0,0.000000e+00,7.148793e+11,2.696130e+12,0.000000e+00,0.000000e+00,NaN,0.000000e+00,NaN
191,VDS,2020-12-31,Y,Y,1.390464e+12,2.278698e+10,1.729878e+09,2.457065e+10,1.838569e+10,1.224225e+10,0.0,0.0,0.000000e+00,1.241154e+12,6.959400e+10,0.000000e+00,0.000000e+00,NaN,0.000000e+00,NaN
305,VND,2020-12-31,Y,Y,1.104018e+13,3.273109e+09,9.257295e+09,9.431683e+10,1.760117e+10,4.641014e+10,0.0,0.0,2.126250e+09,1.397999e+12,9.458280e+12,0.000000e+00,1.091993e+10,NaN,0.000000e+00,NaN
321,VPBS,2020-12-31,Y,Y,1.093219e+13,5.119859e+11,1.595000e+08,1.068623e+11,4.034667e+07,1.335932e+11,0.0,0.0,0.000000e+00,3.202723e+12,6.976830e+12,0.000000e+00,9.111800e+04,NaN,0.000000e+00,NaN
469,BVH,2021-03-31,Q,N,1.472385e+13,2.737315e+12,1.463537e+10,1.737967e+11,5.400559e+11,7.060048e+10,0.0,0.0,1.982667e+11,8.912531e+11,1.094768e+12,0.000000e+00,1.192416e+11,0.0,8.883918e+12,1.100521e+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19953,VNR,2022-12-31,Y,Y,3.668096e+12,4.463390e+11,6.418389e+08,3.024381e+10,2.355333e+10,1.227470e+09,0.0,0.0,0.000000e+00,1.670343e+11,0.000000e+00,3.266273e+10,2.843675e+10,NaN,0.000000e+00,2.937957e+12
20077,ABI,2023-03-31,Q,N,2.227726e+12,1.894356e+11,0.000000e+00,2.188616e+10,3.592785e+10,0.000000e+00,0.0,0.0,8.374009e+10,3.943919e+10,0.000000e+00,0.000000e+00,5.865082e+10,NaN,0.000000e+00,1.798646e+12
20087,PVI,2022-06-30,Q,Y,1.823139e+13,3.341872e+12,4.506141e+11,1.164546e+11,2.625184e+11,5.252673e+10,0.0,0.0,5.981501e+09,1.427835e+11,7.233136e+11,0.000000e+00,3.717856e+10,NaN,0.000000e+00,1.309815e+13
20391,BLI,2023-03-31,Q,N,1.684047e+12,3.763323e+11,0.000000e+00,1.402859e+10,1.253739e+10,3.153982e+09,0.0,0.0,3.469993e+09,1.344038e+11,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,1.140121e+12
20396,PRE,2023-03-31,Q,N,5.394768e+12,7.328706e+11,0.000000e+00,1.349217e+10,3.237672e+09,0.000000e+00,0.0,0.0,0.000000e+00,7.696719e+11,1.700341e+11,0.000000e+00,2.353755e+09,NaN,0.000000e+00,3.703108e+12

In [22]:
cbs.check_cbs_330(df=df)

CHECK ITEM & SUB-ITEMS CBS_330

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_330,CBS_331,CBS_332,CBS_333,CBS_334,CBS_335,CBS_336,CBS_337,CBS_338,CBS_339,CBS_340,CBS_341,CBS_342,CBS_343
40,VCI,2020-12-31,Y,Y,1.270615e+11,0.0,0.000000e+00,0.0,NaN,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,NaN,1.270615e+11,0.0,0.0
55,TL4,2020-12-31,Y,Y,2.663571e+11,0.0,4.763561e+10,0.0,0.0,0.0,0.0,1.310634e+11,7.305838e+10,0.000000e+00,0.0,9.727300e+08,0.0,0.0
171,ACC,2021-03-31,Q,N,1.091018e+10,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.856105e+08,0.0,0.0
191,VDS,2020-12-31,Y,Y,1.237548e+10,0.0,0.000000e+00,0.0,NaN,0.0,0.0,6.126330e+08,0.000000e+00,0.000000e+00,NaN,1.176284e+10,0.0,0.0
305,VND,2020-12-31,Y,Y,1.166561e+11,0.0,0.000000e+00,0.0,NaN,0.0,0.0,0.000000e+00,0.000000e+00,1.036410e+11,NaN,1.301508e+10,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18659,KBSV,2021-12-31,Y,Y,3.260269e+07,0.0,0.000000e+00,0.0,NaN,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,NaN,3.260269e+07,0.0,0.0
18774,DVSC,2021-12-31,Y,Y,0.000000e+00,0.0,0.000000e+00,0.0,NaN,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.0,0.0
19265,BVH,2022-12-31,Y,Y,1.478892e+14,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2.966963e+11,9.102353e+10,0.000000e+00,0.0,4.840608e+09,0.0,0.0
19267,BVH,2022-12-31,Q,N,1.477610e+14,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2.839344e+11,9.129905e+10,0.000000e+00,0.0,4.773922e+09,0.0,0.0
20391,BLI,2023-03-31,Q,N,3.626399e+09,0.0,0.000000e+00,0.0,0.0,0.0,0.0,1.800000e+08,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0

In [23]:
cbs.check_cbs_400(df=df)

CHECK ITEM & SUB-ITEMS CBS_400

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_400,CBS_410,CBS_430
659,VJC,2021-09-30,Q,Y,NaN,NaN,0.000000e+00
878,HVB,2021-03-31,Q,N,3.234209e+11,3.234209e+11,NaN
1103,MIG,2021-06-30,Q,Y,1.639474e+12,1.639474e+12,NaN
2338,BMI,2021-06-30,Q,Y,2.233614e+12,2.233614e+12,NaN
2345,LDW,2021-06-30,Q,Y,1.172390e+12,8.643854e+11,3.080042e+11
4764,PVI,2020-12-31,Q,N,7.186514e+12,7.186514e+12,NaN
5680,PVI,2020-09-30,Q,N,6.982450e+12,6.982450e+12,NaN
6541,BVH,2020-12-31,Y,Y,2.082177e+13,2.082177e+13,NaN
7254,BIC,2021-09-30,Q,N,2.466643e+12,2.466643e+12,NaN
7255,BMI,2021-09-30,Q,N,2.278136e+12,2.278136e+12,NaN
7256,PGI,2021-09-30,Q,N,1.686400e+12,1.686400e+12,NaN
7291,PTI,2021-09-30,Q,N,2.121653e+12,2.121653e+12,NaN
7292,PVI,2021-09-30,Q,N,7.280335e+12,7.280335e+12,NaN
7293,AIC,2021-09-30,Q,N,1.047837e+12,1.047837e+12,NaN
7294,PRE,2021-09-30,Q,N,9.047237e+11,9.047237e+11,NaN
7449,PVI,2021-12-31,Q,N,7.849934e+12,7.849934e+12,NaN
7810,PVI,2021-12-31,Y,Y,7.839963e+12,7.839963e+12,NaN
7846,ABI,2021-09-30,Q,N,1.251547e+12,1.251547e+12,NaN
7977,BLI,2022-03-31,Q,N,8.603163e+11,8.603163e+11,NaN
8594,VET,2021-06-30,Q,N,3.583130e+11,3.352438e+11,2.306917e+10
8770,BMI,2021-12-31,Q,N,2.331418e+12,2.331418e+12,NaN
8815,ABI,2021-12-31,Q,N,1.235759e+12,1.235759e+12,NaN
9009,PTI,2022-03-31,Q,N,2.218301e+12,2.218301e+12,NaN
9696,MIG,2021-09-30,Q,N,1.672033e+12,1.672033e+12,NaN
9789,PGI,2022-03-31,Q,N,1.848525e+12,1.848525e+12,NaN
9801,BLI,2021-09-30,Q,N,7.615143e+11,7.615143e+11,NaN
9802,BVH,2021-09-30,Q,Y,2.215629e+13,2.215629e+13,NaN
9803,VNR,2021-09-30,Q,N,3.214946e+12,3.214946e+12,NaN
10203,BIC,2021-12-31,Q,N,2.567312e+12,2.567312e+12,NaN
10731,MIG,2021-12-31,Y,Y,1.747285e+12,1.747285e+12,NaN
10771,MIG,2021-12-31,Q,N,1.747841e+12,1.747841e+12,NaN
10772,BIC,2021-12-31,Y,Y,2.575490e+12,2.575490e+12,NaN
10779,MIG,2022-03-31,Q,N,1.815255e+12,1.815255e+12,NaN
11433,PRE,2021-12-31,Y,Y,8.948422e+11,8.948422e+11,NaN
11434,PRE,2021-12-31,Q,N,8.947838e+11,8.947838e+11,NaN
11646,VASS,2021-12-31,Y,Y,3.459197e+11,3.459197e+11,NaN
11647,VASS,2020-12-31,Y,Y,3.437622e+11,3.437622e+11,NaN
12727,HPG,2022-09-30,Q,N,1.000000e+12,1.000000e+12,0.000000e+00
13718,BIC,2022-03-31,Q,N,2.639258e+12,2.639258e+12,NaN
13878,BMI,2021-12-31,Y,Y,2.335356e+12,2.335356e+12,NaN
14131,BMI,2022-03-31,Q,N,2.398969e+12,2.398969e+12,NaN
14405,ABI,2022-03-31,Q,N,1.290961e+12,1.290961e+12,NaN
14756,PVI,2021-03-31,Q,N,7.340873e+12,7.340873e+12,NaN
15193,PTI,2021-12-31,Y,Y,2.180223e+12,2.180223e+12,NaN
15194,PTI,2021-12-31,Q,N,2.191731e+12,2.191731e+12,NaN
15276,BLI,2021-12-31,Q,N,7.323025e+11,7.323025e+11,NaN
15277,BLI,2021-12-31,Y,Y,7.323025e+11,7.323025e+11,NaN
15562,VNR,2022-03-31,Q,N,3.367020e+12,3.367020e+12,NaN
15811,LLM,2021-06-30,Q,N,1.082131e+12,1.080237e+12,1.894348e+09
15848,PGI,2021-06-30,Q,Y,1.588979e+12,1.588979e+12,NaN
15924,PGI,2021-12-31,Q,N,1.777934e+12,1.777934e+12,NaN
16104,BVH,2021-12-31,Q,N,2.201259e+13,2.201259e+13,NaN
16109,VNR,2021-12-31,Y,Y,3.285675e+12,3.285675e+12,NaN
16431,ABI,2021-12-31,Y,Y,1.234878e+12,1.234878e+12,NaN
17156,PVI,2022-03-31,Q,N,8.064079e+12,8.064079e+12,NaN
17159,AIC,2022-03-31,Q,N,1.068569e+12,1.068569e+12,NaN
17914,AIC,2021-12-31,Y,Y,1.052275e+12,1.052275e+12,NaN
17915,AIC,2021-12-31,Q,N,1.051330e+12,1.051330e+12,NaN
18403,VNR,2021-12-31,Q,N,3.285675e+12,3.285675e+12,NaN

In [24]:
cbs.check_cbs_410(df=df)

CHECK ITEM & SUB-ITEMS CBS_410

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_410,CBS_411,CBS_412,CBS_413,CBS_414,CBS_415,CBS_416,CBS_417,CBS_418,CBS_419,CBS_420,CBS_421,CBS_429
35,VCBS,2020-12-31,Y,Y,1.805876e+12,1.000000e+12,0.000000e+00,0.0,0.0,0.0,-2.213904e+08,0.0,0.0,0.0,6.505103e+10,6.648228e+11,0.0
40,VCI,2020-12-31,Y,Y,4.521487e+12,1.656000e+12,5.849173e+11,0.0,0.0,0.0,4.266953e+11,0.0,NaN,NaN,1.157572e+11,1.572517e+12,0.0
79,AAS,2021-03-31,Q,N,3.495409e+11,3.100000e+11,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,2.296342e+09,3.494820e+10,0.0
86,TVB,2020-12-31,Y,Y,6.026885e+11,5.472587e+11,1.633889e+10,0.0,0.0,0.0,1.551122e+10,0.0,0.0,0.0,2.927843e+09,1.772402e+10,0.0
93,TVS,2020-12-31,Y,Y,1.308177e+12,9.823517e+11,1.110413e+08,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,1.809782e+10,2.523549e+11,344857706.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20421,SBS,2023-03-31,Q,N,3.429062e+11,1.466076e+12,1.403000e+11,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,5.356928e+10,-1.372562e+12,0.0
20435,DNSE,2023-03-31,Q,N,3.184082e+12,3.000000e+12,4.157530e+07,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,2.598930e+09,1.782066e+11,0.0
20442,VNSC,2023-03-31,Q,N,2.977960e+11,5.586000e+11,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,-2.610589e+11,0.0
20444,PNSC,2023-03-31,Q,N,5.224629e+11,4.631000e+11,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,5.105497e+09,4.915186e+10,0.0
20445,DVSC,2023-03-31,Q,N,2.385560e+11,2.500000e+11,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,4.237405e+09,-1.924377e+10,0.0

In [25]:
cbs.check_cbs_411(df=df)

CHECK ITEM & SUB-ITEMS CBS_411

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_411,CBS_411A,CBS_411B
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
860,HSV,2021-03-31,Q,N,5.000000e+10,5.000000e+10,NaN
2345,LDW,2021-06-30,Q,Y,7.880000e+11,7.880000e+11,0.0
2481,TNH,2021-06-30,Q,Y,4.150000e+11,4.150000e+11,0.0
2524,HSG,2021-06-30,Q,N,4.446252e+12,4.446252e+12,0.0
8096,VEF,2021-06-30,Q,N,1.666040e+12,1.666040e+12,0.0
8268,SPD,2021-06-30,Q,N,1.200000e+11,1.200000e+11,0.0
8554,PVA,2021-06-30,Q,N,2.184600e+11,2.184600e+11,0.0
8640,VTX,2021-06-30,Q,N,2.097232e+11,2.097232e+11,0.0
15094,NVL,2021-03-31,Q,N,1.072812e+13,1.072812e+13,NaN
15722,DFF,2021-03-31,Q,N,4.000000e+11,4.000000e+11,0.0
15811,LLM,2021-06-30,Q,N,7.972610e+11,7.972610e+11,0.0
18497,HVB,2021-12-31,Y,Y,3.000000e+11,0.000000e+00,0.0

In [26]:
cbs.check_cbs_419(df=df)

CHECK ITEM & SUB-ITEMS CBS_419

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_419,CBS_4191,CBS_4192
35,VCBS,2020-12-31,Y,Y,0.0,7.622366e+10,0.0
40,VCI,2020-12-31,Y,Y,NaN,1.656000e+11,NaN
68,TTZ,2020-12-31,Y,Y,0.0,NaN,0.0
73,VC2,2020-12-31,Y,Y,0.0,NaN,0.0
75,VC6,2020-12-31,Y,Y,0.0,NaN,0.0
...,...,...,...,...,...,...,...
20421,SBS,2023-03-31,Q,N,0.0,5.552318e+10,0.0
20435,DNSE,2023-03-31,Q,N,0.0,3.234930e+09,0.0
20442,VNSC,2023-03-31,Q,N,0.0,2.549980e+08,0.0
20444,PNSC,2023-03-31,Q,N,0.0,5.105497e+09,0.0
20445,DVSC,2023-03-31,Q,N,0.0,3.562405e+09,0.0

In [27]:
cbs.check_cbs_421(df=df)

CHECK ITEM & SUB-ITEMS CBS_421

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_421,CBS_421A,CBS_421B
40,VCI,2020-12-31,Y,Y,1.572517e+12,NaN,6.806610e+10
191,VDS,2020-12-31,Y,Y,1.095539e+11,NaN,1.184187e+10
305,VND,2020-12-31,Y,Y,1.452288e+12,NaN,7.425022e+10
321,VPBS,2020-12-31,Y,Y,1.335819e+12,NaN,-2.301777e+09
659,VJC,2021-09-30,Q,Y,NaN,NaN,NaN
...,...,...,...,...,...,...,...
18552,ASIAS,2021-12-31,Q,N,2.296050e+09,NaN,0.000000e+00
18656,APS,2021-12-31,Q,N,5.636032e+11,NaN,3.200539e+11
18658,KBSV,2021-12-31,Q,N,6.812542e+11,NaN,2.803566e+07
18659,KBSV,2021-12-31,Y,Y,6.808895e+11,NaN,2.804500e+07
18774,DVSC,2021-12-31,Y,Y,-1.184060e+10,NaN,2.734145e+09

In [28]:
cbs.check_cbs_430(df=df)

CHECK ITEM & SUB-ITEMS CBS_430

,SECURITY_CODE,REPORT_DATE,FREQ_CODE,AUDITED,CBS_430,CBS_4301,CBS_431,CBS_432
40,VCI,2020-12-31,Y,Y,0.0,0.000000e+00,NaN,NaN
191,VDS,2020-12-31,Y,Y,0.0,0.000000e+00,NaN,NaN
305,VND,2020-12-31,Y,Y,0.0,1.091993e+10,NaN,NaN
321,VPBS,2020-12-31,Y,Y,0.0,9.111800e+04,NaN,NaN
659,VJC,2021-09-30,Q,Y,0.0,0.000000e+00,0.0,NaN
...,...,...,...,...,...,...,...,...
18552,ASIAS,2021-12-31,Q,N,0.0,0.000000e+00,NaN,NaN
18656,APS,2021-12-31,Q,N,0.0,3.904980e+08,NaN,NaN
18658,KBSV,2021-12-31,Q,N,0.0,9.171110e+08,NaN,NaN
18659,KBSV,2021-12-31,Y,Y,0.0,9.171110e+08,NaN,NaN
18774,DVSC,2021-12-31,Y,Y,0.0,1.189265e+06,NaN,NaN